<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">listUsers</value>
  <array name="sig" type="value" depth="1">
    <value>[i] record:0:optional input</value>
    <value>[i] - field:1:optional authIds</value>
    <value>[i] - recref:1:optional userIdentities wm.mft.assets.rec.profile:UserProfile</value>
    <value>[i] field:0:required Locale</value>
    <value>[o] record:0:required output</value>
    <value>[o] - field:1:optional userDataStr</value>
    <value>[o] - recref:0:optional svcResponse wm.mft.portal.rec:svcResponse</value>
  </array>
  <value name="subtype">unknown</value>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">CgkgICAgSURhdGFDdXJzb3IgY3VyID0gbnVsbDsKICAgICAgICBJRGF0YSBvdXRwdXQgPSBJRGF0
YUZhY3RvcnkuY3JlYXRlKCk7IAoJCUlEYXRhIHN2Y1Jlc3AgPSBudWxsOwoJCVN0cmluZyBzdmNO
YW1lID0gIndtLm1mdC5wb3J0YWwudXNlcjpsaXN0VXNlcnMiOyAKCQlVc2VySWRlbnRpdHlbXSBp
ZGVudGl0aWVzID0gbnVsbDsKCSAgICB0cnkgewoKCSAgICAJSURhdGEgaW5wdXQgPSAoSURhdGEp
VmFsdWVzRW11bGF0b3IuZ2V0KHBpcGVsaW5lLCAiaW5wdXQiKTsKCSAgICAJaWYgKGlucHV0ICE9
IG51bGwpIAoJICAgIAl7CgkgICAgCQlPYmplY3Qgb2JqID0gVmFsdWVzRW11bGF0b3IuZ2V0KGlu
cHV0LCJhdXRoSWRzIik7CgkgICAgCQlpZihvYmogIT0gbnVsbCAmJiBvYmogaW5zdGFuY2VvZiBT
dHJpbmdbXSkKCSAgICAJCXsKCSAgICAJCQlTdHJpbmdbXSBhdXRoSWRzPSAoU3RyaW5nIFtdKSBv
Ymo7CgkJICAgIAkJaWRlbnRpdGllcyA9IG5ldyBVc2VySWRlbnRpdHlbYXV0aElkcy5sZW5ndGhd
OwoJCSAgICAJCWZvcihpbnQgaSA9IDA7IGkgPCBpZGVudGl0aWVzLmxlbmd0aDsgaSsrKQoJCSAg
ICAJCXsKCQkgICAgCQkJaWRlbnRpdGllc1tpXSA9IG5ldyBVc2VySWRlbnRpdHkoYXV0aElkc1tp
XSwgVXNlcklkZW50aXR5LlVTRVIpOwoJCSAgICAJCX0KCSAgICAJCX0KCSAgICAJCQoJICAgIAkJ
CgkgICAgCQlPYmplY3QgdWlkb2JqID0gVmFsdWVzRW11bGF0b3IuZ2V0KGlucHV0LCJ1c2VySWRl
bnRpdGllcyIpOwoJICAgIAkJaWYodWlkb2JqICE9IG51bGwgJiYgdWlkb2JqIGluc3RhbmNlb2Yg
SURhdGFbXSkKCSAgICAJCXsKCSAgICAJCQlJRGF0YVtdIGlBcnJheSA9IChJRGF0YVtdKSB1aWRv
Ymo7CgkgICAgCQkJaWRlbnRpdGllcyA9IG5ldyBVc2VySWRlbnRpdHlbaUFycmF5Lmxlbmd0aF07
CgkgICAgCQkJZm9yKGludCBpID0gMDsgaSA8IGlkZW50aXRpZXMubGVuZ3RoOyBpKyspCgkJICAg
IAkJewoJICAgIAkJCQlJRGF0YSByb3cgPSBpQXJyYXlbaV07CgkJICAgIAkJCWlkZW50aXRpZXNb
aV0gPSBuZXcgVXNlcklkZW50aXR5KFZhbHVlc0VtdWxhdG9yLmdldFN0cmluZyhyb3csICJpZCIp
LCBWYWx1ZXNFbXVsYXRvci5nZXRTdHJpbmcocm93LCAidHlwZSIpKTsKCQkgICAgCQl9CgkgICAg
CQl9CgkgICAgCQkKCSAgICAJfQoJICAgIAkKCSAgICAJTGlzdDxVc2VyQ29uZmlnPiB1c2VycyA9
IFVzZXJNYW5hZ2VyUHJveHkubGlzdFVzZXJzKGlkZW50aXRpZXMpOwoJICAgICAgICBpZiAodXNl
cnMgIT0gbnVsbCAmJiB1c2Vycy5zaXplKCkgIT0gMCl7CgkgICAgICAgIAlTdHJpbmdbXSBzZXJ2
ZXJMaXN0ID0gbmV3IFN0cmluZ1t1c2Vycy5zaXplKCldOwoJICAgICAgICAJCgkgICAgICAgIAlp
bnQgaW5kZXggPTA7CgkgICAgICAgIAlmb3IgKE9iamVjdCB1c2VyRGF0YTp1c2Vycyl7CgkgICAg
ICAgIAkJc2VydmVyTGlzdFtpbmRleF0gPSBCYXNlNjRVdGlsLmVuY29kZU9iamVjdCh1c2VyRGF0
YSk7CgkgICAgICAgIAkJaW5kZXgrKzsKCSAgICAgICAgCX0KCSAgICAgICAgCQoJICAgICAgICAJ
VmFsdWVzRW11bGF0b3IucHV0KG91dHB1dCwgInVzZXJEYXRhU3RyIiwgc2VydmVyTGlzdCk7Cgkg
ICAgICAgIAkKCSAgICAgICAgfQoKCSAgICB9Y2F0Y2ggKFRocm93YWJsZSB0KXsKCSAgICAJc3Zj
UmVzcCA9IFBvcnRhbFV0aWxzLmNhdGNoRXJyb3IodCwgc3ZjTmFtZSwgU2hhcmVkQ29uc3RhbnRz
LkVSUk9SICxzdmNSZXNwKTsKCSAgICB9ZmluYWxseSB7CgkgICAgCWlmIChjdXIgIT0gbnVsbCl7
CgkgICAgCQljdXIuZGVzdHJveSgpOwoJICAgIAl9CgkgICAgCVZhbHVlc0VtdWxhdG9yLnB1dChv
dXRwdXQsICJzdmNSZXNwb25zZSIsIHN2Y1Jlc3ApOwogICAgICAgIAlWYWx1ZXNFbXVsYXRvci5w
dXQocGlwZWxpbmUsICJvdXRwdXQiLCBvdXRwdXQpOwkgICAgICAgIAkKCSAgICB9CgkJCg==</value>
</Values>
