<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">listPartnerVFS</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:required Locale</value>
    <value>[i] field:0:optional partnerID</value>
    <value>[i] field:0:optional userID</value>
    <value>[i] field:0:optional vfsName</value>
    <value>[i] field:0:optional pageNum</value>
    <value>[i] field:0:optional pageSize</value>
    <value>[i] field:0:optional pageDepth</value>
    <value>[o] record:0:required output</value>
    <value>[o] - field:0:optional totalPages</value>
    <value>[o] - record:1:optional vfsPartnerList</value>
    <value>[o] -- field:0:optional partnerID</value>
    <value>[o] -- field:0:optional partnerName</value>
    <value>[o] -- field:0:optional vfsListStr</value>
    <value>[o] - recref:0:optional svcResponse wm.mft.portal.rec:svcResponse</value>
  </array>
  <value name="subtype">unknown</value>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">CgkgICAgSURhdGFDdXJzb3IgY3VyID0gbnVsbDsKICAgICAgICBJRGF0YSBvdXRwdXQgPSBJRGF0
YUZhY3RvcnkuY3JlYXRlKCk7IAoJCUlEYXRhIHN2Y1Jlc3AgPSBudWxsOwoJCVN0cmluZyBwYXJ0
bmVySUQgPSBudWxsLCB2ZnNMaXN0U3RyID0gbnVsbCwgdXNlcklEID0gbnVsbCwgdmZzTmFtZSA9
IG51bGw7CgkJaW50IHBhZ2VOdW1iZXIgPSAtMSwgcGFnZVNpemUgPSAtMSwgcGFnZURlcHRoID0g
LTE7CgkJU3RyaW5nIHN2Y05hbWUgPSAid20ubWZ0LnBvcnRhbC52ZnM6bGlzdFZGUyI7CgkgICAg
dHJ5IHsKCgkgICAgCWN1ciA9IHBpcGVsaW5lLmdldEN1cnNvcigpOwoJICAgIAlpZiAoIGN1ci5m
aXJzdCAoICJwYXJ0bmVySUQiICkgKXsKCSAgICAJCXBhcnRuZXJJRCA9IChTdHJpbmcpY3VyLmdl
dFZhbHVlKCk7IAoJICAgIAl9CgkgICAgCWlmICggY3VyLmZpcnN0ICggInVzZXJJRCIgKSApewoJ
ICAgIAkJdXNlcklEID0gKFN0cmluZyljdXIuZ2V0VmFsdWUoKTsgCgkgICAgCX0KCSAgICAJaWYg
KCBjdXIuZmlyc3QgKCAicGFnZU51bSIgKSApewoJICAgIAkJdHJ5ewoJICAgIAkJCXBhZ2VOdW1i
ZXIgPSBJbnRlZ2VyLnBhcnNlSW50KChTdHJpbmcpY3VyLmdldFZhbHVlKCkpOyAKCSAgICAJCX0K
CSAgICAJCWNhdGNoKE51bWJlckZvcm1hdEV4Y2VwdGlvbiBlKQoJICAgIAkJewoJICAgIAkJCXBh
Z2VOdW1iZXIgPSAtMTsKCSAgICAJCX0KCSAgICAJfQoJICAgIAlpZiAoIGN1ci5maXJzdCAoICJw
YWdlU2l6ZSIgKSApewoJICAgIAkJdHJ5ewoJICAgIAkJCXBhZ2VTaXplID0gSW50ZWdlci5wYXJz
ZUludCgoU3RyaW5nKWN1ci5nZXRWYWx1ZSgpKTsgCgkgICAgCQl9CgkgICAgCQljYXRjaChOdW1i
ZXJGb3JtYXRFeGNlcHRpb24gZSkKCSAgICAJCXsKCSAgICAJCQlwYWdlU2l6ZSA9IC0xOwoJICAg
IAkJfQoJICAgIAl9CgkgICAgCWlmICggY3VyLmZpcnN0ICggInBhZ2VEZXB0aCIgKSApewoJICAg
IAkJdHJ5ewoJICAgIAkJCXBhZ2VEZXB0aCA9IEludGVnZXIucGFyc2VJbnQoKFN0cmluZyljdXIu
Z2V0VmFsdWUoKSk7IAoJICAgIAkJfQoJICAgIAkJY2F0Y2goTnVtYmVyRm9ybWF0RXhjZXB0aW9u
IGUpCgkgICAgCQl7CgkgICAgCQkJcGFnZURlcHRoID0gLTE7CgkgICAgCQl9CgkgICAgCX0KCSAg
ICAJaWYgKCBjdXIuZmlyc3QgKCAidmZzTmFtZSIgKSApewoJICAgIAkJdmZzTmFtZSA9IChTdHJp
bmcpIGN1ci5nZXRWYWx1ZSgpOyAKCSAgICAJfQoJICAgIAlpZiAoIHVzZXJJRCAhPSBudWxsICYm
IHVzZXJJRC50cmltKCkuZXF1YWxzKCIiKSApIHVzZXJJRCA9IG51bGw7CgkgICAgCQogCSAgICAJ
UGFydG5lclZmc0xpc3RJbmZvIHZmc0luZm8gPSBVc2VyTWFuYWdlclByb3h5Lmxpc3RQYXJ0bmVy
VkZTKHBhcnRuZXJJRCwgdXNlcklELCB2ZnNOYW1lLCBwYWdlTnVtYmVyLCBwYWdlU2l6ZSwgcGFn
ZURlcHRoLCBmYWxzZSk7CgkgICAgCUhhc2hNYXAgPFN0cmluZywgTGlzdFZGU09iamVjdFtdPiB2
ZnNMaXN0ID0gdmZzSW5mby5nZXRQYXJ0bmVyVmZzTWFwKCk7CiAgICAgICAgCWlmKHZmc0xpc3Qg
IT0gbnVsbCl7CiAgICAgICAgCQlTb3J0ZWRJRGF0YUxpc3Qgc29ydCA9IG5ldyBTb3J0ZWRJRGF0
YUxpc3QoInBhcnRuZXJOYW1lIik7IAogICAgICAgIAkJU2V0PFN0cmluZz4ga2V5cyA9IHZmc0xp
c3Qua2V5U2V0KCk7CiAgICAgICAgCQlJdGVyYXRvcjxTdHJpbmc+IGl0ciA9IGtleXMuaXRlcmF0
b3IoKTsKICAgICAgICAJCXdoaWxlKGl0ci5oYXNOZXh0KCkpewogICAgICAgIAkJCVN0cmluZyBr
ZXkgPSBpdHIubmV4dCgpOwogICAgICAgIAkJCUxpc3RWRlNPYmplY3RbXSBsaXN0ID0gdmZzTGlz
dC5nZXQoa2V5KTsKICAgICAgICAJCQlJRGF0YSBpZGF0YSA9IElEYXRhRmFjdG9yeS5jcmVhdGUo
KTsKICAgICAgICAJCQlWYWx1ZXNFbXVsYXRvci5wdXQoaWRhdGEsICJwYXJ0bmVySUQiLCBrZXkp
OwogICAgICAgIAkJCWlmKGxpc3QgIT0gbnVsbCAmJiBsaXN0Lmxlbmd0aCA+IDApewogICAgICAg
IAkJCQlTdHJpbmcgbmFtZSA9IGxpc3RbMF0uZ2V0UGFydG5lck5hbWUoKTsKICAgICAgICAJCQkJ
aWYobmFtZSAhPSBudWxsICYmICFuYW1lLmVxdWFsc0lnbm9yZUNhc2UoIk5vIFBhcnRuZXIiKSkK
ICAgICAgICAJCQkJCVZhbHVlc0VtdWxhdG9yLnB1dChpZGF0YSwgInBhcnRuZXJOYW1lIiwgQmFz
ZTY0LmVuY29kZVVURjgobmFtZSkpOwogICAgICAgIAkJCQllbHNlCiAgICAgICAgCQkJCQlWYWx1
ZXNFbXVsYXRvci5wdXQoaWRhdGEsICJwYXJ0bmVyTmFtZSIsIEJhc2U2NC5lbmNvZGVVVEY4KCJO
byBQYXJ0bmVyIikpOwogICAgICAgIAkJCX0KICAgICAgICAJCQlWYWx1ZXNFbXVsYXRvci5wdXQo
aWRhdGEsICJ2ZnNMaXN0U3RyIiwgQmFzZTY0VXRpbC5lbmNvZGVPYmplY3QobGlzdCkpOwogICAg
ICAgIAkJCXNvcnQuYWRkRWxlbWVudChpZGF0YSk7CiAgICAgICAgCQl9CiAgICAgICAgCQlJRGF0
YVtdIHNvcnRlZFZGU0xpc3QgPSBzb3J0LmdldFNvcnRlZExpc3QoKTsKICAgICAgICAJCVZhbHVl
c0VtdWxhdG9yLnB1dChvdXRwdXQsICJ2ZnNQYXJ0bmVyTGlzdCIsIHNvcnRlZFZGU0xpc3QpOyAK
ICAgICAgICAJCVZhbHVlc0VtdWxhdG9yLnB1dChvdXRwdXQsICJ0b3RhbFBhZ2VzIiwgU3RyaW5n
LnZhbHVlT2YodmZzSW5mby5nZXRUb3RhbE51bU9mcGFnZXMoKSkpOwogICAgICAgIAkJCiAgICAg
ICAgCX0JICAKICAgICAgICAJCgkgICAgfWNhdGNoIChUaHJvd2FibGUgdCl7CgkgICAgCXN2Y1Jl
c3AgPSBQb3J0YWxVdGlscy5jYXRjaEVycm9yKHQsIHN2Y05hbWUsIFNoYXJlZENvbnN0YW50cy5F
UlJPUiAsc3ZjUmVzcCk7CgkgICAgfWZpbmFsbHkgewoJICAgIAlpZiAoY3VyICE9IG51bGwpewoJ
ICAgIAkJY3VyLmRlc3Ryb3koKTsKCSAgICAJfQoJICAgIAlWYWx1ZXNFbXVsYXRvci5wdXQob3V0
cHV0LCAic3ZjUmVzcG9uc2UiLCBzdmNSZXNwKTsKICAgICAgICAJVmFsdWVzRW11bGF0b3IucHV0
KHBpcGVsaW5lLCAib3V0cHV0Iiwgb3V0cHV0KTsJICAgICAgICAJCgkgICAgfQoJCQo=</value>
</Values>
