<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">list</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:optional type {"Keystore","Truststore","PGP_Public","PGP_Private","SSH_PrivateKey","SSH_PublicKey"}</value>
    <value>[o] record:0:required certificates</value>
    <value>[o] - recref:0:required mftCertificate wm.mft.assets.rec.server:certificateAsset</value>
    <value>[o] - field:0:optional success</value>
    <value>[o] - field:0:optional message</value>
    <value>[o] - field:0:optional totalRows</value>
  </array>
  <value name="subtype">unknown</value>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">CklEYXRhQ3Vyc29yIGN1ciA9IG51bGw7ClN0cmluZyBtZXNzYWdlID0gTUZUUmVzb3VyY2VzLmdl
dE1lc3NhZ2UoIjEwMTMiKTsKYm9vbGVhbiBzdWNjZXNzID0gdHJ1ZTsKSURhdGFbXSBtZnRLZXlB
cnJheSA9IG51bGwgOwp0cnkgewoJU3RyaW5nIHR5cGUgPSAoU3RyaW5nKSBWYWx1ZXNFbXVsYXRv
ci5nZXQocGlwZWxpbmUsICJ0eXBlIik7CglpZih0eXBlICE9IG51bGwgJiYgIXR5cGUuaXNFbXB0
eSgpKXsKCQl0eXBlID0gInR5cGU6IiArIHR5cGU7Cgl9CglTdHJpbmcgcGcgPSBWYWx1ZXNFbXVs
YXRvci5nZXROb25FbXB0eVN0cmluZyhwaXBlbGluZSwgInBhZ2VOdW0iKTsKCWlmKHBnID09IG51
bGwgfHwgcGcuaXNFbXB0eSgpKSBwZyA9ICIxIjsKCglTdHJpbmcgcHMgPSBWYWx1ZXNFbXVsYXRv
ci5nZXROb25FbXB0eVN0cmluZyhwaXBlbGluZSwgInBhZ2VTaXplIik7CglpZihwcyA9PSBudWxs
IHx8IHBzLmlzRW1wdHkoKSkgcHMgPSBTdHJpbmcudmFsdWVPZihJbnRlZ2VyLk1BWF9WQUxVRSk7
CgoJU3RyaW5nIHNvcnRDb2x1bW4gPSBWYWx1ZXNFbXVsYXRvci5nZXROb25FbXB0eVN0cmluZyhw
aXBlbGluZSwgInNvcnRDb2x1bW4iKTsKCWlmKHNvcnRDb2x1bW4gPT0gbnVsbCkgc29ydENvbHVt
biA9ICIiOwoKCVN0cmluZyBzb3J0T3JkZXIgPSBWYWx1ZXNFbXVsYXRvci5nZXROb25FbXB0eVN0
cmluZyhwaXBlbGluZSwgInNvcnRPcmRlciIpOwoJaWYoc29ydE9yZGVyID09IG51bGwpIHNvcnRP
cmRlciA9ICIiOwoKCWludCBwYWdlTnVtID0gSW50ZWdlci5wYXJzZUludChwZyk7CglpbnQgcGFn
ZVNpemUgPSBJbnRlZ2VyLnBhcnNlSW50KHBzKTsKCglNRlRDZXJ0aWZpY2F0ZUxpc3RSZXNwb25z
ZSBtZnRDZXJ0aWZpY2F0ZUxpc3RSZXNwb25zZSA9IENvbW1vblByb3h5Lmxpc3RNRlRLZXlzSW5Q
YWdlcyhwYWdlTnVtLCBwYWdlU2l6ZSwgdHlwZSwgc29ydENvbHVtbiwgc29ydE9yZGVyLCBmYWxz
ZSk7CglMaXN0PE1GVENlcnRpZmljYXRlPiBtZnRDZXJ0aWZpY2F0ZUxpc3QgPSBtZnRDZXJ0aWZp
Y2F0ZUxpc3RSZXNwb25zZS5nZXRNZnRDZXJ0aWZpY2F0ZUxpc3QoKTsKCWlmIChtZnRDZXJ0aWZp
Y2F0ZUxpc3QgIT0gbnVsbCkgewoJCWJvb2xlYW4gaXNDbG91ZE1vZGUgPSBTZXJ2ZXJBZG1pblBy
b3h5LmlzQ2xvdWRNb2RlKCk7CgkJaWYgKGlzQ2xvdWRNb2RlKSB7CgkJCW1mdENlcnRpZmljYXRl
TGlzdCA9IG1mdENlcnRpZmljYXRlTGlzdC5zdHJlYW0oKS5maWx0ZXIoeCAtPiB7CgkJCQlpZih4
LmdldE1ldGFkYXRhKCkgPT0gbnVsbCkgcmV0dXJuIHRydWU7CgkJCQlib29sZWFuIGlzRGVmYXVs
dCA9IEJvb2xlYW4ucGFyc2VCb29sZWFuKHguZ2V0TWV0YWRhdGEoKS5nZXRPckRlZmF1bHQoImRl
ZmF1bHQiLCAiZmFsc2UiKSk7CgkJCQlyZXR1cm4gIWlzRGVmYXVsdDsKCQkJfSkuY29sbGVjdChD
b2xsZWN0b3JzLnRvTGlzdCgpKTsKCQl9CgkJaW50IGkgPSAwOwoJCW1mdEtleUFycmF5ID0gbmV3
IElEYXRhW21mdENlcnRpZmljYXRlTGlzdC5zaXplKCldOwoJCWZvciAoTUZUQ2VydGlmaWNhdGUg
bWZ0a2V5IDogbWZ0Q2VydGlmaWNhdGVMaXN0KSB7CgkJCW1mdEtleUFycmF5W2krK10gPSBBc3Nl
dFV0aWxzLmdldElEYXRhRnJvbU1GVEtleShtZnRrZXkpOwoJCX0KCX0KCVZhbHVlc0VtdWxhdG9y
LnB1dChwaXBlbGluZSwgImNlcnRpZmljYXRlcyIsIG1mdEtleUFycmF5KTsKCVZhbHVlc0VtdWxh
dG9yLnB1dChwaXBlbGluZSwgInRvdGFsUm93cyIsIG1mdENlcnRpZmljYXRlTGlzdFJlc3BvbnNl
LmdldFRvdGFsUmVjb3JkcygpKTsKfSBjYXRjaCAoVGhyb3dhYmxlIHQpIHsKCXN1Y2Nlc3MgPSBm
YWxzZTsKCW1lc3NhZ2UgPSB0LmdldExvY2FsaXplZE1lc3NhZ2UoKTsKfSBmaW5hbGx5IHsKCWlm
IChjdXIgIT0gbnVsbCkgewoJCWN1ci5kZXN0cm95KCk7Cgl9CglWYWx1ZXNFbXVsYXRvci5wdXQo
cGlwZWxpbmUsICJzdWNjZXNzIiwgU3RyaW5nLnZhbHVlT2Yoc3VjY2VzcykpOwoJVmFsdWVzRW11
bGF0b3IucHV0KHBpcGVsaW5lLCAibWVzc2FnZSIsIG1lc3NhZ2UpOwp9Cg==</value>
</Values>
