<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">fileSystemBrowse</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:optional dir</value>
    <value>[i] field:0:optional filesIncluded</value>
    <value>[o] record:0:required output</value>
    <value>[o] - record:1:required files</value>
    <value>[o] -- field:0:required name</value>
    <value>[o] -- field:0:required path</value>
    <value>[o] -- field:0:required type</value>
  </array>
  <value name="subtype">unknown</value>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">CklEYXRhQ3Vyc29yIGN1ciA9IG51bGw7ClN0cmluZyBkaXIgPSBudWxsOwpTdHJpbmcgZmlsZXNJ
bmNsdWRlZCA9IG51bGw7CklEYXRhIG91dHB1dCA9IElEYXRhRmFjdG9yeS5jcmVhdGUoKTsKVmVj
dG9yIGxpc3RpbmcgPSBudWxsOwpTb3J0ZWRJRGF0YUxpc3QgbGlzdERpciA9IG5ldyBTb3J0ZWRJ
RGF0YUxpc3QoIm5hbWUiKTsKU29ydGVkSURhdGFMaXN0IGxpc3RGaWxlID0gbmV3IFNvcnRlZElE
YXRhTGlzdCgibmFtZSIpOwp0cnkgewoJUkJBUHJveHkudmFsaWRhdGVTZXNzaW9uKFJCQVVpSGFu
ZGxlLlZGU19BQ0NFU1NfTE9DQUxfRklMRSk7CgljdXIgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsK
CWlmIChjdXIuZmlyc3QoImRpciIpKSB7CgkJZGlyID0gKFN0cmluZykgY3VyLmdldFZhbHVlKCk7
Cgl9CglpZiAoY3VyLmZpcnN0KCJmaWxlc0luY2x1ZGVkIikpIHsKCQlmaWxlc0luY2x1ZGVkID0g
KFN0cmluZykgY3VyLmdldFZhbHVlKCk7Cgl9CglQcm9wZXJ0aWVzIHByb3BzID0gVXNlck1hbmFn
ZXJQcm94eS5nZXRMaXN0aW5nSW5mbyhkaXIpOwoJaWYgKHByb3BzICE9IG51bGwpIHsKCQlsaXN0
aW5nID0gKFZlY3RvcikgcHJvcHMuZ2V0KCJsaXN0aW5nIik7CgkJaWYgKGxpc3RpbmcgIT0gbnVs
bCkgewoJCQlJdGVyYXRvciBpdHIgPSBsaXN0aW5nLml0ZXJhdG9yKCk7CgkJCXdoaWxlIChpdHIu
aGFzTmV4dCgpKSB7CgkJCQlQcm9wZXJ0aWVzIHByb3AgPSAoUHJvcGVydGllcykgaXRyLm5leHQo
KTsKCQkJCWlmIChwcm9wICE9IG51bGwpIHsKCQkJCQlJRGF0YSBpZGF0YSA9IElEYXRhRmFjdG9y
eS5jcmVhdGUoKTsKCQkJCQlWYWx1ZXNFbXVsYXRvci5wdXQoaWRhdGEsICJuYW1lIiwgcHJvcC5n
ZXQoIm5hbWUiKSk7CgkJCQkJVmFsdWVzRW11bGF0b3IucHV0KGlkYXRhLCAicGF0aCIsIHByb3Au
Z2V0KCJocmVmX3BhdGgiKSk7CgkJCQkJU3RyaW5nIHR5cGUgPSAoU3RyaW5nKSBwcm9wLmdldCgi
dHlwZSIpOwoJCQkJCVZhbHVlc0VtdWxhdG9yLnB1dChpZGF0YSwgInR5cGUiLCB0eXBlKTsKCQkJ
CQlpZiAodHlwZSAhPSBudWxsICYmIHR5cGUuZXF1YWxzSWdub3JlQ2FzZSgiRElSIikpCgkJCQkJ
CWxpc3REaXIuYWRkRWxlbWVudChpZGF0YSk7CgkJCQkJZWxzZSB7CgkJCQkJCWlmIChmaWxlc0lu
Y2x1ZGVkICE9IG51bGwgJiYgZmlsZXNJbmNsdWRlZC5lcXVhbHNJZ25vcmVDYXNlKCJ0cnVlIikp
CgkJCQkJCQlsaXN0RmlsZS5hZGRFbGVtZW50KGlkYXRhKTsKCQkJCQl9CgkJCQl9CgkJCX0KCQl9
Cgl9CglJRGF0YVtdIHNvcnRlZERpckxpc3QgPSBsaXN0RGlyLmdldFNvcnRlZExpc3QoKTsKCUlE
YXRhW10gc29ydGVkRmlsZUxpc3QgPSBsaXN0RmlsZS5nZXRTb3J0ZWRMaXN0KCk7CglJRGF0YVtd
IGZpbmFsTGlzdCA9IG51bGw7CglpZiAoc29ydGVkRGlyTGlzdCAhPSBudWxsICYmIHNvcnRlZEZp
bGVMaXN0ID09IG51bGwpIHsKCQlmaW5hbExpc3QgPSBzb3J0ZWREaXJMaXN0OwoJfSBlbHNlIGlm
IChzb3J0ZWRGaWxlTGlzdCAhPSBudWxsICYmIHNvcnRlZERpckxpc3QgPT0gbnVsbCkgewoJCWZp
bmFsTGlzdCA9IHNvcnRlZEZpbGVMaXN0OwoJfSBlbHNlIGlmIChzb3J0ZWRGaWxlTGlzdCAhPSBu
dWxsICYmIHNvcnRlZERpckxpc3QgIT0gbnVsbCkgewoJCWludCBsZW5ndGggPSBzb3J0ZWRGaWxl
TGlzdC5sZW5ndGggKyBzb3J0ZWREaXJMaXN0Lmxlbmd0aDsKCQlmaW5hbExpc3QgPSBuZXcgSURh
dGFbbGVuZ3RoXTsKCQlpbnQgayA9IDA7CgkJZm9yIChpbnQgaSA9IDA7IGkgPCBsZW5ndGg7IGkr
KykgewoJCQlpZiAoaSA8IHNvcnRlZERpckxpc3QubGVuZ3RoKQoJCQkJZmluYWxMaXN0W2ldID0g
c29ydGVkRGlyTGlzdFtpXTsKCQkJZWxzZSB7CgkJCQlmaW5hbExpc3RbaV0gPSBzb3J0ZWRGaWxl
TGlzdFtrKytdOwoJCQl9CgkJfQoJfQoJVmFsdWVzRW11bGF0b3IucHV0KG91dHB1dCwgImZpbGVz
IiwgZmluYWxMaXN0KTsKfSBjYXRjaCAoVGhyb3dhYmxlIHQpIHsKCVZhbHVlc0VtdWxhdG9yLnB1
dChwaXBlbGluZSwgInN1Y2Nlc3MiLCBmYWxzZSk7CglWYWx1ZXNFbXVsYXRvci5wdXQocGlwZWxp
bmUsICJtZXNzYWdlIiwgdC5nZXRMb2NhbGl6ZWRNZXNzYWdlKCkpOwp9IGZpbmFsbHkgewoJaWYg
KGN1ciAhPSBudWxsKSB7CgkJY3VyLmRlc3Ryb3koKTsKCX0KCVZhbHVlc0VtdWxhdG9yLnB1dChw
aXBlbGluZSwgIm91dHB1dCIsIG91dHB1dCk7Cn0KCg==</value>
</Values>
