<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">add</value>
  <array name="sig" type="value" depth="1">
    <value>[i] recref:0:required eventInfo wm.mft.assets.rec.event:PostProcessEvent</value>
    <value>[o] field:0:required success</value>
    <value>[o] field:0:optional eventId</value>
    <value>[o] field:0:required message</value>
    <value>[o] field:1:required validationErrors</value>
  </array>
  <value name="subtype">unknown</value>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">CQlTdHJpbmcgbWVzc2FnZSA9IE1GVFJlc291cmNlcy5nZXRNZXNzYWdlKCIxMDEzIik7CgkJSURh
dGFDdXJzb3IgY3VyID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7CgkJU3RyaW5nIGV2ZW50SWQgPSAi
IjsKCQlJRGF0YSBldmVudFBpcGUgPSAoSURhdGEpIFZhbHVlc0VtdWxhdG9yLmdldChwaXBlbGlu
ZSwgImV2ZW50SW5mbyIpOwoJCWJvb2xlYW4gdmFsaWRhdGVJbnB1dCA9IHRydWU7CgkJaWYgKCAi
ZmFsc2UiLmVxdWFsc0lnbm9yZUNhc2UoVmFsdWVzRW11bGF0b3IuZ2V0U3RyaW5nKHBpcGVsaW5l
LCAidmFsaWRhdGVJbnB1dCIpKSApIHsKCQkJdmFsaWRhdGVJbnB1dCA9IGZhbHNlOwoJCX0KCQlQ
b3N0UHJvY2Vzc0V2ZW50IGV2ZW50ID0gbnVsbDsKCQkKCQlib29sZWFuIHN1Y2Nlc3MgPSBmYWxz
ZTsKCQlTdHJpbmdbXSBtZXNzYWdlQXJyYXkgPSBudWxsOwoJCXRyeXsKCQkJaWYgKCBldmVudFBp
cGUgPT0gbnVsbCApCgkJCQl0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbihNRlRSZXNvdXJjZXMu
Z2V0TWVzc2FnZSgiMTAwMSIsICJldmVudEluZm8iKSk7CgkJCWV2ZW50ID0gQXNzZXRVdGlscy5n
ZXRFdmVudEZyb21JRGF0YShldmVudFBpcGUpOwoJCQlpZiAoIGV2ZW50LmdldE5hbWUoKSAhPSBu
dWxsICYmIGV2ZW50LmdldE5hbWUoKS5sZW5ndGgoKSA+IDI1NSApIHsKCQkJCXRocm93IG5ldyBT
ZXJ2aWNlRXhjZXB0aW9uKE1GVFJlc291cmNlcy5nZXRNZXNzYWdlKCI4MTA1IikpOwoJCQl9CgkJ
CWlmICggZXZlbnQuZ2V0RGVzY3JpcHRpb24oKSAhPSBudWxsICYmIGV2ZW50LmdldERlc2NyaXB0
aW9uKCkubGVuZ3RoKCkgPiAyNTYgKSB7CgkJCQl0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbihN
RlRSZXNvdXJjZXMuZ2V0TWVzc2FnZSgiODEwNCIpKTsKCQkJfQoJCQlldmVudElkID0gRXZlbnRz
UHJveHkuYWRkUG9zdFByb2Nlc3NpbmdFdmVudChldmVudCwgbnVsbCwgdmFsaWRhdGVJbnB1dCk7
CgkJCXN1Y2Nlc3MgPSB0cnVlOwoJCX1jYXRjaCAoVGhyb3dhYmxlIHQpewoJICAgIAltZXNzYWdl
ID0gdC5nZXRMb2NhbGl6ZWRNZXNzYWdlKCk7CgkgICAgCWlmICggdCBpbnN0YW5jZW9mIE1GVFNl
cnZpY2VFeGNlcHRpb24gKSB7CgkgICAgCQlMaXN0PFN0cmluZz4gbWVzc2FnZUxpc3QgPSAoKE1G
VFNlcnZpY2VFeGNlcHRpb24pIHQpLmdldEVycm9yTWVzc2FnZUxpc3QoKTsKCSAgICAJCWlmICgg
bWVzc2FnZUxpc3QgIT0gbnVsbCApIHsKCSAgICAJCQltZXNzYWdlQXJyYXkgPSBuZXcgU3RyaW5n
W21lc3NhZ2VMaXN0LnNpemUoKV07IAoJICAgIAkJCW1lc3NhZ2VMaXN0LnRvQXJyYXkobWVzc2Fn
ZUFycmF5KTsKCSAgICAJCX0KCQkJfQoJICAgIH1maW5hbGx5IHsKCSAgICAJVmFsdWVzRW11bGF0
b3IucHV0KHBpcGVsaW5lLCAic3VjY2VzcyIsIFN0cmluZy52YWx1ZU9mKHN1Y2Nlc3MpKTsKCSAg
ICAJVmFsdWVzRW11bGF0b3IucHV0KHBpcGVsaW5lLCJldmVudElkIiwgZXZlbnRJZCk7CgkgICAg
CVZhbHVlc0VtdWxhdG9yLnB1dChwaXBlbGluZSwibWVzc2FnZSIsbWVzc2FnZSk7CgkJCWlmICgg
bWVzc2FnZUFycmF5ICE9IG51bGwgKQoJCQkJVmFsdWVzRW11bGF0b3IucHV0KHBpcGVsaW5lLCAi
dmFsaWRhdGlvbkVycm9ycyIsbWVzc2FnZUFycmF5KTsKCQkJaWYgKGN1ciAhPSBudWxsKXsKCSAg
ICAJCWN1ci5kZXN0cm95KCk7CgkgICAgCX0KCSAgICB9Cg==</value>
</Values>
