<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">deliverDeployment</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:required name</value>
    <value>[i] field:0:required description</value>
    <value>[i] field:0:optional sourceEnvironment</value>
    <value>[i] field:0:optional sourceUser</value>
    <value>[i] field:0:optional targetEnvironment</value>
    <value>[i] field:0:required base64EncodedExportData</value>
    <value>[o] field:0:required success</value>
    <value>[o] field:0:required deploymentId</value>
    <value>[o] field:0:required message</value>
  </array>
  <value name="subtype">unknown</value>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">ClN0cmluZyBtZXNzYWdlID0gTUZUUmVzb3VyY2VzLmdldE1lc3NhZ2UoIjEwMTMiKTsKSURhdGFD
dXJzb3IgY3VyID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7CgpTdHJpbmcgbmFtZSA9IG51bGw7ClN0
cmluZyBkZXNjcmlwdGlvbiA9IG51bGw7ClN0cmluZyBzb3VyY2VFbnZpcm9ubWVudCA9IG51bGw7
ClN0cmluZyB0YXJnZXRFbnZpcm9ubWVudCA9IG51bGw7ClN0cmluZyBkZXBsb3ltZW50SWQgPSBu
dWxsOwpib29sZWFuIHN1Y2Nlc3MgPSBmYWxzZTsKU3RyaW5nIGJhc2U2NEVuY29kZWRFeHBvcnRE
YXRhID0gIiI7ClN0cmluZyBzb3VyY2VVc2VyID0gIiI7CnRyeSB7CgogICAgLy8gUkJBUHJveHku
dmFsaWRhdGVTZXNzaW9uKFJCQVVpSGFuZGxlLkFTU0VUX0RFUExPWU1FTlRfVklFVyk7CiAgICBS
QkFQcm94eS52YWxpZGF0ZVNlc3Npb24oUkJBVWlIYW5kbGUuQVNTRVRfREVQTE9ZTUVOVF9WSUVX
KTsKCiAgICBpZiAoY3VyLmZpcnN0KCJuYW1lIikpIHsKICAgICAgICBuYW1lID0gKFN0cmluZykg
Y3VyLmdldFZhbHVlKCk7CiAgICB9CgogICAgaWYgKGN1ci5maXJzdCgiZGVzY3JpcHRpb24iKSkg
ewogICAgICAgIGRlc2NyaXB0aW9uID0gKFN0cmluZykgY3VyLmdldFZhbHVlKCk7CiAgICB9Cgog
ICAgaWYgKGN1ci5maXJzdCgic291cmNlRW52aXJvbm1lbnQiKSkgewogICAgICAgIHNvdXJjZUVu
dmlyb25tZW50ID0gKFN0cmluZykgY3VyLmdldFZhbHVlKCk7CiAgICB9CgogICAgaWYgKGN1ci5m
aXJzdCgic291cmNlVXNlciIpKSB7CiAgICAgICAgc291cmNlVXNlciA9IChTdHJpbmcpIGN1ci5n
ZXRWYWx1ZSgpOwogICAgfQoKICAgIGlmIChjdXIuZmlyc3QoInRhcmdldEVudmlyb25tZW50Iikp
IHsKICAgICAgICB0YXJnZXRFbnZpcm9ubWVudCA9IChTdHJpbmcpIGN1ci5nZXRWYWx1ZSgpOwog
ICAgfQoKICAgIGlmIChjdXIuZmlyc3QoImJhc2U2NEVuY29kZWRFeHBvcnREYXRhIikpIHsKICAg
ICAgICBiYXNlNjRFbmNvZGVkRXhwb3J0RGF0YSA9IChTdHJpbmcpIGN1ci5nZXRWYWx1ZSgpOwog
ICAgfQoKICAgIFN0cmluZyBhdXRob3Jpc2VkVXNlciA9IChTdHJpbmcpIFZhbHVlc0VtdWxhdG9y
LmdldChwaXBlbGluZSwgImF1dGhvcmlzZWRVc2VyIik7CiAgICBTdHJpbmcgYXV0aG9yaXNlZENy
ZWRzID0gKFN0cmluZykgVmFsdWVzRW11bGF0b3IuZ2V0KHBpcGVsaW5lLCAiYXV0aG9yaXNlZENy
ZWRzIik7CgoKICAgIGlmIChTZXJ2ZXJBZG1pblByb3h5LnZhbGlkYXRlRGVwbG95bWVudFVzZXIo
YXV0aG9yaXNlZFVzZXIsIGF1dGhvcmlzZWRDcmVkcykpIHsKICAgICAgICBkZXBsb3ltZW50SWQg
PSBBc3NldE1hbmFnZXJQcm94eS5kZWxpdmVyRGVwbG95bWVudChuYW1lLCBkZXNjcmlwdGlvbiwg
c291cmNlRW52aXJvbm1lbnQsIHNvdXJjZVVzZXIsIHRhcmdldEVudmlyb25tZW50LCBhdXRob3Jp
c2VkVXNlciwgYmFzZTY0RW5jb2RlZEV4cG9ydERhdGEpOwogICAgfSBlbHNlIHsKICAgICAgICBt
ZXNzYWdlID0gQ29tbW9uUHJveHkuZ2V0TWVzc2FnZUZvclBhY2thZ2UoIjE1NzAiLCBhdXRob3Jp
c2VkVXNlcik7CiAgICB9CiAgICBzdWNjZXNzID0gbnVsbCAhPSBkZXBsb3ltZW50SWQgJiYgIWRl
cGxveW1lbnRJZC5pc0VtcHR5KCk7Cn0gY2F0Y2ggKFRocm93YWJsZSB0KSB7CiAgICBtZXNzYWdl
ID0gdC5nZXRNZXNzYWdlKCk7CiAgICBzdWNjZXNzID0gZmFsc2U7Cn0gZmluYWxseSB7CiAgICBW
YWx1ZXNFbXVsYXRvci5yZW1vdmUocGlwZWxpbmUsICJiYXNlNjRFbmNvZGVkRXhwb3J0RGF0YSIp
OwogICAgcGlwZWxpbmUuZ2V0Q3Vyc29yKCkuZGVzdHJveSgpOwogICAgVmFsdWVzRW11bGF0b3Iu
cHV0KHBpcGVsaW5lLCAic3VjY2VzcyIsIFN0cmluZy52YWx1ZU9mKHN1Y2Nlc3MpKTsKICAgIFZh
bHVlc0VtdWxhdG9yLnB1dChwaXBlbGluZSwgImRlcGxveW1lbnRJZCIsIG51bGw9PWRlcGxveW1l
bnRJZD8iIjpkZXBsb3ltZW50SWQpOwogICAgVmFsdWVzRW11bGF0b3IucHV0KHBpcGVsaW5lLCAi
bWVzc2FnZSIsIG1lc3NhZ2UpOwogICAgaWYgKGN1ciAhPSBudWxsKSB7CiAgICAgICAgY3VyLmRl
c3Ryb3koKTsKICAgIH0KfQo=</value>
</Values>
