<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">getDependencies</value>
  <array name="sig" type="value" depth="1">
    <value>[i] record:1:required assetList</value>
    <value>[i] - field:0:optional assetType {"portServer","serverInstance","serverPreference","user","template","postProcessEvent","monitorFolderAction","postProcessAction","VFS","MFTSettings","rba","actionTemplate"}</value>
    <value>[i] - field:1:required ids</value>
    <value>[i] - field:1:required names</value>
    <value>[o] field:0:required success</value>
    <value>[o] recref:1:optional dependencies wm.mft.assets.rec.management:dependencies</value>
  </array>
  <value name="subtype">unknown</value>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">U3RyaW5nIG1lc3NhZ2UgPSBNRlRSZXNvdXJjZXMuZ2V0TWVzc2FnZSgiMTAxMyIpOwpJRGF0YUN1
cnNvciBjdXIgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsKamF2YS51dGlsLkxpc3Q8QXNzZXRGaWx0
ZXI+IGZpbHRlckxpc3QgPSBudWxsOwpJRGF0YVtdIGRlcGVuZGVuY3lMaXN0ID0gbnVsbDsKSURh
dGFbXSBleHBvcnRGaWx0ZXIgPSBudWxsOwpib29sZWFuIHN1Y2Nlc3MgPSBmYWxzZTsKTWFwPFN0
cmluZywgTWFwPFN0cmluZywgT2JqZWN0Pj4gYXNzZXRzQ2FjaGUgPSBudWxsOwp0cnkgewoJUkJB
UHJveHkudmFsaWRhdGVTZXNzaW9uKFJCQVVpSGFuZGxlLkFTU0VUX0VYUE9SVF9WSUVXKTsKCVNl
dDxTdHJpbmc+IHJiYVBlcm1pdHRlZEFzc2V0VHlwZXMgPSBnZXRSQkFGaWx0ZXJMaXN0U3RyaW5n
cygpOwoKCVN0cmluZyByYW5kb21TdHIgPSBWYWx1ZXNFbXVsYXRvci5nZXRTdHJpbmcocGlwZWxp
bmUsICJyYW5kb21TdHIiKTsKCVN0cmluZyBjbGVhckNhY2hlID0gVmFsdWVzRW11bGF0b3IuZ2V0
U3RyaW5nKHBpcGVsaW5lLCAiY2xlYXJDYWNoZSIpIDsKCWlmICggInRydWUiLmVxdWFsc0lnbm9y
ZUNhc2UoY2xlYXJDYWNoZSkgKSB7CgkJLy93aGVuIGNsZWFyQ2FjaGUgaXMgdHJ1ZSwgVUkgaXMg
ZG9uZSB3aXRoIGFsbCB0aGUgY2FsbHMuIENsZWFyIHRoZSBjYWNoZSBhbmQgcmV0dXJuCgkJY2Fj
aGVNYXAucmVtb3ZlKHJhbmRvbVN0cik7Cgl9IGVsc2UgewoJCS8vQ2hlY2sgaWYgdGhlcmUgaXMg
YW55IGFzc2V0IGluIHRoZSBjYWNoZSB0aGF0IGlzIG9sZGVyIHRoYW4gNSBtaW5zLiBJZiBzbyBy
ZW1vdmUKCQlsb25nIGN1cnJlbnRNaWxsaXMgPSBTeXN0ZW0uY3VycmVudFRpbWVNaWxsaXMoKTsK
CQlTZXQ8U3RyaW5nPiBjYWNoZUtleXMgPSBjYWNoZU1hcC5rZXlTZXQoKTsKCQlpZiAoY2FjaGVL
ZXlzICE9IG51bGwpIHsKCQkJZm9yIChTdHJpbmcgbWlsbGlzIDogY2FjaGVLZXlzKSB7CgkJCQl0
cnkgewoJCQkJCWxvbmcga2V5SW5Mb25nID0gTG9uZy5wYXJzZUxvbmcobWlsbGlzKTsKCQkJCQlp
ZiAoKGN1cnJlbnRNaWxsaXMgLSBrZXlJbkxvbmcpID4gNTAwMCkgewoJCQkJCQljYWNoZU1hcC5y
ZW1vdmUobWlsbGlzKTsKCQkJCQl9CgkJCQl9IGNhdGNoIChFeGNlcHRpb24gZTEpIHsKCQkJCQkv
L3RoaXMgbWlnaHQgaGFwcGVuIGlmIHJhbmRvbVN0ciBpcyBub3QgcHJvdmlkZWQgb3Igbm90IGxv
bmcuIERvbnQgZG8gYW55dGhpbmcKCQkJCX0KCQkJfQoJCX0KCgoJCWlmIChjdXIuZmlyc3QoImFz
c2V0TGlzdCIpKSB7CgkJCWV4cG9ydEZpbHRlciA9IChJRGF0YVtdKSBjdXIuZ2V0VmFsdWUoKTsK
CQl9CgoJCWZpbHRlckxpc3QgPSBjcmVhdGVGaWx0ZXJMaXN0KGV4cG9ydEZpbHRlcik7CgoJCWlm
IChyYW5kb21TdHIgIT0gbnVsbCAmJiByYW5kb21TdHIudHJpbSgpLmxlbmd0aCgpID4gMCkgewoJ
CQlhc3NldHNDYWNoZSA9IGNhY2hlTWFwLmdldChyYW5kb21TdHIpOwoJCX0KCQlpZiAoYXNzZXRz
Q2FjaGUgPT0gbnVsbCkgewoJCQlhc3NldHNDYWNoZSA9IG5ldyBIYXNoTWFwPFN0cmluZywgTWFw
PFN0cmluZywgT2JqZWN0Pj4oKTsKCQkJaWYgKHJhbmRvbVN0ciAhPSBudWxsICYmIHJhbmRvbVN0
ci50cmltKCkubGVuZ3RoKCkgPiAwKSB7CgkJCQljYWNoZU1hcC5wdXQocmFuZG9tU3RyLCBhc3Nl
dHNDYWNoZSk7CgkJCX0KCQl9CgoJCUV4cG9ydERhdGEgZXhwb3J0RGF0YSA9IEFzc2V0TWFuYWdl
clByb3h5LmdldEV4cG9ydERhdGFXaXRoQXNzZXRSZWZlcmVuY2VzKGZpbHRlckxpc3QsIGFzc2V0
c0NhY2hlKTsKCQlkZXBlbmRlbmN5TGlzdCA9IEFzc2V0VXRpbHMuZ2V0RGVwZW5kZW5jeUxpc3RG
cm9tRXhwb3J0RGF0YShyYmFQZXJtaXR0ZWRBc3NldFR5cGVzLCBleHBvcnREYXRhKTsKCX0KCXN1
Y2Nlc3MgPSB0cnVlOwoJCn0gY2F0Y2ggKFRocm93YWJsZSB0KSB7CgltZXNzYWdlID0gdC5nZXRN
ZXNzYWdlKCk7Cn0gZmluYWxseSB7CglWYWx1ZXNFbXVsYXRvci5wdXQocGlwZWxpbmUsICJzdWNj
ZXNzIiwgU3RyaW5nLnZhbHVlT2Yoc3VjY2VzcykpOwoJVmFsdWVzRW11bGF0b3IucHV0KHBpcGVs
aW5lLCAiZGVwZW5kZW5jaWVzIiwgZGVwZW5kZW5jeUxpc3QpOwoJVmFsdWVzRW11bGF0b3IucHV0
KHBpcGVsaW5lLCAibWVzc2FnZSIsIG1lc3NhZ2UpOwoJaWYgKGN1ciAhPSBudWxsKSB7CgkJY3Vy
LmRlc3Ryb3koKTsKCX0KfQo=</value>
</Values>
