<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">listUserDetails</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:required pageNumber</value>
    <value>[i] field:0:required pageSize</value>
    <value>[i] field:0:required type</value>
    <value>[o] record:1:required userDetails</value>
    <value>[o] - field:0:required userName</value>
    <value>[o] - field:0:required firstName</value>
    <value>[o] - field:0:required lastName</value>
    <value>[o] - field:0:required emailAddress</value>
    <value>[o] - field:0:required directoryService</value>
    <value>[o] field:0:required totalUsers</value>
    <value>[o] field:0:required message</value>
    <value>[o] field:0:required success</value>
  </array>
  <value name="subtype">unknown</value>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">ClN0cmluZyBtZXNzYWdlID0gTUZUUmVzb3VyY2VzLmdldE1lc3NhZ2UoIjEwMTMiKTsKYm9vbGVh
biBzdWNjZXNzID0gdHJ1ZTsKaW50IHRvdGFsVXNlcnMgPSAwOwpMaXN0PElEYXRhPiBpZGF0YUxp
c3QgPSBuZXcgQXJyYXlMaXN0PElEYXRhPigpOwp0cnkgewoJaW50IHBhZ2VOdW1iZXIgPSBWYWx1
ZXNFbXVsYXRvci5nZXRJbnQocGlwZWxpbmUsICJwYWdlTnVtYmVyIik7CglpbnQgcGFnZVNpemUg
PSBWYWx1ZXNFbXVsYXRvci5nZXRJbnQocGlwZWxpbmUsICJwYWdlU2l6ZSIpOwoJU3RyaW5nIHR5
cGUgPSBWYWx1ZXNFbXVsYXRvci5nZXRTdHJpbmcocGlwZWxpbmUsICJ0eXBlIik7CglpZiAoVXNl
cklkZW50aXR5LlVTRVIuZXF1YWxzKHR5cGUpKQoJCVJCQVByb3h5LnZhbGlkYXRlU2Vzc2lvbihS
QkFVaUhhbmRsZS5VU0VSX1ZJRVcpOwoJZWxzZSBpZiAoVXNlcklkZW50aXR5LlJPTEUuZXF1YWxz
KHR5cGUpKQoJCVJCQVByb3h5LnZhbGlkYXRlU2Vzc2lvbihSQkFVaUhhbmRsZS5ST0xFX1ZJRVcp
OwoJZWxzZQoJCVJCQVByb3h5LnZhbGlkYXRlU2Vzc2lvbihSQkFVaUhhbmRsZS5HUk9VUF9WSUVX
KTsKCglVc2VySWRlbnRpdHkgc2VhcmNoQ3JpdGVyaWEgPSBnZXRTZWFyY2hDcml0ZXJpYShwaXBl
bGluZSwgdHlwZSk7Cgl0b3RhbFVzZXJzID0gVXNlck1hbmFnZXJQcm94eS5nZXRDb3VudEZvck1G
VFVzZXJFbnRpdGllcyh0eXBlKTsKCUxpc3Q8VXNlcklkZW50aXR5PiB1c2VySWRlbnRpdGllcyA9
IFVzZXJNYW5hZ2VyUHJveHkubGlzdFVzZXJzKHBhZ2VOdW1iZXIsIHBhZ2VTaXplLCB0eXBlLCBz
ZWFyY2hDcml0ZXJpYSwKCQkJdHJ1ZSk7CglpZiAodXNlcklkZW50aXRpZXMgIT0gbnVsbCkgewoJ
CWlmIChTeXN0ZW0uZ2V0UHJvcGVydHkoIm1mdC51c2VyLmxpc3Quc2hvdy51c2VyLmRldGFpbHMi
LCAidHJ1ZSIpLmVxdWFsc0lnbm9yZUNhc2UoImZhbHNlIikpIHsKCQkJZm9yIChVc2VySWRlbnRp
dHkgdUkgOiB1c2VySWRlbnRpdGllcykgewoJCQkJaWRhdGFMaXN0LmFkZCh1c2VySWRlbnRpdHlU
b0lEYXRhKHVJLCB0eXBlKSk7CgkJCX0KCQl9IGVsc2UgewoJCQlmb3IgKFVzZXJJZGVudGl0eSB1
SSA6IHVzZXJJZGVudGl0aWVzKSB7CgkJCQl0cnl7CgkJCQkJaWYgKHVJLmdldFVzZXJUeXBlKCku
ZXF1YWxzKCJVIikpIHsKCQkJCQkJaWRhdGFMaXN0LmFkZChBc3NldFV0aWxzLmdldElEYXRhRnJv
bVByaW5jaXBhbE1vZGVsKFVzZXJNYW5hZ2VyUHJveHkudmlld1VzZXIodUkuZ2V0VXNlcklkKCks
IG51bGwsIHVJLmdldFVzZXJUeXBlKCksIHRydWUpKSk7CgkJCQkJfSBlbHNlIGlmICh1SS5nZXRV
c2VyVHlwZSgpLmVxdWFscygiRyIpKSB7CgkJCQkJCWlkYXRhTGlzdC5hZGQoQXNzZXRVdGlscy5n
ZXRJRGF0YUdyb3VwRnJvbVByaW5jaXBhbE1vZGVsKFVzZXJNYW5hZ2VyUHJveHkudmlld1VzZXIo
dUkuZ2V0VXNlcklkKCksIG51bGwsIHVJLmdldFVzZXJUeXBlKCksIHRydWUpKSk7CgkJCQkJfSBl
bHNlIGlmICh1SS5nZXRVc2VyVHlwZSgpLmVxdWFscygiUiIpKSB7CgkJCQkJCWlkYXRhTGlzdC5h
ZGQoZ2V0RGV0YWlsc0Zyb21JRGlyZWN0b3J5KHVJLmdldFVzZXJJZCgpLCBVSVV0aWxzLmxvb2t1
cEVudGl0eUJ5TmFtZSh1SS5nZXRVc2VySWQoKSwgZ2V0VHlwZSh0eXBlKSksIHR5cGUpKTsKCQkJ
CQl9CgkJCQl9Y2F0Y2ggKEV4Y2VwdGlvbiBlKSB7CgkJCQkJVXNlckNvbmZpZyB1c2VyQ29uZmln
ID0gbmV3IFVzZXJDb25maWcoKTsKCQkJCQl1c2VyQ29uZmlnLnNldEF1dGhlbnRpY2F0aW9uSWQo
dUkuZ2V0VXNlcklkKCkpOwoJCQkJCXVzZXJDb25maWcuc2V0VXNlclR5cGUodUkuZ2V0VXNlclR5
cGUoKSk7CgkJCQkJdXNlckNvbmZpZy5zZXRMb2dpbkRpc2FibGVkKHRydWUpOwoJCQkJCWlmICh1
SS5nZXRVc2VyVHlwZSgpLmVxdWFscygiVSIpKSB7CgkJCQkJCWlkYXRhTGlzdC5hZGQoQXNzZXRV
dGlscy5nZXRJRGF0YUZyb21QcmluY2lwYWxNb2RlbCh1c2VyQ29uZmlnKSk7CgkJCQkJfSBlbHNl
IGlmICh1SS5nZXRVc2VyVHlwZSgpLmVxdWFscygiRyIpKSB7CgkJCQkJCWlkYXRhTGlzdC5hZGQo
QXNzZXRVdGlscy5nZXRJRGF0YUdyb3VwRnJvbVByaW5jaXBhbE1vZGVsKHVzZXJDb25maWcpKTsK
CQkJCQl9CgkJCQl9CgoJCQl9CgkJfQoJfQp9IGNhdGNoIChUaHJvd2FibGUgdCkgewoJc3VjY2Vz
cyA9IGZhbHNlOwoJbWVzc2FnZSA9IHQuZ2V0TG9jYWxpemVkTWVzc2FnZSgpOwp9IGZpbmFsbHkg
ewoJVmFsdWVzRW11bGF0b3IucHV0KHBpcGVsaW5lLCAic3VjY2VzcyIsIFN0cmluZy52YWx1ZU9m
KHN1Y2Nlc3MpKTsKCVZhbHVlc0VtdWxhdG9yLnB1dChwaXBlbGluZSwgInVzZXJEZXRhaWxzIiwg
aWRhdGFMaXN0LnRvQXJyYXkobmV3IElEYXRhW2lkYXRhTGlzdC5zaXplKCldKSk7CglWYWx1ZXNF
bXVsYXRvci5wdXQocGlwZWxpbmUsICJ0b3RhbFVzZXJzIiwgdG90YWxVc2Vycyk7CglWYWx1ZXNF
bXVsYXRvci5wdXQocGlwZWxpbmUsICJtZXNzYWdlIiwgbWVzc2FnZSk7Cn0K</value>
</Values>
