<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">getSession</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:required Locale</value>
    <value>[o] record:0:required output</value>
    <value>[o] - field:0:required running</value>
    <value>[o] - field:0:required code</value>
    <value>[o] - field:0:required message</value>
  </array>
  <value name="subtype">unknown</value>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">CgkJSURhdGFDdXJzb3IgY3VyID0gbnVsbDsKCQlJRGF0YSBvdXRwdXQgPSBudWxsOwoJCUlEYXRh
Q3Vyc29yIG91dHB1dEN1ciA9IG51bGw7CgkJSURhdGEgc3ZjUmVzcCA9IG51bGw7CgkJU3RyaW5n
IHN2Y05hbWUgPSAid20ubWZ0LnBvcnRhbC5yb3V0ZTppbnZva2VTZXJ2aWNlIjsKCQlJRGF0YSBo
ZWFkZXJzID0gSURhdGFGYWN0b3J5LmNyZWF0ZSgpOwoJCXRyeSB7CgkJCWN1ciA9IHBpcGVsaW5l
LmdldEN1cnNvcigpOwoJCQlvdXRwdXQgPSBJRGF0YUZhY3RvcnkuY3JlYXRlKCk7CgkJCW91dHB1
dEN1ciA9IG91dHB1dC5nZXRDdXJzb3IoKTsKCgkJCVN0cmluZyB1c2VyTmFtZSA9IFNlcnZlckFk
bWluUHJveHkuZ2V0Q3VycmVudFVzZXIoKTsKCQkJSHR0cEhlYWRlciByZXNwSGVhZGVyID0gU2Vy
dmljZS5nZXRIdHRwUmVzcG9uc2VIZWFkZXIoKTsKCQkJcmVzcEhlYWRlci5hZGRGaWVsZCgidXNl
cm5hbWUiLCB1c2VyTmFtZSk7CgkJCWlmKFNlcnZlckFkbWluUHJveHkuaXNDbG91ZE1vZGUoKSkg
ewoJCQkJcmVzcEhlYWRlci5hZGRGaWVsZCgiY2xvdWQtdGVuYW50IiwgU2VydmVyQWRtaW5Qcm94
eS5nZXRUZW5hbnRJZCgpKTsKCQkJCXJlc3BIZWFkZXIuYWRkRmllbGQoIm1hbmFnZS1lbnZpcm9u
bWVudCIsIFNlcnZlckFkbWluUHJveHkuZ2V0TWFuYWdlRW52VXJsKCkpOwoJCQkJcmVzcEhlYWRl
ci5hZGRGaWVsZCgiY2xvdWQtZG9jLXVybCIsIFNlcnZlckFkbWluUHJveHkuZ2V0Q2xvdWREb2NV
cmwoKSk7CgoJCQkJcmVzcEhlYWRlci5hZGRGaWVsZCgiaXMtY2xvdWQtYWRtaW5pc3RyYXRvciIs
IFN0cmluZy52YWx1ZU9mKFNlcnZlckFkbWluUHJveHkuaXNDbG91ZEFkbWluaXN0cmF0b3IoKSkp
OwoJCQkJcmVzcEhlYWRlci5hZGRGaWVsZCgiaXMtY2xvdWQtYWNjb3VudC1hZG1pbmlzdHJhdG9y
IiwgU3RyaW5nLnZhbHVlT2YoU2VydmVyQWRtaW5Qcm94eS5pc0Nsb3VkVGVuYW50QWRtaW5pc3Ry
YXRvcigpKSk7CgkJCQlyZXNwSGVhZGVyLmFkZEZpZWxkKCJjbG91ZC1wcm92aWRlciIsIFNlcnZl
ckFkbWluUHJveHkuZ2V0Q2xvdWRQcm92aWRlcigpKTsKCQkJCXJlc3BIZWFkZXIuYWRkRmllbGQo
ImNsb3VkLWxvZ291dC11cmwiLCBTZXJ2ZXJBZG1pblByb3h5LmxvZ291dFJlZGlyZWN0VXJsKCkp
OwoJCQl9CgoJCQlhZGRTZWN1cml0eUhlYWRlcnMoKTsKCgkJfSBjYXRjaCAoVGhyb3dhYmxlIHQp
IHsKCQkJb3V0cHV0Q3VyLmluc2VydEFmdGVyKCJydW5uaW5nIiwgImZhbHNlIik7CgkJCW91dHB1
dEN1ci5pbnNlcnRBZnRlcigiY29kZSIsICI5OTk5Iik7CgkJCW91dHB1dEN1ci5pbnNlcnRBZnRl
cigibWVzc2FnZSIsIHQuZ2V0TG9jYWxpemVkTWVzc2FnZSgpKTsKCQl9ZmluYWxseXsKCQkJY3Vy
Lmluc2VydEFmdGVyKCJvdXRwdXQiLCBvdXRwdXQpOwoJCQljdXIuaW5zZXJ0QWZ0ZXIoImhlYWRl
cnMiLCBoZWFkZXJzKTsKLy8JCQlWYWx1ZXNFbXVsYXRvci5wdXQob3V0cHV0LCAiaGVhZGVycyIs
IGhlYWRlcnMpOwoJCQlpZihjdXIgIT0gbnVsbCkgY3VyLmRlc3Ryb3koKTsKCQkJaWYob3V0cHV0
Q3VyICE9IG51bGwpIG91dHB1dEN1ci5kZXN0cm95KCk7CgkJfQoK</value>
</Values>
