<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">getAllActiveTransferPropertiesWithDefaultValues</value>
  <array name="sig" type="value" depth="1">
    <value>[o] record:1:optional properties</value>
    <value>[o] field:0:required success</value>
    <value>[o] field:0:required message</value>
  </array>
  <value name="encodeutf8">true</value>
  <value name="body">CQkJYm9vbGVhbiBzdWNjZXNzID0gdHJ1ZTsKCQkJU3RyaW5nIG1lc3NhZ2UgPSBNRlRSZXNvdXJj
ZXMuZ2V0TWVzc2FnZSgiMTAxMyIpOwoJCQl0cnkgewoJCQkJUkJBUHJveHkudmFsaWRhdGVTZXNz
aW9uKFJCQVVpSGFuZGxlLlNFVFRJTkdTX1BST1BFUlRJRVNfVklFVyk7CgkJCQkKCQkJCWJvb2xl
YW4gaXNHYXRld2F5ID0gQ29tbW9uUHJveHkuaXNHYXRld2F5U2VydmVyKCk7CgkJCQlTdHJpbmcg
cHJvcGVydHlUeXBlID0gaXNHYXRld2F5ID8gR0FURVdBWV9QUk9QRVJUWSA6IFNFUlZFUl9QUk9Q
RVJUWTsKCQkJCS8vZ2V0IGFsbCBBY3RpdmVUcmFuc2ZlciBwcm9wZXJ0aWVzIHdpdGggZGVmYXVs
dCB2YWx1ZXMKCQkJCUxpc3Q8UHJvcGVydHlVdGlscz4gcHJvcGVydGllcyA9IFByb3BlcnR5VXRp
bHMuZ2V0QWxsUHJvcGVydHlVdGlsc1dpdGhEZWZhdWx0VmFsdWVzKHByb3BlcnR5VHlwZSk7CgkJ
CQlJRGF0YVtdIHByb3BlcnRpZXNJRGF0YSA9IG5ldyBJRGF0YVtwcm9wZXJ0aWVzLnNpemUoKV07
CgoJCQkJaW50IGkgPTA7CgkJCQlmb3IgKFByb3BlcnR5VXRpbHMgcHJvcGVydHlVdGlsIDogcHJv
cGVydGllcykgewoJCQkJCXByb3BlcnRpZXNJRGF0YVtpXSA9IElEYXRhRmFjdG9yeS5jcmVhdGUo
KTsKCQkJCQlWYWx1ZXNFbXVsYXRvci5wdXQocHJvcGVydGllc0lEYXRhW2ldLCAicHJvcGVydHlO
YW1lIiwgcHJvcGVydHlVdGlsLmdldFByb3BlcnR5TmFtZSgpKTsKCQkJCQlWYWx1ZXNFbXVsYXRv
ci5wdXQocHJvcGVydGllc0lEYXRhW2ldLCAicHJvcGVydHlWYWx1ZSIsIHByb3BlcnR5VXRpbC5n
ZXREZWZhdWx0VmFsdWUoKSk7CgkJCQkJVmFsdWVzRW11bGF0b3IucHV0KHByb3BlcnRpZXNJRGF0
YVtpXSwgImRlc2NyaXB0aW9uSWQiLCBwcm9wZXJ0eVV0aWwuZ2V0UHJvcGVydHlOYW1lKCkucmVw
bGFjZUFsbCgiXFwuIiwgIl8iKSk7CgkJCQkJaSsrOwoJCQkJfQoJCQkJVmFsdWVzRW11bGF0b3Iu
cHV0KHBpcGVsaW5lLCAicHJvcGVydGllcyIsIHByb3BlcnRpZXNJRGF0YSk7CgkJCX1jYXRjaCAo
VGhyb3dhYmxlIHQpewoJCSAgICAJc3VjY2VzcyA9IGZhbHNlOwoJCSAgICAJbWVzc2FnZSA9IHQu
Z2V0TG9jYWxpemVkTWVzc2FnZSgpOwoJCSAgICB9IGZpbmFsbHkgewoJCQkJVmFsdWVzRW11bGF0
b3IucHV0KHBpcGVsaW5lLCAic3VjY2VzcyIsIFN0cmluZy52YWx1ZU9mKHN1Y2Nlc3MpKTsKCQkJ
CVZhbHVlc0VtdWxhdG9yLnB1dChwaXBlbGluZSwgIm1lc3NhZ2UiLCBtZXNzYWdlKTsKCQkJfQo=
</value>
</Values>
