<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">deleteActiveTransferProperties</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:1:required propertyNames</value>
    <value>[o] field:0:required success</value>
    <value>[o] field:0:required message</value>
  </array>
  <value name="subtype">unknown</value>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">CQkJYm9vbGVhbiBzdWNjZXNzID0gdHJ1ZTsKCQkJU3RyaW5nIG1lc3NhZ2UgPSBNRlRSZXNvdXJj
ZXMuZ2V0TWVzc2FnZSgiMTAxMyIpOwoJCQlTdHJpbmdbXSBwcm9wZXJ0eU5hbWVzID0gbnVsbDsK
CQkJSURhdGFDdXJzb3IgY3VyID0gbnVsbDsKCQkJdHJ5IHsKCQkJCVJCQVByb3h5LnZhbGlkYXRl
U2Vzc2lvbihSQkFVaUhhbmRsZS5TRVRUSU5HU19QUk9QRVJUSUVTX1ZJRVcpOwoJCQkJCgkJCQlG
aWxlIHByb3BlcnR5RmlsZSA9IG5ldyBGaWxlKFNlcnZlci5nZXRSZXNvdXJjZXMoKS5nZXRQYWNr
YWdlQ29uZmlnRGlyKCJXbU1GVCIpLCAicHJvcGVydGllcy5jbmYiKTsKCQkJCWlmICghcHJvcGVy
dHlGaWxlLmNhbldyaXRlKCkpIHsKCQkJCQltZXNzYWdlID0gIlByb3BlcnR5IGZpbGUgaXMgcmVh
ZG9ubHkiOwoJCQkJCXN1Y2Nlc3MgPSBmYWxzZTsKCQkJCQlyZXR1cm47CgkJCQl9CgkJCQkvL2dl
dCBwcm9wZXJ0aWVzIGZyb20gcHJvcGVydGllcy5jbmYgZmlsZQoJCQkJUHJvcGVydGllcyBtZnRQ
cm9wZXJ0aWVzID0gYWRtaW5pbXBsLmdldE1mdFByb3BlcnRpZXMocHJvcGVydHlGaWxlKTsKCQkJ
CVByb3BlcnRpZXMgZGVsZXRlZFByb3BlcnRpZXMgPSBuZXcgUHJvcGVydGllcygpOwoJCQkJCgkJ
CQljdXIgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsKCQkgICAgCWlmICggY3VyLmZpcnN0ICggInBy
b3BlcnR5TmFtZXMiICkgKXsKCQkgICAgCQlwcm9wZXJ0eU5hbWVzID0gKFN0cmluZ1tdKWN1ci5n
ZXRWYWx1ZSgpOyAKCQkgICAgCQlpZihwcm9wZXJ0eU5hbWVzICE9IG51bGwgJiYgcHJvcGVydHlO
YW1lcy5sZW5ndGggPiAwKXsKCQkgICAgCQkJZm9yIChTdHJpbmcgcHJvcGVydHlOYW1lIDogcHJv
cGVydHlOYW1lcykgewoJCSAgICAJCQkJLy9pZiBwcm9wZXJ0eSBleGlzdHMgaW4gdGhlIHByb3Bl
cnR5IGZpbGUsIGVtcHR5IHRoYXQgcHJvcGVydHkgdmFsdWUgZnJvbSBwcm9wZXJ0eSBmaWxlCgkJ
ICAgIAkJCQlpZihtZnRQcm9wZXJ0aWVzLmdldChwcm9wZXJ0eU5hbWUpICE9IG51bGwpIHsKCQkg
ICAgCQkJCQkvL2xvYWQgZGVsZXRlZFByb3BlcnRpZXMgZm9yIGF1ZGl0IGxvZwoJCSAgICAJCQkJ
CWRlbGV0ZWRQcm9wZXJ0aWVzLnB1dChwcm9wZXJ0eU5hbWUsIG1mdFByb3BlcnRpZXMuZ2V0KHBy
b3BlcnR5TmFtZSkpOwoJCSAgICAJCQkJCW1mdFByb3BlcnRpZXMucHV0KHByb3BlcnR5TmFtZSwg
IiIpOwoJCSAgICAJCQkJfQoJCSAgICAJCQl9CgkJICAgIAkJCWFkbWluaW1wbC53cml0ZVRvTWZ0
UHJvcGVydHlGaWxlKHByb3BlcnR5RmlsZSwgbWZ0UHJvcGVydGllcyk7CgkJICAgIAkJCQoJCSAg
ICAJCQlTeXN0ZW0uZ2V0UHJvcGVydGllcygpLnB1dEFsbChtZnRQcm9wZXJ0aWVzKTsKCQkJCQkJ
Q29tbW9uUHJveHkudXBkYXRlUnVudGltZVByb3BlcnRpZXMoKTsKCQkJCQkJCgkJICAgIAkJCS8v
aW5zZXJ0IGF1ZGl0IGxvZyBmb3IgcHJvcGVydGllcyBERUxFVEUKCQkgICAgCQkJQ29tbW9uUHJv
eHkudXBkYXRlQXVkaXRJbmZvRm9yTUZUUHJvcGVydGllcyhkZWxldGVkUHJvcGVydGllcyk7CgkJ
ICAgIAkJCQoJCSAgICAJCQlub3RpZnlQcm9wZXJ0eUNoYW5nZXNUb0dyb3VwUmVtb3RlU2VydmVy
cyhkZWxldGVkUHJvcGVydGllcywgImRlbGV0ZSIpOwoJCSAgICAJCX0KCQkgICAgCX0KCQkJfSBj
YXRjaCAoVGhyb3dhYmxlIHQpewoJCSAgICAJc3VjY2VzcyA9IGZhbHNlOwoJCSAgICAJbWVzc2Fn
ZSA9IHQuZ2V0TG9jYWxpemVkTWVzc2FnZSgpOwoJCSAgICB9IGZpbmFsbHkgewoJCQkJVmFsdWVz
RW11bGF0b3IucHV0KHBpcGVsaW5lLCAic3VjY2VzcyIsIFN0cmluZy52YWx1ZU9mKHN1Y2Nlc3Mp
KTsKCQkJCVZhbHVlc0VtdWxhdG9yLnB1dChwaXBlbGluZSwgIm1lc3NhZ2UiLCBtZXNzYWdlKTsK
CQkJfQo=</value>
</Values>
