<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">setProperties</value>
  <array name="sig" type="value" depth="1">
    <value>[o] field:0:required message</value>
    <value>[o] field:0:required success</value>
  </array>
  <value name="subtype">unknown</value>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">cHVibGljIHN0YXRpYyBmaW5hbCB2b2lkIHNldFByb3BlcnRpZXMoSURhdGEgcGlwZWxpbmUpIHsK
CWJvb2xlYW4gc3VjY2VzcyA9IHRydWU7CglTdHJpbmcgbWVzc2FnZSA9IE1GVFJlc291cmNlcy5n
ZXRNZXNzYWdlKCIxMDEzIik7Cgl0cnkgewoJCVJCQVByb3h5LnZhbGlkYXRlU2Vzc2lvbihSQkFV
aUhhbmRsZS5EQVRBQkFTRV9BUkNISVZBTF9FWEVDVVRFKTsKCQlTdHJpbmcgc2NoZW1hTmFtZSA9
IFZhbHVlc0VtdWxhdG9yLmdldFN0cmluZyhwaXBlbGluZSwgInNjaGVtYU5hbWUiKTsKCQlTdHJp
bmcgcmV0ZW50aW9uUGVyaW9kSW5EYXlzID0gVmFsdWVzRW11bGF0b3IuZ2V0U3RyaW5nKHBpcGVs
aW5lLCAicmV0ZW50aW9uUGVyaW9kSW5EYXlzIik7CgkJVUlVdGlscy5pc0VtcHR5KHNjaGVtYU5h
bWUsICJzY2hlbWFOYW1lIik7CgkJVUlVdGlscy5pc0VtcHR5KHJldGVudGlvblBlcmlvZEluRGF5
cywgInJldGVudGlvblBlcmlvZEluRGF5cyIpOwoJCWlmICghYWRtaW5pbXBsLnZhbGlkU2NoZW1h
TmFtZShzY2hlbWFOYW1lKSkgewoJCQl0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbihNRlRSZXNv
dXJjZXMuZ2V0TWVzc2FnZSgiMTUzMiIpKTsKCQl9CgkJaWYgKHNjaGVtYU5hbWUubGVuZ3RoKCkg
PiA2NCkgewoJCQl0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbihNRlRSZXNvdXJjZXMuZ2V0TWVz
c2FnZSgiMTUzMCIpKTsKCQl9CgkJdHJ5IHsKCQkJaWYgKEludGVnZXIucGFyc2VJbnQocmV0ZW50
aW9uUGVyaW9kSW5EYXlzKSA8PSAwKSB7CgkJCQl0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbihN
RlRSZXNvdXJjZXMuZ2V0TWVzc2FnZSgiMTUyNSIpKTsKCQkJfQoJCQlpZiAoSW50ZWdlci5wYXJz
ZUludChyZXRlbnRpb25QZXJpb2RJbkRheXMpID4gOTk5OSkgewoJCQkJdGhyb3cgbmV3IFNlcnZp
Y2VFeGNlcHRpb24oTUZUUmVzb3VyY2VzLmdldE1lc3NhZ2UoIjE1MjgiKSk7CgkJCX0KCQl9IGNh
dGNoKE51bWJlckZvcm1hdEV4Y2VwdGlvbiBleCkgewoJCQl0aHJvdyBuZXcgU2VydmljZUV4Y2Vw
dGlvbihNRlRSZXNvdXJjZXMuZ2V0TWVzc2FnZSgiMTUyOSIpKTsKCQl9CgkJCgkJTWFwPFN0cmlu
ZywgU3RyaW5nPiBkYkFyY2hpdmFsUHJvcHMgPSBuZXcgSGFzaE1hcDw+KCk7CgkJZGJBcmNoaXZh
bFByb3BzLnB1dCgic2NoZW1hTmFtZSIsIHNjaGVtYU5hbWUpOwoJCWRiQXJjaGl2YWxQcm9wcy5w
dXQoInJldGVudGlvblBlcmlvZEluRGF5cyIsIHJldGVudGlvblBlcmlvZEluRGF5cyk7CgkJQ29t
bW9uUHJveHkuc2V0TUZUQXBwUHJvcGVydGllcyhkYkFyY2hpdmFsUHJvcHMsIE1GVEFwcFByb3Bl
cnR5VHlwZXMuRGF0YWJhc2VBcmNoaXZhbCk7Cgl9IGNhdGNoIChUaHJvd2FibGUgdCkgewoJCXN1
Y2Nlc3MgPSBmYWxzZTsKCQltZXNzYWdlID0gdC5nZXRMb2NhbGl6ZWRNZXNzYWdlKCk7Cgl9IGZp
bmFsbHkgewoJCVZhbHVlc0VtdWxhdG9yLnB1dChwaXBlbGluZSwgInN1Y2Nlc3MiLCBzdWNjZXNz
KTsKCQlWYWx1ZXNFbXVsYXRvci5wdXQocGlwZWxpbmUsICJtZXNzYWdlIiwgbWVzc2FnZSk7Cgl9
Cg==</value>
</Values>
