<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">getActiveTransferPropertiesForComplexity</value>
  <array name="sig" type="value" depth="1">
    <value>[o] record:1:optional properties</value>
    <value>[o] field:0:required success</value>
    <value>[o] field:0:required message</value>
  </array>
  <value name="encodeutf8">true</value>
  <value name="body">Ym9vbGVhbiBzdWNjZXNzID0gdHJ1ZTsKU3RyaW5nIG1lc3NhZ2UgPSBNRlRSZXNvdXJjZXMuZ2V0
TWVzc2FnZSgiMTAxMyIpOwp0cnkgewoJRmlsZSBwcm9wZXJ0eUZpbGUgPSBuZXcgRmlsZShTZXJ2
ZXIuZ2V0UmVzb3VyY2VzKCkuZ2V0UGFja2FnZUNvbmZpZ0RpcigiV21NRlQiKSwgInByb3BlcnRp
ZXMuY25mIik7CglpZiAoIXByb3BlcnR5RmlsZS5leGlzdHMoKSkgewoJCW1lc3NhZ2UgPSAiVGhl
IHByb3BlcnR5IGZpbGUgcHJvcGVydGllcy5jbmYgZG9lcyBub3QgZXhpc3RzLiI7CgkJc3VjY2Vz
cyA9IGZhbHNlOwoJCXJldHVybjsKCX0KCgkvL2dldCB0aGUgcHJvcGVydGllcyBmcm9tIHByb3Bl
cnRpZXMuY25mIGZpbGUKCVByb3BlcnRpZXMgbWZ0UHJvcGVydGllcyA9IGFkbWluaW1wbC5nZXRN
ZnRQcm9wZXJ0aWVzKHByb3BlcnR5RmlsZSk7CgoJU3RyaW5nIHByb3BlcnR5VHlwZSA9ICBTRVJW
RVJfUFJPUEVSVFk7CgkvL2ZpbHRlciBwcm9wZXJ0aWVzIGluIGZpbGUgdXNpbmcgYWxsIEFjdGl2
ZVRyYW5zZmVyIHByb3BlcnRpZXMKCW1mdFByb3BlcnRpZXMgPSBmaWx0ZXJQcm9wZXJ0aWVzSW5Q
cm9wZXJ0eUZpbGUobWZ0UHJvcGVydGllcywgcHJvcGVydHlUeXBlKTsKCUlEYXRhIGNvbXBsZXhp
dHlJRGF0YSA9IElEYXRhRmFjdG9yeS5jcmVhdGUoKTsKCVN0cmluZyBwcm9wZXJ0eU5hbWUgPSBQ
cm9wZXJ0eVV0aWxzLk1GVF9TRVJWRVJfUEFTU1dPUkRfQ09NUExFWElUWS5nZXRQcm9wZXJ0eU5h
bWUoKTsKCVN0cmluZyBwcm9wZXJ0eVZhbHVlID0gbWZ0UHJvcGVydGllcy5nZXRQcm9wZXJ0eShw
cm9wZXJ0eU5hbWUpOwoJU3RyaW5nIGRlc2NyaXB0aW9uSWQgPSBwcm9wZXJ0eU5hbWUucmVwbGFj
ZUFsbCgiXFwuIiwgIl8iKTsKCVZhbHVlc0VtdWxhdG9yLnB1dChjb21wbGV4aXR5SURhdGEsICJw
cm9wZXJ0eU5hbWUiLCBwcm9wZXJ0eU5hbWUpOwoJVmFsdWVzRW11bGF0b3IucHV0KGNvbXBsZXhp
dHlJRGF0YSwgInByb3BlcnR5VmFsdWUiLCBwcm9wZXJ0eVZhbHVlKTsKCVZhbHVlc0VtdWxhdG9y
LnB1dChjb21wbGV4aXR5SURhdGEsICJkZXNjcmlwdGlvbklkIiwgZGVzY3JpcHRpb25JZCk7CglW
YWx1ZXNFbXVsYXRvci5wdXQoY29tcGxleGl0eUlEYXRhLCAiZGVmYXVsdFZhbHVlIiwgUHJvcGVy
dHlVdGlscy52YWx1ZU9mKGRlc2NyaXB0aW9uSWQudG9VcHBlckNhc2UoTG9jYWxlLkVOR0xJU0gp
KS5nZXREZWZhdWx0VmFsdWUoKSk7CglWYWx1ZXNFbXVsYXRvci5wdXQocGlwZWxpbmUsICJwcm9w
ZXJ0aWVzIiwgY29tcGxleGl0eUlEYXRhKTsKfSBjYXRjaCAoVGhyb3dhYmxlIHQpIHsKCXN1Y2Nl
c3MgPSBmYWxzZTsKCW1lc3NhZ2UgPSB0LmdldExvY2FsaXplZE1lc3NhZ2UoKTsKfSBmaW5hbGx5
IHsKCVZhbHVlc0VtdWxhdG9yLnB1dChwaXBlbGluZSwgInN1Y2Nlc3MiLCBTdHJpbmcudmFsdWVP
ZihzdWNjZXNzKSk7CglWYWx1ZXNFbXVsYXRvci5wdXQocGlwZWxpbmUsICJtZXNzYWdlIiwgbWVz
c2FnZSk7Cn0K</value>
</Values>
