<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">update</value>
  <array name="sig" type="value" depth="1">
    <value>[i] recref:0:required userInfo wm.mft.assets.rec.user:UserDetails</value>
    <value>[o] field:0:required success</value>
    <value>[o] field:0:required userId</value>
  </array>
  <value name="subtype">unknown</value>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">CmJvb2xlYW4gc3VjY2VzcyA9IGZhbHNlOwpib29sZWFuIHVwZGF0ZVN5c0RpciA9IGZhbHNlOwpT
dHJpbmcgbWVzc2FnZSA9IE1GVFJlc291cmNlcy5nZXRNZXNzYWdlKCIxMDEzIik7ClVzZXJDb25m
aWcgdXNlckNvbmZpZyA9IG51bGw7CklEYXRhIHVzZXJJbmZvID0gKElEYXRhKSBWYWx1ZXNFbXVs
YXRvci5nZXQocGlwZWxpbmUsICJ1c2VySW5mbyIpOwppZiAodXNlckluZm8gPT0gbnVsbCkgewoJ
dGhyb3cgbmV3IFNlcnZpY2VFeGNlcHRpb24oTUZUUmVzb3VyY2VzLmdldE1lc3NhZ2UoIjEwMDEi
LCAidXNlckluZm8iKSk7Cn0KU3RyaW5nIHVzZXJJZCA9IFZhbHVlc0VtdWxhdG9yLmdldFN0cmlu
Zyh1c2VySW5mbywgInVzZXJJZCIpOwpTdHJpbmcgdXNlclR5cGUgPSBWYWx1ZXNFbXVsYXRvci5n
ZXRTdHJpbmcodXNlckluZm8sICJ1c2VyVHlwZSIpOwp1c2VySW5mbyA9IGVtcHR5VG9aZXJvKHVz
ZXJJbmZvKTsKdHJ5IHsKCWlmIChVc2VySWRlbnRpdHkuVVNFUi5lcXVhbHModXNlclR5cGUpKQoJ
CVJCQVByb3h5LnZhbGlkYXRlU2Vzc2lvbihSQkFVaUhhbmRsZS5VU0VSX1VQREFURSk7CgllbHNl
IGlmIChVc2VySWRlbnRpdHkuUk9MRS5lcXVhbHModXNlclR5cGUpKQoJCVJCQVByb3h5LnZhbGlk
YXRlU2Vzc2lvbihSQkFVaUhhbmRsZS5ST0xFX1VQREFURSk7CgllbHNlCgkJUkJBUHJveHkudmFs
aWRhdGVTZXNzaW9uKFJCQVVpSGFuZGxlLkdST1VQX1VQREFURSk7CglJRGF0YSBpbmhlcml0YW5j
ZU1hcCA9IChJRGF0YSkgVmFsdWVzRW11bGF0b3IuZ2V0KHVzZXJJbmZvLCAiaW5oZXJpdGFuY2VN
YXAiKTsKCXVzZXJDb25maWcgPSBVc2VyTWFuYWdlclByb3h5LnZpZXdVc2VyKHVzZXJJZCwgdXNl
cklkLCB1c2VyVHlwZSwgdHJ1ZSk7Cgl1cGRhdGVUZW1wbGF0ZURhdGEodXNlckNvbmZpZywgVmFs
dWVzRW11bGF0b3IuZ2V0U3RyaW5nKHVzZXJJbmZvLCAidGVtcGxhdGVJZCIpKTsKCUFzc2V0VXRp
bHMuc2V0UGFydG5lckRldGFpbHNGcm9tSURhdGEodXNlckluZm8sIHVzZXJDb25maWcpOwoJVUlV
dGlscy5zZXRVc2VyRGV0YWlsc0ZvclVzZXIodXNlckluZm8sIHVzZXJDb25maWcpOwoJcmVzZXRJ
bmhlcml0ZWRWYWx1ZXMoaW5oZXJpdGFuY2VNYXAsIHVzZXJDb25maWcsIHVzZXJJbmZvKTsKCWlm
ICh1c2VyVHlwZSAhPSBudWxsICYmIHVzZXJUeXBlLmVxdWFsc0lnbm9yZUNhc2UoVXNlcklkZW50
aXR5LlVTRVIpICYmIHVzZXJDb25maWcgIT0gbnVsbCAmJiB1c2VyQ29uZmlnLmdldERpcmVjdG9y
eVNlcnZpY2UoKSAhPSBudWxsICYmdXNlckNvbmZpZy5nZXREaXJlY3RvcnlTZXJ2aWNlKCkuZXF1
YWxzKCJTeXN0ZW0iKSkgewoJCXVwZGF0ZVN5c0RpciA9IHRydWU7Cgl9CglzdWNjZXNzID0gVXNl
ck1hbmFnZXJQcm94eS51cGRhdGVVc2VyKHVzZXJDb25maWcsIHVwZGF0ZVN5c0Rpcik7Cn0gY2F0
Y2ggKFRocm93YWJsZSB0KSB7CgltZXNzYWdlID0gdC5nZXRMb2NhbGl6ZWRNZXNzYWdlKCk7Cn0g
ZmluYWxseSB7CglWYWx1ZXNFbXVsYXRvci5yZW1vdmUocGlwZWxpbmUsICJ1c2VySW5mbyIpOwoJ
VmFsdWVzRW11bGF0b3IucHV0KHBpcGVsaW5lLCAibWVzc2FnZSIsIG1lc3NhZ2UpOwoJVmFsdWVz
RW11bGF0b3IucHV0KHBpcGVsaW5lLCAic3VjY2VzcyIsIFN0cmluZy52YWx1ZU9mKHN1Y2Nlc3Mp
KTsKCVZhbHVlc0VtdWxhdG9yLnB1dChwaXBlbGluZSwgInVzZXJJZCIsIFN0cmluZy52YWx1ZU9m
KHVzZXJDb25maWcuZ2V0SWQoKSkpOwp9Cg==</value>
</Values>
