<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">list</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:optional pageNumber</value>
    <value>[i] field:0:optional pageSize</value>
    <value>[i] record:0:optional filters</value>
    <value>[i] - field:0:optional nameLike</value>
    <value>[i] - field:0:optional isActive</value>
    <value>[i] - field:0:optional usage</value>
    <value>[i] field:0:optional sortOrder</value>
    <value>[o] field:0:required success</value>
    <value>[o] field:0:required message</value>
    <value>[o] record:0:required pagination</value>
    <value>[o] - field:0:required pageNumber</value>
    <value>[o] - field:0:required pageSize</value>
    <value>[o] - field:0:required totalRows</value>
    <value>[o] - field:0:required totalPages</value>
    <value>[o] record:1:required templates</value>
    <value>[o] - field:0:required id</value>
    <value>[o] - field:0:required name</value>
    <value>[o] - field:0:required description</value>
    <value>[o] - field:0:required isActive</value>
    <value>[o] - field:0:required usage</value>
  </array>
  <value name="subtype">unknown</value>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">IApTdHJpbmcgbWVzc2FnZSA9ICIiOwpib29sZWFuIHN1Y2Nlc3MgPSB0cnVlOwp0cnkgewogICAg
UkJBUHJveHkudmFsaWRhdGVTZXNzaW9uKFJCQVVpSGFuZGxlLkFDVElPTl9URV9WSUVXKTsKICAg
IAogICAgLy8gR2V0IHBhZ2luYXRpb24gcGFyYW1ldGVycwogICAgU3RyaW5nIHBhZ2VOdW1iZXJT
dHIgPSBWYWx1ZXNFbXVsYXRvci5nZXRTdHJpbmcocGlwZWxpbmUsICJwYWdlTnVtYmVyIik7CiAg
ICBTdHJpbmcgcGFnZVNpemVTdHIgPSBWYWx1ZXNFbXVsYXRvci5nZXRTdHJpbmcocGlwZWxpbmUs
ICJwYWdlU2l6ZSIpOwogICAgCiAgICBpbnQgcGFnZU51bWJlciA9IDE7CiAgICBpbnQgcGFnZVNp
emUgPSAyMDsKICAgIAogICAgaWYgKHBhZ2VOdW1iZXJTdHIgIT0gbnVsbCAmJiAhcGFnZU51bWJl
clN0ci5pc0VtcHR5KCkpIHsKICAgICAgICB0cnkgewogICAgICAgICAgICBwYWdlTnVtYmVyID0g
SW50ZWdlci5wYXJzZUludChwYWdlTnVtYmVyU3RyKTsKICAgICAgICAgICAgaWYgKHBhZ2VOdW1i
ZXIgPCAxKSBwYWdlTnVtYmVyID0gMTsKICAgICAgICB9IGNhdGNoIChOdW1iZXJGb3JtYXRFeGNl
cHRpb24gZSkgewogICAgICAgICAgICBwYWdlTnVtYmVyID0gMTsKICAgICAgICB9CiAgICB9CiAg
ICAKICAgIGlmIChwYWdlU2l6ZVN0ciAhPSBudWxsICYmICFwYWdlU2l6ZVN0ci5pc0VtcHR5KCkp
IHsKICAgICAgICB0cnkgewogICAgICAgICAgICBwYWdlU2l6ZSA9IEludGVnZXIucGFyc2VJbnQo
cGFnZVNpemVTdHIpOwogICAgICAgICAgICBpZiAocGFnZVNpemUgPCAxKSBwYWdlU2l6ZSA9IDIw
OwogICAgICAgICAgICBpZiAocGFnZVNpemUgPiAxMDApIHBhZ2VTaXplID0gMTAwOwogICAgICAg
IH0gY2F0Y2ggKE51bWJlckZvcm1hdEV4Y2VwdGlvbiBlKSB7CiAgICAgICAgICAgIHBhZ2VTaXpl
ID0gMjA7CiAgICAgICAgfQogICAgfQogICAgCiAgICAvLyBHZXQgZmlsdGVyIHBhcmFtZXRlcnMK
ICAgIElEYXRhIGZpbHRlcnMgPSAoSURhdGEpIFZhbHVlc0VtdWxhdG9yLmdldChwaXBlbGluZSwg
ImZpbHRlcnMiKTsKICAgIFN0cmluZyBuYW1lTGlrZSA9IG51bGw7CiAgICBTdHJpbmcgaXNBY3Rp
dmVGaWx0ZXIgPSBudWxsOwogICAgU3RyaW5nIHVzYWdlRmlsdGVyID0gbnVsbDsKICAgIAogICAg
aWYgKGZpbHRlcnMgIT0gbnVsbCkgewogICAgICAgIG5hbWVMaWtlID0gVmFsdWVzRW11bGF0b3Iu
Z2V0U3RyaW5nKGZpbHRlcnMsICJuYW1lTGlrZSIpOwogICAgICAgIGlzQWN0aXZlRmlsdGVyID0g
VmFsdWVzRW11bGF0b3IuZ2V0U3RyaW5nKGZpbHRlcnMsICJpc0FjdGl2ZSIpOwogICAgICAgIHVz
YWdlRmlsdGVyID0gVmFsdWVzRW11bGF0b3IuZ2V0U3RyaW5nKGZpbHRlcnMsICJ1c2FnZSIpOwog
ICAgfQogICAgCiAgICAvLyBHZXQgc29ydCBvcmRlcgogICAgU3RyaW5nIHNvcnRPcmRlciA9IFZh
bHVlc0VtdWxhdG9yLmdldFN0cmluZyhwaXBlbGluZSwgInNvcnRPcmRlciIpOwogICAgaWYgKHNv
cnRPcmRlciA9PSBudWxsIHx8IHNvcnRPcmRlci5pc0VtcHR5KCkpIHsKICAgICAgICBzb3J0T3Jk
ZXIgPSAibmFtZTphc2MiOwogICAgfQogICAgCiAgICAvLyBCdWlsZCBzZWFyY2ggc3RyaW5nIGZv
ciBiYWNrZW5kCiAgICBTdHJpbmcgc2VhcmNoU3RyaW5nID0gKG5hbWVMaWtlICE9IG51bGwgJiYg
IW5hbWVMaWtlLmlzRW1wdHkoKSkgPyBuYW1lTGlrZSA6IG51bGw7CiAgICAKICAgIC8vIEdldCBh
bGwgdGVtcGxhdGVzIGZyb20gYmFja2VuZAogICAgTGlzdDxBY3Rpb25UZW1wbGF0ZT4gYWxsVGVt
cGxhdGVzID0gRXZlbnRzUHJveHkubGlzdEFjdGlvblRlbXBsYXRlcyhzZWFyY2hTdHJpbmcpOwog
ICAgCiAgICAvLyBBcHBseSBpc0FjdGl2ZSBmaWx0ZXIgaWYgc3BlY2lmaWVkCiAgICBpZiAoaXNB
Y3RpdmVGaWx0ZXIgIT0gbnVsbCAmJiAhaXNBY3RpdmVGaWx0ZXIuaXNFbXB0eSgpKSB7CiAgICAg
ICAgYm9vbGVhbiBhY3RpdmVWYWx1ZSA9IEJvb2xlYW4ucGFyc2VCb29sZWFuKGlzQWN0aXZlRmls
dGVyKTsKICAgICAgICBhbGxUZW1wbGF0ZXMgPSBhbGxUZW1wbGF0ZXMuc3RyZWFtKCkKICAgICAg
ICAgICAgLmZpbHRlcih0IC0+IHQuaXNBY3RpdmUoKSA9PSBhY3RpdmVWYWx1ZSkKICAgICAgICAg
ICAgLmNvbGxlY3QoamF2YS51dGlsLnN0cmVhbS5Db2xsZWN0b3JzLnRvTGlzdCgpKTsKICAgIH0K
ICAgIAogICAgLy8gQXBwbHkgdXNhZ2UgZmlsdGVyIGlmIHNwZWNpZmllZAogICAgaWYgKHVzYWdl
RmlsdGVyICE9IG51bGwgJiYgIXVzYWdlRmlsdGVyLmlzRW1wdHkoKSkgewogICAgICAgIGJvb2xl
YW4gdXNhZ2VWYWx1ZSA9IEJvb2xlYW4ucGFyc2VCb29sZWFuKHVzYWdlRmlsdGVyKTsKICAgICAg
ICBhbGxUZW1wbGF0ZXMgPSBhbGxUZW1wbGF0ZXMuc3RyZWFtKCkKICAgICAgICAgICAgLmZpbHRl
cih0IC0+IHQuaXNVc2FnZSgpID09IHVzYWdlVmFsdWUpCiAgICAgICAgICAgIC5jb2xsZWN0KGph
dmEudXRpbC5zdHJlYW0uQ29sbGVjdG9ycy50b0xpc3QoKSk7CiAgICB9CiAgICAKICAgIC8vIEFw
cGx5IHNvcnRpbmcKICAgIFN0cmluZ1tdIHNvcnRQYXJ0cyA9IHNvcnRPcmRlci5zcGxpdCgiOiIp
OwogICAgU3RyaW5nIHNvcnRGaWVsZCA9IHNvcnRQYXJ0cy5sZW5ndGggPiAwID8gc29ydFBhcnRz
WzBdIDogIm5hbWUiOwogICAgU3RyaW5nIHNvcnREaXJlY3Rpb24gPSBzb3J0UGFydHMubGVuZ3Ro
ID4gMSA/IHNvcnRQYXJ0c1sxXSA6ICJhc2MiOwogICAgaWYgKCJuYW1lIi5lcXVhbHNJZ25vcmVD
YXNlKHNvcnRGaWVsZCkpIHsKICAgICAgICBhbGxUZW1wbGF0ZXMuc29ydCgodDEsIHQyKSAtPiB7
CiAgICAgICAgICAgIGludCBjbXAgPSB0MS5nZXROYW1lKCkuY29tcGFyZVRvSWdub3JlQ2FzZSh0
Mi5nZXROYW1lKCkpOwogICAgICAgICAgICByZXR1cm4gImRlc2MiLmVxdWFsc0lnbm9yZUNhc2Uo
c29ydERpcmVjdGlvbikgPyAtY21wIDogY21wOwogICAgICAgIH0pOwogICAgfQogICAgCiAgICAv
LyBDYWxjdWxhdGUgcGFnaW5hdGlvbgogICAgaW50IHRvdGFsUm93cyA9IGFsbFRlbXBsYXRlcy5z
aXplKCk7CiAgICBpbnQgdG90YWxQYWdlcyA9IChpbnQpIE1hdGguY2VpbCgoZG91YmxlKSB0b3Rh
bFJvd3MgLyBwYWdlU2l6ZSk7CiAgICBpbnQgc3RhcnRJbmRleCA9IChwYWdlTnVtYmVyIC0gMSkg
KiBwYWdlU2l6ZTsKICAgIGludCBlbmRJbmRleCA9IE1hdGgubWluKHN0YXJ0SW5kZXggKyBwYWdl
U2l6ZSwgdG90YWxSb3dzKTsKICAgIAogICAgLy8gR2V0IHBhZ2Ugc2xpY2UKICAgIExpc3Q8QWN0
aW9uVGVtcGxhdGU+IHBhZ2VUZW1wbGF0ZXMgPSBhbGxUZW1wbGF0ZXMuc3ViTGlzdCgKICAgICAg
ICBNYXRoLm1heCgwLCBzdGFydEluZGV4KSwKICAgICAgICBNYXRoLm1heCgwLCBlbmRJbmRleCkK
ICAgICk7CiAgICAKICAgIC8vIENvbnZlcnQgdG8gSURhdGEgYXJyYXkKICAgIElEYXRhW10gdGVt
cGxhdGVBcnJheSA9IG5ldyBJRGF0YVtwYWdlVGVtcGxhdGVzLnNpemUoKV07CiAgICBmb3IgKGlu
dCBpID0gMDsgaSA8IHBhZ2VUZW1wbGF0ZXMuc2l6ZSgpOyBpKyspIHsKICAgICAgICB0ZW1wbGF0
ZUFycmF5W2ldID0gQXNzZXRVdGlscy5nZXRBY3Rpb25UZW1wbGF0ZUFzSURhdGEocGFnZVRlbXBs
YXRlcy5nZXQoaSksIGZhbHNlKTsKICAgIH0KICAgIAogICAgLy8gU2V0IG91dHB1dAogICAgVmFs
dWVzRW11bGF0b3IucHV0KHBpcGVsaW5lLCAidGVtcGxhdGVzIiwgdGVtcGxhdGVBcnJheSk7CiAg
ICAKICAgIC8vIFNldCBwYWdpbmF0aW9uIG1ldGFkYXRhCiAgICBJRGF0YSBwYWdpbmF0aW9uID0g
SURhdGFGYWN0b3J5LmNyZWF0ZSgpOwogICAgVmFsdWVzRW11bGF0b3IucHV0KHBhZ2luYXRpb24s
ICJwYWdlTnVtYmVyIiwgU3RyaW5nLnZhbHVlT2YocGFnZU51bWJlcikpOwogICAgVmFsdWVzRW11
bGF0b3IucHV0KHBhZ2luYXRpb24sICJwYWdlU2l6ZSIsIFN0cmluZy52YWx1ZU9mKHBhZ2VTaXpl
KSk7CiAgICBWYWx1ZXNFbXVsYXRvci5wdXQocGFnaW5hdGlvbiwgInRvdGFsUm93cyIsIFN0cmlu
Zy52YWx1ZU9mKHRvdGFsUm93cykpOwogICAgVmFsdWVzRW11bGF0b3IucHV0KHBhZ2luYXRpb24s
ICJ0b3RhbFBhZ2VzIiwgU3RyaW5nLnZhbHVlT2YodG90YWxQYWdlcykpOwogICAgVmFsdWVzRW11
bGF0b3IucHV0KHBpcGVsaW5lLCAicGFnaW5hdGlvbiIsIHBhZ2luYXRpb24pOwogICAgCn0gY2F0
Y2ggKEV4Y2VwdGlvbiB0KSB7CiAgICBzdWNjZXNzID0gZmFsc2U7CiAgICBtZXNzYWdlID0gdC5n
ZXRMb2NhbGl6ZWRNZXNzYWdlKCk7Cn0gZmluYWxseSB7CiAgICBWYWx1ZXNFbXVsYXRvci5wdXQo
cGlwZWxpbmUsICJzdWNjZXNzIiwgU3RyaW5nLnZhbHVlT2Yoc3VjY2VzcykpOwogICAgVmFsdWVz
RW11bGF0b3IucHV0KHBpcGVsaW5lLCAibWVzc2FnZSIsIG1lc3NhZ2UpOwp9Cg==</value>
</Values>
