<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">changePassword</value>
  <array name="sig" type="value" depth="1">
    <value>[i] recref:0:required userInfo wm.mft.assets.rec.user:UserDetails</value>
    <value>[o] field:0:required success</value>
    <value>[o] field:0:required userId</value>
  </array>
  <value name="subtype">unknown</value>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">CmJvb2xlYW4gc3VjY2VzcyA9IGZhbHNlOwpib29sZWFuIHVwZGF0ZVN5c0RpciA9IGZhbHNlOwpT
dHJpbmcgbWVzc2FnZSA9IE1GVFJlc291cmNlcy5nZXRNZXNzYWdlKCIxMDEzIik7ClVzZXJDb25m
aWcgdXNlckNvbmZpZyA9IG51bGw7Ckxpc3Q8U3RyaW5nPiBlcnJvck1lc3NhZ2VzID0gbmV3IEFy
cmF5TGlzdDw+KCk7CklEYXRhIHVzZXJJbmZvID0gKElEYXRhKSBWYWx1ZXNFbXVsYXRvci5nZXQo
cGlwZWxpbmUsICJ1c2VySW5mbyIpOwpTdHJpbmcgdHlwZVBhc3N3b3JkID0gVmFsdWVzRW11bGF0
b3IuZ2V0U3RyaW5nKHVzZXJJbmZvLCAiZ2VuZXJhdGVQYXNzd29yZCIpOwppZiAodXNlckluZm8g
PT0gbnVsbCkgewoJdGhyb3cgbmV3IFNlcnZpY2VFeGNlcHRpb24oTUZUUmVzb3VyY2VzLmdldE1l
c3NhZ2UoIjEwMDEiLCAidXNlckluZm8iKSk7Cn0KdHJ5IHsKCXVzZXJDb25maWcgPSBBc3NldFV0
aWxzLmdldFVzZXJEZXRhaWxzV2l0aEFkdmFuY2VkU2V0dGluZ3NGcm9tSURhdGEodXNlckluZm8p
OwoJc2V0UmFuZG9tUGFzc3dvcmQodXNlckNvbmZpZywgcGlwZWxpbmUpOwoJU3RyaW5nIHVzZXJU
eXBlID0gVmFsdWVzRW11bGF0b3IuZ2V0U3RyaW5nKHVzZXJJbmZvLCAidXNlclR5cGUiKTsKCWlm
ICh1c2VyVHlwZSAhPSBudWxsICYmIHVzZXJUeXBlLmVxdWFsc0lnbm9yZUNhc2UoVXNlcklkZW50
aXR5LlVTRVIpKSB7CgkJdXBkYXRlU3lzRGlyID0gdHJ1ZTsKCX0KCWlmKHR5cGVQYXNzd29yZCAh
PSBudWxsICYmIHR5cGVQYXNzd29yZC5lcXVhbHNJZ25vcmVDYXNlKCJzZW5kUGFzc3dvcmRMaW5r
IikpIHsKCQlzdWNjZXNzID0gdHJ1ZTsKCX0gZWxzZSBpZih0eXBlUGFzc3dvcmQgIT0gbnVsbCAm
JiB0eXBlUGFzc3dvcmQuZXF1YWxzSWdub3JlQ2FzZSgiY3JlYXRlUGFzc3dvcmQiKXx8dHlwZVBh
c3N3b3JkLmVxdWFsc0lnbm9yZUNhc2UoInJhbmRvbVBhc3N3b3JkIikpewoJCXN1Y2Nlc3MgPSBV
c2VyTWFuYWdlclByb3h5LmNoYW5nZVBhc3N3b3JkKHVzZXJDb25maWcsIHVwZGF0ZVN5c0Rpciwg
ZXJyb3JNZXNzYWdlcyk7CgkJaWYgKHN1Y2Nlc3MpIHsKCQkJU3RyaW5nIHNlbmRFbWFpbCA9IFZh
bHVlc0VtdWxhdG9yLmdldFN0cmluZyh1c2VySW5mbywgInNlbmRFbWFpbCIpOwoJCQlpZiAoc2Vu
ZEVtYWlsICE9IG51bGwgJiYgInRydWUiLmVxdWFsc0lnbm9yZUNhc2Uoc2VuZEVtYWlsKSkgewoJ
CQkJTGlzdDxTZXJ2ZXJDb25maWc+IHNlcnZlcnMgPSBTZXJ2ZXJBZG1pblByb3h5Lmxpc3RTZXJ2
ZXJzRm9yRW1haWwoKTsKCQkJCVN0cmluZyBmb3JtYXR0ZWRTZXJ2ZXJMaXN0ID0gVUlVdGlscy5n
ZXRGb3JtYXR0ZWRTZXJ2ZXJMaXN0KHNlcnZlcnMsIHRydWUpOwoJCQkJVUlVdGlscy5zZW5kRW1h
aWwoZm9ybWF0dGVkU2VydmVyTGlzdCwgdXNlckNvbmZpZywgImNoYW5nZVB3ZCIpOwoJCQl9CgkJ
fQoJfQp9IGNhdGNoIChUaHJvd2FibGUgdCkgewoJc3VjY2VzcyA9IGZhbHNlOwoJbWVzc2FnZSA9
IHQuZ2V0TG9jYWxpemVkTWVzc2FnZSgpOwp9IGZpbmFsbHkgewoJVmFsdWVzRW11bGF0b3IucmVt
b3ZlKHBpcGVsaW5lLCAidXNlckluZm8iKTsKCWlmKCFlcnJvck1lc3NhZ2VzLmlzRW1wdHkoKSl7
CgkJbWVzc2FnZSArPSAiICIgKyBlcnJvck1lc3NhZ2VzLnRvU3RyaW5nKCk7Cgl9CglWYWx1ZXNF
bXVsYXRvci5wdXQocGlwZWxpbmUsICJtZXNzYWdlIiwgbWVzc2FnZSk7CglWYWx1ZXNFbXVsYXRv
ci5wdXQocGlwZWxpbmUsICJzdWNjZXNzIiwgU3RyaW5nLnZhbHVlT2Yoc3VjY2VzcykpOwoJVmFs
dWVzRW11bGF0b3IucHV0KHBpcGVsaW5lLCAidXNlcklkIiwgU3RyaW5nLnZhbHVlT2YodXNlckNv
bmZpZy5nZXRJZCgpKSk7Cn0K</value>
</Values>
