<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">listDefaultVFS</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:required subDirectory</value>
    <value>[i] field:0:required filter</value>
    <value>[i] field:0:required maxItems</value>
    <value>[o] field:0:required success</value>
    <value>[o] field:0:required message</value>
    <value>[o] field:1:required directories</value>
  </array>
  <value name="subtype">unknown</value>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">CQlTdHJpbmcgbWVzc2FnZSA9IE1GVFJlc291cmNlcy5nZXRNZXNzYWdlKCIxMDEzIik7CgkJYm9v
bGVhbiBzdWNjZXNzID0gZmFsc2U7CgkJU3RyaW5nIHN1YkRpcmVjdG9yeSA9ICIiOwoJCVN0cmlu
ZyBmaWx0ZXIgPSAiIjsKCQlpbnQgbWF4SXRlbXMgPSAtMTsKCQlMaXN0PFN0cmluZz4gc3ViRGly
cyA9IG5ldyBBcnJheUxpc3Q8PigpOwoJCUlEYXRhW10gZGlyTGlzdCA9IG51bGw7CgkJSURhdGEg
b3V0cHV0ID0gSURhdGFGYWN0b3J5LmNyZWF0ZSgpOwoJCXRyeSB7CgkJCVJCQVByb3h5LnZhbGlk
YXRlU2Vzc2lvbihSQkFVaUhhbmRsZS5WRlNfVVBEQVRFKTsKCQkJSURhdGFDdXJzb3IgaW5jdXIg
PSBwaXBlbGluZS5nZXRDdXJzb3IoKTsKCQkJaWYgKGluY3VyLmZpcnN0KCJzdWJEaXJlY3Rvcnki
KSkgewoJCQkJc3ViRGlyZWN0b3J5ID0gKFN0cmluZykgaW5jdXIuZ2V0VmFsdWUoKTsKCQkJfQoK
CQkJaWYgKGluY3VyLmZpcnN0KCJmaWx0ZXIiKSkgewoJCQkJZmlsdGVyID0gKFN0cmluZykgaW5j
dXIuZ2V0VmFsdWUoKTsKCQkJfQoKCQkJaWYgKGluY3VyLmZpcnN0KCJtYXhJdGVtcyIpKSB7CgkJ
CQl0cnkgewoJCQkJCVN0cmluZyBtYXggPSAoU3RyaW5nKSBpbmN1ci5nZXRWYWx1ZSgpOwoJCQkJ
CWludCBtYXhWYWx1ZSA9IEludGVnZXIudmFsdWVPZihtYXgpOwoJCQkJCWlmIChtYXhWYWx1ZSA+
IDApIHsKCQkJCQkJbWF4SXRlbXMgPSBtYXhWYWx1ZTsKCQkJCQl9CgkJCQl9IGNhdGNoIChFeGNl
cHRpb24gZSkgewoJCQkJfQoJCQl9CgkJCQoJCQlpZiAobnVsbCA9PSBzdWJEaXJlY3RvcnkpIHsK
CQkJCXN1YkRpcmVjdG9yeSA9ICIiOwoJCQl9CgkJCQoJCQlzdWJEaXJlY3RvcnkgPSBBc3NldFV0
aWxzLnNhbml0aXplU3ViRGlyZWN0b3J5U3RyaW5nKHN1YkRpcmVjdG9yeSk7CgkJCQoJCQlzdWJE
aXJzID0gVXNlck1hbmFnZXJQcm94eS5saXN0RGVmYXVsdFZGUyhzdWJEaXJlY3RvcnksIGZpbHRl
ciwgbWF4SXRlbXMpOwoKCQkJLy8gVG8gbWFrZSBpdCBzaW1pbGFyIHRvIHdtLm1mdC51aS5hZG1p
bi5maWxlU3lzdGVtQnJvd3NlKElEYXRhKQoJCQlTb3J0ZWRJRGF0YUxpc3QgbGlzdERpciA9IG5l
dyBTb3J0ZWRJRGF0YUxpc3QoIm5hbWUiKTsKCQkJZmluYWwgU3RyaW5nIGZpbmFsUGF0aCA9IHN1
YkRpcmVjdG9yeS5lbmRzV2l0aCgiLyIpP3N1YkRpcmVjdG9yeTpzdWJEaXJlY3RvcnkrIi8iOyAK
CQkJc3ViRGlycy5mb3JFYWNoKGRpci0+ewoJCQkJaWYgKGRpci5pc0VtcHR5KCkpIHsKCQkJCQly
ZXR1cm47CgkJCQl9CgkJCQlJRGF0YSBpZGF0YSA9IElEYXRhRmFjdG9yeS5jcmVhdGUoKTsKCQkJ
CVZhbHVlc0VtdWxhdG9yLnB1dChpZGF0YSwgIm5hbWUiLCBkaXIpOwoJCQkJVmFsdWVzRW11bGF0
b3IucHV0KGlkYXRhLCAicGF0aCIsIGZpbmFsUGF0aCtkaXIpOwoJCQkJVmFsdWVzRW11bGF0b3Iu
cHV0KGlkYXRhLCAidHlwZSIsICJESVIiKTsKCQkJCWxpc3REaXIuYWRkRWxlbWVudChpZGF0YSk7
CgkJCX0pOwoJCQlkaXJMaXN0ID0gbGlzdERpci5nZXRTb3J0ZWRMaXN0KCk7CgkJCVZhbHVlc0Vt
dWxhdG9yLnB1dChvdXRwdXQsICJmaWxlcyIsIGRpckxpc3QpOwoJCQlzdWNjZXNzID0gdHJ1ZTsK
CQoJCX0gY2F0Y2ggKFRocm93YWJsZSB0KSB7CgkJCW1lc3NhZ2UgPSB0LmdldExvY2FsaXplZE1l
c3NhZ2UoKTsKCQl9IGZpbmFsbHkgewoJCQlWYWx1ZXNFbXVsYXRvci5wdXQocGlwZWxpbmUsICJz
dWNjZXNzIiwgU3RyaW5nLnZhbHVlT2Yoc3VjY2VzcykpOwoJCQlWYWx1ZXNFbXVsYXRvci5wdXQo
cGlwZWxpbmUsICJtZXNzYWdlIiwgbWVzc2FnZSk7CgkJCVZhbHVlc0VtdWxhdG9yLnB1dChwaXBl
bGluZSwgImRpcmVjdG9yaWVzIiwgc3ViRGlycy50b0FycmF5KG5ldyBTdHJpbmdbc3ViRGlycy5z
aXplKCldKSk7CgkJCVZhbHVlc0VtdWxhdG9yLnB1dChwaXBlbGluZSwgIm91dHB1dCIsIG91dHB1
dCk7CgkJfQo=</value>
</Values>
