<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">getShareDetails</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:required shareId</value>
    <value>[o] field:0:required status</value>
    <value>[o] field:0:required message</value>
    <value>[o] record:0:optional share</value>
    <value>[o] - field:0:required shareId</value>
    <value>[o] - field:0:required username</value>
    <value>[o] - field:0:required shareType</value>
    <value>[o] - field:0:required shareName</value>
    <value>[o] - field:0:required shareMessage</value>
    <value>[o] - field:0:required shareItems</value>
    <value>[o] - field:0:required permissions</value>
    <value>[o] - field:0:required vfsConfig</value>
    <value>[o] - field:0:required createdBy</value>
    <value>[o] - field:0:required createdDate</value>
    <value>[o] - field:0:required expiryDate</value>
    <value>[o] - field:0:required status</value>
    <value>[o] - field:0:required accessCount</value>
    <value>[o] - field:0:required downloadCount</value>
    <value>[o] - field:0:required maxDownloads</value>
  </array>
  <value name="subtype">unknown</value>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">CklEYXRhQ3Vyc29yIGN1cnNvciA9IG51bGw7CmJvb2xlYW4gc3VjY2VzcyA9IHRydWU7ClN0cmlu
ZyBtZXNzYWdlID0gIiI7CklEYXRhIHNoYXJlRGF0YSA9IG51bGw7Cgp0cnkgewogICAgY3Vyc29y
ID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7CiAgICAKICAgIC8vIEdldCBzaGFyZUlkIGZyb20gaW5w
dXQKICAgIFN0cmluZyBzaGFyZUlkID0gVmFsdWVzRW11bGF0b3IuZ2V0U3RyaW5nKHBpcGVsaW5l
LCAic2hhcmVJZCIpOwogICAgCiAgICBpZiAoc2hhcmVJZCA9PSBudWxsIHx8IHNoYXJlSWQudHJp
bSgpLmlzRW1wdHkoKSkgewogICAgICAgIHRocm93IG5ldyBFeGNlcHRpb24oInNoYXJlSWQgaXMg
cmVxdWlyZWQiKTsKICAgIH0KICAgIAogICAgLy8gR2V0IHNoYXJlIGZyb20gZGF0YWJhc2UgLSBy
ZXR1cm5zIE1hcDxTdHJpbmcsIE9iamVjdD4KICAgIE1hcDxTdHJpbmcsIE9iamVjdD4gc2hhcmVP
YmogPSAoTWFwPFN0cmluZywgT2JqZWN0PikgU2hhcmVQcm94eS5nZXRTaGFyZUJ5SWQoc2hhcmVJ
ZCk7CiAgICAKICAgIGlmIChzaGFyZU9iaiAhPSBudWxsKSB7CiAgICAgICAgc2hhcmVEYXRhID0g
SURhdGFGYWN0b3J5LmNyZWF0ZSgpOwogICAgICAgIElEYXRhQ3Vyc29yIHNoYXJlQ3Vyc29yID0g
c2hhcmVEYXRhLmdldEN1cnNvcigpOwogICAgICAgIFNpbXBsZURhdGVGb3JtYXQgZGF0ZUZvcm1h
dCA9IG5ldyBTaW1wbGVEYXRlRm9ybWF0KCJ5eXl5LU1NLWRkIEhIOm1tOnNzIik7CiAgICAgICAg
CiAgICAgICAgc2hhcmVDdXJzb3IuaW5zZXJ0QWZ0ZXIoInNoYXJlSWQiLCAoU3RyaW5nKSBzaGFy
ZU9iai5nZXQoInNoYXJlSWQiKSk7CiAgICAgICAgc2hhcmVDdXJzb3IuaW5zZXJ0QWZ0ZXIoInVz
ZXJuYW1lIiwgKFN0cmluZykgc2hhcmVPYmouZ2V0KCJ1c2VybmFtZSIpKTsKICAgICAgICBzaGFy
ZUN1cnNvci5pbnNlcnRBZnRlcigic2hhcmVUeXBlIiwgKFN0cmluZykgc2hhcmVPYmouZ2V0KCJz
aGFyZVR5cGUiKSk7CiAgICAgICAgc2hhcmVDdXJzb3IuaW5zZXJ0QWZ0ZXIoInNoYXJlTmFtZSIs
IHNoYXJlT2JqLmdldCgic2hhcmVOYW1lIikgIT0gbnVsbCA/IChTdHJpbmcpIHNoYXJlT2JqLmdl
dCgic2hhcmVOYW1lIikgOiAiIik7CiAgICAgICAgc2hhcmVDdXJzb3IuaW5zZXJ0QWZ0ZXIoInNo
YXJlTWVzc2FnZSIsIHNoYXJlT2JqLmdldCgic2hhcmVNZXNzYWdlIikgIT0gbnVsbCA/IChTdHJp
bmcpIHNoYXJlT2JqLmdldCgic2hhcmVNZXNzYWdlIikgOiAiIik7CiAgICAgICAgc2hhcmVDdXJz
b3IuaW5zZXJ0QWZ0ZXIoInNoYXJlSXRlbXMiLCBzaGFyZU9iai5nZXQoInNoYXJlSXRlbXMiKSAh
PSBudWxsID8gKFN0cmluZykgc2hhcmVPYmouZ2V0KCJzaGFyZUl0ZW1zIikgOiAiW10iKTsKICAg
ICAgICBzaGFyZUN1cnNvci5pbnNlcnRBZnRlcigicGVybWlzc2lvbnMiLCBzaGFyZU9iai5nZXQo
InBlcm1pc3Npb25zIikgIT0gbnVsbCA/IChTdHJpbmcpIHNoYXJlT2JqLmdldCgicGVybWlzc2lv
bnMiKSA6ICJ7fSIpOwogICAgICAgIHNoYXJlQ3Vyc29yLmluc2VydEFmdGVyKCJ2ZnNDb25maWci
LCBzaGFyZU9iai5nZXQoInZmc0NvbmZpZyIpICE9IG51bGwgPyAoU3RyaW5nKSBzaGFyZU9iai5n
ZXQoInZmc0NvbmZpZyIpIDogInt9Iik7CiAgICAgICAgc2hhcmVDdXJzb3IuaW5zZXJ0QWZ0ZXIo
ImNyZWF0ZWRCeSIsIChTdHJpbmcpIHNoYXJlT2JqLmdldCgiY3JlYXRlZEJ5IikpOwogICAgICAg
IGphdmEudXRpbC5EYXRlIGNyZWF0ZWREYXRlID0gKGphdmEudXRpbC5EYXRlKSBzaGFyZU9iai5n
ZXQoImNyZWF0ZWREYXRlIik7CiAgICAgICAgc2hhcmVDdXJzb3IuaW5zZXJ0QWZ0ZXIoImNyZWF0
ZWREYXRlIiwgY3JlYXRlZERhdGUgIT0gbnVsbCA/IGRhdGVGb3JtYXQuZm9ybWF0KGNyZWF0ZWRE
YXRlKSA6ICIiKTsKICAgICAgICBzaGFyZUN1cnNvci5pbnNlcnRBZnRlcigiY3JlYXRlZERhdGVF
cG9jaCIsIGNyZWF0ZWREYXRlICE9IG51bGwgPyBTdHJpbmcudmFsdWVPZihjcmVhdGVkRGF0ZS5n
ZXRUaW1lKCkpIDogIiIpOwogICAgICAgIGphdmEudXRpbC5EYXRlIGV4cGlyeURhdGUgPSAoamF2
YS51dGlsLkRhdGUpIHNoYXJlT2JqLmdldCgiZXhwaXJ5RGF0ZSIpOwogICAgICAgIHNoYXJlQ3Vy
c29yLmluc2VydEFmdGVyKCJleHBpcnlEYXRlIiwgZXhwaXJ5RGF0ZSAhPSBudWxsID8gZGF0ZUZv
cm1hdC5mb3JtYXQoZXhwaXJ5RGF0ZSkgOiAiIik7CiAgICAgICAgc2hhcmVDdXJzb3IuaW5zZXJ0
QWZ0ZXIoImV4cGlyeURhdGVFcG9jaCIsIGV4cGlyeURhdGUgIT0gbnVsbCA/IFN0cmluZy52YWx1
ZU9mKGV4cGlyeURhdGUuZ2V0VGltZSgpKSA6ICIiKTsKICAgICAgICBzaGFyZUN1cnNvci5pbnNl
cnRBZnRlcigic2hhcmVTdGF0dXMiLCAoU3RyaW5nKSBzaGFyZU9iai5nZXQoInN0YXR1cyIpKTsK
ICAgICAgICBzaGFyZUN1cnNvci5pbnNlcnRBZnRlcigiYWNjZXNzQ291bnQiLCBTdHJpbmcudmFs
dWVPZihzaGFyZU9iai5nZXQoImFjY2Vzc0NvdW50IikpKTsKICAgICAgICBzaGFyZUN1cnNvci5p
bnNlcnRBZnRlcigiZG93bmxvYWRDb3VudCIsIFN0cmluZy52YWx1ZU9mKHNoYXJlT2JqLmdldCgi
ZG93bmxvYWRDb3VudCIpKSk7CiAgICAgICAgSW50ZWdlciBtYXhEb3dubG9hZHMgPSAoSW50ZWdl
cikgc2hhcmVPYmouZ2V0KCJtYXhEb3dubG9hZHMiKTsKICAgICAgICBzaGFyZUN1cnNvci5pbnNl
cnRBZnRlcigibWF4RG93bmxvYWRzIiwgbWF4RG93bmxvYWRzICE9IG51bGwgPyBTdHJpbmcudmFs
dWVPZihtYXhEb3dubG9hZHMpIDogInVubGltaXRlZCIpOwogICAgICAgIHNoYXJlQ3Vyc29yLmlu
c2VydEFmdGVyKCJzaGFyZWRGcm9tTWFpbCIsIHNoYXJlT2JqLmdldCgic2hhcmVkRnJvbU1haWwi
KSAhPSBudWxsID8gKFN0cmluZykgc2hhcmVPYmouZ2V0KCJzaGFyZWRGcm9tTWFpbCIpIDogIiIp
OwogICAgICAgIHNoYXJlQ3Vyc29yLmluc2VydEFmdGVyKCJzaGFyZWRUb01haWwiLCBzaGFyZU9i
ai5nZXQoInNoYXJlZFRvTWFpbCIpICE9IG51bGwgPyAoU3RyaW5nKSBzaGFyZU9iai5nZXQoInNo
YXJlZFRvTWFpbCIpIDogIiIpOwogICAgICAgIAogICAgICAgIHNoYXJlQ3Vyc29yLmRlc3Ryb3ko
KTsKICAgICAgICBtZXNzYWdlID0gIlNoYXJlIGRldGFpbHMgcmV0cmlldmVkIHN1Y2Nlc3NmdWxs
eSI7CiAgICB9IGVsc2UgewogICAgICAgIHN1Y2Nlc3MgPSBmYWxzZTsKICAgICAgICBtZXNzYWdl
ID0gIlNoYXJlIG5vdCBmb3VuZCI7CiAgICB9CiAgICAKfSBjYXRjaCAoVGhyb3dhYmxlIHQpIHsK
ICAgIHN1Y2Nlc3MgPSBmYWxzZTsKICAgIG1lc3NhZ2UgPSAiRmFpbGVkIHRvIHJldHJpZXZlIHNo
YXJlIGRldGFpbHM6ICIgKyB0LmdldExvY2FsaXplZE1lc3NhZ2UoKTsKfSBmaW5hbGx5IHsKICAg
IGlmIChjdXJzb3IgIT0gbnVsbCkgewogICAgICAgIGN1cnNvci5pbnNlcnRBZnRlcigic3RhdHVz
Iiwgc3VjY2VzcyA/ICJzdWNjZXNzIiA6ICJmYWlsdXJlIik7CiAgICAgICAgY3Vyc29yLmluc2Vy
dEFmdGVyKCJtZXNzYWdlIiwgbWVzc2FnZSk7CiAgICAgICAgaWYgKHNoYXJlRGF0YSAhPSBudWxs
KSB7CiAgICAgICAgICAgIGN1cnNvci5pbnNlcnRBZnRlcigic2hhcmUiLCBzaGFyZURhdGEpOwog
ICAgICAgIH0KICAgICAgICBjdXJzb3IuZGVzdHJveSgpOwogICAgfQp9Cg==</value>
</Values>
