monitorInterval=60

appender.activetransfer.type=RollingFile
appender.activetransfer.name=ActiveTransfer.RollingLogFile
appender.activetransfer.fileName=logs/ActiveTransfer.log
appender.activetransfer.filePattern=logs/ActiveTransfer-%i.log.gz
appender.activetransfer.layout.type=PatternLayout
appender.activetransfer.layout.pattern=%d{DEFAULT} %-5p [%-40.60c{10}][%scgMsgKey] - %m%n
appender.activetransfer.policies.type=Policies
appender.activetransfer.policies.size.type=SizeBasedTriggeringPolicy
appender.activetransfer.policies.size.size=10MB
appender.activetransfer.strategy.type=DefaultRolloverStrategy
appender.activetransfer.strategy.max=10

appender.activetransferui.type=RollingFile
appender.activetransferui.name=ActiveTransferUI.RollingLogFile
appender.activetransferui.fileName=logs/ActiveTransferUI.log
appender.activetransferui.filePattern=logs/ActiveTransferUI-%i.log.gz
appender.activetransferui.layout.type=PatternLayout
appender.activetransferui.layout.pattern=%d{DEFAULT} %-5p [%-40.60c{10}][%scgMsgKey] - %m%n
appender.activetransferui.policies.type=Policies
appender.activetransferui.policies.size.type=SizeBasedTriggeringPolicy
appender.activetransferui.policies.size.size=10MB
appender.activetransferui.strategy.type=DefaultRolloverStrategy
appender.activetransferui.strategy.max=10

appender.maverick.type=RollingFile
appender.maverick.name=maverick.RollingLogFile
appender.maverick.fileName=logs/Maverick.log
appender.maverick.filePattern=logs/Maverick-%i.log.gz
appender.maverick.layout.type=PatternLayout
appender.maverick.layout.pattern=%d{DEFAULT} %-5p [%-40.60c{10}] - %m%n
appender.maverick.policies.type=Policies
appender.maverick.policies.size.type=SizeBasedTriggeringPolicy
appender.maverick.policies.size.size=10MB
appender.maverick.strategy.type=DefaultRolloverStrategy
appender.maverick.strategy.max=10


logger.activeTransfer.name=com.webmethods.mft
logger.activeTransfer.level=info
logger.activeTransfer.additivity=false
logger.activeTransfer.appenderRef.activetransfer.ref=ActiveTransfer.RollingLogFile

logger.activeTransfer.name=com.webmethods.mft.common
logger.activeTransfer.level=info
logger.activeTransfer.additivity=false
logger.activeTransfer.appenderRef.activetransfer.ref=ActiveTransfer.RollingLogFile

logger.springsec.name=org.springframework.security
logger.springsec.level=trace
logger.springsec.additivity=false
logger.springsec.appenderRef.activetransfer.ref=ActiveTransfer.RollingLogFile

logger.activetransferui.name=com.webmethods.mft.ui
logger.activetransferui.level=info
logger.activetransferui.additivity=false
logger.activetransferui.appenderRef.activetransfer.ref=ActiveTransferUI.RollingLogFile


logger.fileretention.name=com.webmethods.mft.retention.FilePurgeProcessor
logger.fileretention.level=info
logger.fileretention.additivity=false
logger.fileretention.appenderRef.activetransfer.ref=ActiveTransfer.RollingLogFile

logger.maverick.name=com.maverick
logger.maverick.level=info
logger.maverick.additivity=false
logger.maverick.appenderRef.activetransfer.ref=maverick.RollingLogFile

logger.sshtools.name=com.sshtools
logger.sshtools.level=info
logger.sshtools.additivity=false
logger.sshtools.appenderRef.activetransfer.ref=maverick.RollingLogFile