<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">validate</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:required dirServiceName</value>
    <value>[i] field:1:required properties</value>
    <value>[i] field:2:required serviceEnabled</value>
    <value>[o] record:0:required output</value>
    <value>[o] - field:0:required success</value>
    <value>[o] - field:0:required message</value>
  </array>
  <value name="subtype">unknown</value>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">CklEYXRhIG91dHB1dCA9IElEYXRhRmFjdG9yeS5jcmVhdGUoKTsKSURhdGFDdXJzb3IgY3VyID0g
cGlwZWxpbmUuZ2V0Q3Vyc29yKCk7Ck1GVFVzZXJEaXJlY3RvcnkgdXNlckRpcmVjdG9yeSA9IG5l
dyBNRlRVc2VyRGlyZWN0b3J5KCk7ClByb3BlcnRpZXMgcHJvcGVydGllcyA9IG5ldyBQcm9wZXJ0
aWVzKCk7CnRyeSB7CiAgICBpZiAoY3VyLmZpcnN0KCJkaXJTZXJ2aWNlTmFtZSIpKSB7CiAgICAg
ICAgdXNlckRpcmVjdG9yeS5zZXREaXJTZXJ2aWNlTmFtZSgoU3RyaW5nKSBjdXIuZ2V0VmFsdWUo
KSk7CiAgICB9CgogICAgaWYgKGN1ci5maXJzdCgic2VydmljZUVuYWJsZWQiKSkgewogICAgICAg
IHVzZXJEaXJlY3Rvcnkuc2V0U2VydmljZUVuYWJsZWQoKGJvb2xlYW4pIGN1ci5nZXRWYWx1ZSgp
KTsKICAgIH0KCiAgICBpZiAoY3VyLmZpcnN0KCJwcm9wZXJ0aWVzIikpIHsKICAgICAgICBJRGF0
YSBwcm9wcyA9IChJRGF0YSkgY3VyLmdldFZhbHVlKCk7CiAgICAgICAgSURhdGFDdXJzb3IgcHJv
cHNDdXIgPSBwcm9wcy5nZXRDdXJzb3IoKTsKICAgICAgICB3aGlsZSAocHJvcHNDdXIubmV4dCgp
KSB7CiAgICAgICAgICAgIHByb3BlcnRpZXMucHV0KHByb3BzQ3VyLmdldEtleSgpLCBwcm9wc0N1
ci5nZXRWYWx1ZSgpKTsKICAgICAgICB9CiAgICAgICAgU3RyaW5nIGNsaWVudFNlYyA9IHByb3Bl
cnRpZXMuZ2V0UHJvcGVydHkoImNsaWVudFNlY3JldCIpOwogICAgICAgIGlmIChjbGllbnRTZWMg
IT0gbnVsbCAmJiBjbGllbnRTZWMuZXF1YWxzKCIqKioqKioqKioqKioqKioqIikpIHsKICAgICAg
ICAgICAgUHJvcGVydGllcyBwcm9wZXJ0aWVzMSA9IFNlcnZlckFkbWluUHJveHkudmlld1VzZXJE
aXJlY3RvcnkodXNlckRpcmVjdG9yeS5nZXREaXJTZXJ2aWNlTmFtZSgpKS5nZXRQcm9wZXJ0aWVz
KCk7CiAgICAgICAgICAgIFN0cmluZyBvbGRDbGllbnRTZWNyZXQgPSBwcm9wZXJ0aWVzMS5nZXRQ
cm9wZXJ0eSgiY2xpZW50U2VjcmV0Iik7CiAgICAgICAgICAgIGlmIChvbGRDbGllbnRTZWNyZXQg
IT0gbnVsbCkgewogICAgICAgICAgICAgICAgcHJvcGVydGllcy5yZXBsYWNlKCJjbGllbnRTZWNy
ZXQiLCAiKioqKioqKioqKioqKioqKiIsIG9sZENsaWVudFNlY3JldCk7CiAgICAgICAgICAgIH0K
ICAgICAgICB9CiAgICAgICAgdXNlckRpcmVjdG9yeS5zZXRQcm9wZXJ0aWVzKHByb3BlcnRpZXMp
OwogICAgfQogICAgUkJBUHJveHkudmFsaWRhdGVTZXNzaW9uKFJCQVVpSGFuZGxlLlNFVFRJTkdT
X1VTRVJfRElSRUNUT1JZX1ZJRVcpOwogICAgYm9vbGVhbiB0b2tlbiA9IGZhbHNlOwogICAgaWYg
KHVzZXJEaXJlY3RvcnkgIT0gbnVsbCkgewogICAgICAgIHRva2VuID0gVXNlck1hbmFnZXJQcm94
eS52YWxpZGF0ZSh1c2VyRGlyZWN0b3J5KTsKICAgIH0KICAgIGlmICghdG9rZW4pIHsKICAgICAg
ICB0aHJvdyBuZXcgRXhjZXB0aW9uKCJJbnZhbGlkIGNyZWRlbnRpYWxzIik7CiAgICB9CiAgICBW
YWx1ZXNFbXVsYXRvci5wdXQob3V0cHV0LCAic3VjY2VzcyIsIHRydWUpOwoKfSBjYXRjaCAoVGhy
b3dhYmxlIGUpIHsKICAgIFZhbHVlc0VtdWxhdG9yLnB1dChwaXBlbGluZSwgIm1lc3NhZ2UiLCBl
LmdldExvY2FsaXplZE1lc3NhZ2UoKSk7CiAgICBWYWx1ZXNFbXVsYXRvci5wdXQocGlwZWxpbmUs
ICJzdWNjZXNzIiwgZmFsc2UpOwp9IGZpbmFsbHkgewoJVmFsdWVzRW11bGF0b3IucmVtb3ZlKHBp
cGVsaW5lLCAicHJvcGVydGllcyIpOwogICAgVmFsdWVzRW11bGF0b3IucHV0KHBpcGVsaW5lLCAi
b3V0cHV0Iiwgb3V0cHV0KTsKfQo=</value>
</Values>
