<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">add</value>
  <array name="sig" type="value" depth="1">
    <value>[i] recref:0:required templateInfo wm.mft.assets.rec.event:ActionTemplate</value>
    <value>[o] field:0:required success</value>
    <value>[o] field:0:optional templateId</value>
    <value>[o] field:0:required message</value>
    <value>[o] field:1:required validationErrors</value>
  </array>
  <value name="subtype">unknown</value>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">IApTdHJpbmcgbWVzc2FnZSA9IE1GVFJlc291cmNlcy5nZXRNZXNzYWdlKCIxMDEzIik7CklEYXRh
Q3Vyc29yIGN1ciA9IHBpcGVsaW5lLmdldEN1cnNvcigpOwpTdHJpbmcgdGVtcGxhdGVJZCA9ICIi
OwpJRGF0YSB0ZW1wbGF0ZVBpcGUgPSAoSURhdGEpIFZhbHVlc0VtdWxhdG9yLmdldChwaXBlbGlu
ZSwgInRlbXBsYXRlSW5mbyIpOwpib29sZWFuIHZhbGlkYXRlSW5wdXQgPSB0cnVlOwppZiAoICJm
YWxzZSIuZXF1YWxzSWdub3JlQ2FzZShWYWx1ZXNFbXVsYXRvci5nZXRTdHJpbmcocGlwZWxpbmUs
ICJ2YWxpZGF0ZUlucHV0IikpICkgewogICAgdmFsaWRhdGVJbnB1dCA9IGZhbHNlOwp9CkFjdGlv
blRlbXBsYXRlIHRlbXBsYXRlID0gbnVsbDsKCmJvb2xlYW4gc3VjY2VzcyA9IGZhbHNlOwpTdHJp
bmdbXSBtZXNzYWdlQXJyYXkgPSBudWxsOwp0cnl7CiAgICBpZiAoIHRlbXBsYXRlUGlwZSA9PSBu
dWxsICkKICAgICAgICB0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbihNRlRSZXNvdXJjZXMuZ2V0
TWVzc2FnZSgiMTAwMSIsICJ0ZW1wbGF0ZUluZm8iKSk7CiAgICB0ZW1wbGF0ZSA9IEFzc2V0VXRp
bHMuZ2V0QWN0aW9uVGVtcGxhdGVGcm9tSURhdGEodGVtcGxhdGVQaXBlKTsKICAgIGlmICggdGVt
cGxhdGUuZ2V0TmFtZSgpICE9IG51bGwgJiYgdGVtcGxhdGUuZ2V0TmFtZSgpLmxlbmd0aCgpID4g
MjU1ICkgewogICAgICAgIHRocm93IG5ldyBTZXJ2aWNlRXhjZXB0aW9uKE1GVFJlc291cmNlcy5n
ZXRNZXNzYWdlKCI4MTA1IikpOwogICAgfQogICAgaWYgKCB0ZW1wbGF0ZS5nZXREZXNjcmlwdGlv
bigpICE9IG51bGwgJiYgdGVtcGxhdGUuZ2V0RGVzY3JpcHRpb24oKS5sZW5ndGgoKSA+IDI1NiAp
IHsKICAgICAgICB0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbihNRlRSZXNvdXJjZXMuZ2V0TWVz
c2FnZSgiODEwNCIpKTsKICAgIH0KICAgIHRlbXBsYXRlSWQgPSBFdmVudHNQcm94eS5hZGRBY3Rp
b25UZW1wbGF0ZSh0ZW1wbGF0ZSk7CiAgICBzdWNjZXNzID0gdHJ1ZTsKfWNhdGNoIChUaHJvd2Fi
bGUgdCl7CiAgICBtZXNzYWdlID0gdC5nZXRMb2NhbGl6ZWRNZXNzYWdlKCk7CiAgICBpZiAoIHQg
aW5zdGFuY2VvZiBNRlRTZXJ2aWNlRXhjZXB0aW9uICkgewogICAgICAgIExpc3Q8U3RyaW5nPiBt
ZXNzYWdlTGlzdCA9ICgoTUZUU2VydmljZUV4Y2VwdGlvbikgdCkuZ2V0RXJyb3JNZXNzYWdlTGlz
dCgpOwogICAgICAgIGlmICggbWVzc2FnZUxpc3QgIT0gbnVsbCApIHsKICAgICAgICAgICAgbWVz
c2FnZUFycmF5ID0gbmV3IFN0cmluZ1ttZXNzYWdlTGlzdC5zaXplKCldOwogICAgICAgICAgICBt
ZXNzYWdlTGlzdC50b0FycmF5KG1lc3NhZ2VBcnJheSk7CiAgICAgICAgfQogICAgfQp9ZmluYWxs
eSB7CiAgICBWYWx1ZXNFbXVsYXRvci5wdXQocGlwZWxpbmUsICJzdWNjZXNzIiwgU3RyaW5nLnZh
bHVlT2Yoc3VjY2VzcykpOwogICAgVmFsdWVzRW11bGF0b3IucHV0KHBpcGVsaW5lLCJ0ZW1wbGF0
ZUlkIiwgdGVtcGxhdGVJZCk7CiAgICBWYWx1ZXNFbXVsYXRvci5wdXQocGlwZWxpbmUsIm1lc3Nh
Z2UiLG1lc3NhZ2UpOwogICAgaWYgKCBtZXNzYWdlQXJyYXkgIT0gbnVsbCApCiAgICAgICAgVmFs
dWVzRW11bGF0b3IucHV0KHBpcGVsaW5lLCAidmFsaWRhdGlvbkVycm9ycyIsbWVzc2FnZUFycmF5
KTsKICAgIGlmIChjdXIgIT0gbnVsbCl7CiAgICAgICAgY3VyLmRlc3Ryb3koKTsKICAgIH0KfQo=
</value>
</Values>
