<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">add</value>
  <array name="sig" type="value" depth="1">
    <value>[i] recref:0:required portInfo wm.mft.assets.rec.port:PortInfo</value>
    <value>[o] field:0:required success</value>
    <value>[o] field:0:optional portId</value>
    <value>[o] field:0:required message</value>
    <value>[o] field:1:required validationErrors</value>
  </array>
  <value name="subtype">unknown</value>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">CQkKCQlTdHJpbmcgbWVzc2FnZSA9IE1GVFJlc291cmNlcy5nZXRNZXNzYWdlKCIxMDEzIik7CgkJ
Ly9DcmVhdGluZyBhIG5ldyBTZXJ2ZXJDb25maWcsIHdoZXJlYXMgaW4gY2FzZSBvZiB1cGRhdGUg
d2lsbCByZXRyaWV2ZSB0aGUgZXhpc3Rpbmcgb25lLgoJCVNlcnZlckNvbmZpZyBjb25maWcgPSBu
ZXcgU2VydmVyQ29uZmlnKCk7CgkJSURhdGFDdXJzb3IgaW5jdXIgPSBwaXBlbGluZS5nZXRDdXJz
b3IoKTsKCQkKCQlJRGF0YSBzZXJ2ZXJDb25maWdQaXBlID0gbnVsbDsKCQlpZihpbmN1ci5maXJz
dCgicG9ydEluZm8iKSl7CgkJCXNlcnZlckNvbmZpZ1BpcGUgPSAoSURhdGEpaW5jdXIuZ2V0VmFs
dWUoKTsKCQl9CgkJaWYobnVsbCA9PSBzZXJ2ZXJDb25maWdQaXBlKXsKCQkJdGhyb3cgbmV3IFNl
cnZpY2VFeGNlcHRpb24oTUZUUmVzb3VyY2VzLmdldE1lc3NhZ2UoIjEwMDEiLCAicG9ydEluZm8i
KSk7CgkJfQoJCQoJCQoJCVN0cmluZyBzZXJ2ZXJJZCA9IG51bGw7CgkJYm9vbGVhbiBzdWNjZXNz
ID0gZmFsc2U7CgkJU3RyaW5nW10gbWVzc2FnZUFycmF5ID0gbnVsbDsKCQl0cnl7CgkJCWNvbmZp
ZyA9IEFzc2V0VXRpbHMuZ2V0U2VydmVyQ29uZmlnKHNlcnZlckNvbmZpZ1BpcGUsY29uZmlnKTsK
CQkJCgkJCWlmICggISBBc3NldFV0aWxzLmlzVmFsaWRQb3J0TmFtZShjb25maWcuZ2V0U2VydmVy
TmFtZSgpKSApIHsKCQkJCXRocm93IG5ldyBTZXJ2aWNlRXhjZXB0aW9uKE1GVFJlc291cmNlcy5n
ZXRNZXNzYWdlKCIxMTA2IiwgY29uZmlnLmdldFNlcnZlck5hbWUoKSkpOwoJCQl9CgkJCQoJCQlp
ZiAoQXNzZXRVdGlscy5pc1NpbmdsZVNpZ25PblJlcXVpcmVDbGllbnRDZXJ0KGNvbmZpZykpIHsK
CQkJCXRocm93IG5ldyBTZXJ2aWNlRXhjZXB0aW9uKE1GVFJlc291cmNlcy5nZXRNZXNzYWdlKCIx
MTA3IiwgY29uZmlnLmdldFNlcnZlck5hbWUoKSkpOwoJCQl9CgkJCQoJCQlTZXJ2ZXJGVFBEZXRh
aWxzIGZ0cERldGFpbHMgPSBjb25maWcuZ2V0U2VydmVyRlRQRGV0YWlscygpOwoJCQlpZiAoZnRw
RGV0YWlscyAhPSBudWxsKXsKCQkJCWlmIChmdHBEZXRhaWxzLmlzRW5jcnlwdGlvblJlcXVpcmVk
KCl8fAoJCQkJZnRwRGV0YWlscy5pc0V4cGxpY2l0U1NMKCl8fAoJCQkJZnRwRGV0YWlscy5pc0V4
cGxpY2l0VExTKCl8fAoJCQkJZnRwRGV0YWlscy5pc0ltcGxpY2l0RlRQKCl8fAoJCQkJZnRwRGV0
YWlscy5pc1NlY3VyZURhdGFDaGFubmVsKCkpIHsKCQkJCQljb25maWcuc2V0UHJvdG9jb2woIkZU
UFMiKTsJCgkJCQl9CgkJCX0gZWxzZSBpZiAoIkZUUCIuZXF1YWxzSWdub3JlQ2FzZShjb25maWcu
Z2V0UHJvdG9jb2woKSkgJiYgY29uZmlnLmdldFNlcnZlckRldGFpbHMoKSAhPSBudWxsCgkJCQkJ
JiYgKGNvbmZpZy5nZXRTZXJ2ZXJEZXRhaWxzKCkuaXNDbGllbnRDZXJ0UmVxdWlyZWQoKQoJCQkJ
CQkJfHxjb25maWcuZ2V0U2VydmVyRGV0YWlscygpLmlzQ2xpZW50Q2VydEFuZFBhc3N3b3JkUmVx
dWlyZWQoKSkpewoJCQkJY29uZmlnLnNldFByb3RvY29sKCJGVFBTIik7CQoJCQl9CgkJCWNvbmZp
Zy5zZXRTZXJ2ZXJJRChudWxsKTsKCQkJc2VydmVySWQgPSBTZXJ2ZXJBZG1pblByb3h5LmFkZFNl
cnZlcihjb25maWcpOwoKCQkJc3VjY2VzcyA9IChzZXJ2ZXJJZCE9bnVsbCk7CgkJCgkJfWNhdGNo
IChUaHJvd2FibGUgdCl7CgkgICAgCW1lc3NhZ2UgPSB0LmdldExvY2FsaXplZE1lc3NhZ2UoKTsK
CSAgICAJaWYgKCB0IGluc3RhbmNlb2YgTUZUU2VydmljZUV4Y2VwdGlvbiApIHsKCSAgICAJCUxp
c3Q8U3RyaW5nPiBtZXNzYWdlTGlzdCA9ICgoTUZUU2VydmljZUV4Y2VwdGlvbikgdCkuZ2V0RXJy
b3JNZXNzYWdlTGlzdCgpOwoJICAgIAkJaWYgKCBtZXNzYWdlTGlzdCAhPSBudWxsICkgewoJICAg
IAkJCW1lc3NhZ2VBcnJheSA9IG5ldyBTdHJpbmdbbWVzc2FnZUxpc3Quc2l6ZSgpXTsgCgkgICAg
CQkJbWVzc2FnZUxpc3QudG9BcnJheShtZXNzYWdlQXJyYXkpOwoJICAgIAkJfQoJCQl9CgkgICAg
fWZpbmFsbHkgewoJICAgIAlpZihudWxsID09IHNlcnZlcklkKXsKCSAgICAJCXNlcnZlcklkID0g
IiI7CgkgICAgCX0KCSAgICAJVmFsdWVzRW11bGF0b3IucHV0KHBpcGVsaW5lLCAic3VjY2VzcyIs
IFN0cmluZy52YWx1ZU9mKHN1Y2Nlc3MpKTsKCSAgICAJVmFsdWVzRW11bGF0b3IucHV0KHBpcGVs
aW5lLCAicG9ydElkIiwgc2VydmVySWQpOwoJICAgIAlWYWx1ZXNFbXVsYXRvci5wdXQocGlwZWxp
bmUsICJtZXNzYWdlIiwgbWVzc2FnZSk7CgkgICAgCWlmKG51bGwhPW1lc3NhZ2VBcnJheSl7Cgkg
ICAgCQlWYWx1ZXNFbXVsYXRvci5wdXQocGlwZWxpbmUsICJ2YWxpZGF0aW9uRXJyb3JzIiwgbWVz
c2FnZUFycmF5KTsKCSAgICAJfQoJICAgIH0K</value>
</Values>
