<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">getListingInfo</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:optional dir</value>
    <value>[i] field:0:optional filesIncluded</value>
    <value>[i] field:0:required Locale</value>
    <value>[o] record:0:required output</value>
    <value>[o] - record:1:required files</value>
    <value>[o] -- field:0:required name</value>
    <value>[o] -- field:0:required path</value>
    <value>[o] -- field:0:required type</value>
    <value>[o] - recref:0:optional svcResponse wm.mft.portal.rec:svcResponse</value>
  </array>
  <value name="subtype">unknown</value>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">CQkKCSAgICBJRGF0YUN1cnNvciBjdXIgPSBudWxsOwoJICAgIFN0cmluZyBkaXIgPSBudWxsOwoJ
ICAgIFN0cmluZyBmaWxlc0luY2x1ZGVkID0gbnVsbDsKICAgICAgICBJRGF0YSBvdXRwdXQgPSBJ
RGF0YUZhY3RvcnkuY3JlYXRlKCk7IAoJCUlEYXRhIHN2Y1Jlc3AgPSBudWxsOwoJCVN0cmluZyBz
dmNOYW1lID0gIndtLm1mdC5wb3J0YWwuc2VydmVyOmdldExpc3RpbmdJbmZvIjsKCQlWZWN0b3Ig
bGlzdGluZyA9IG51bGw7CgkJU29ydGVkSURhdGFMaXN0IGxpc3REaXIgPSBuZXcgU29ydGVkSURh
dGFMaXN0KCJuYW1lIik7CgkJU29ydGVkSURhdGFMaXN0IGxpc3RGaWxlID0gbmV3IFNvcnRlZElE
YXRhTGlzdCgibmFtZSIpOwoJCXRyeSB7CgkgICAgCWN1ciA9IHBpcGVsaW5lLmdldEN1cnNvcigp
OwoJICAgIAlpZiAoIGN1ci5maXJzdCAoICJkaXIiICkgKXsKCSAgICAJCWRpciA9IChTdHJpbmcp
Y3VyLmdldFZhbHVlKCk7IAoJICAgIAl9CgkgICAgCWlmICggY3VyLmZpcnN0ICggImZpbGVzSW5j
bHVkZWQiICkgKXsKCSAgICAJCWZpbGVzSW5jbHVkZWQgPSAoU3RyaW5nKWN1ci5nZXRWYWx1ZSgp
OyAKCSAgICAJfQoJICAgIAlQcm9wZXJ0aWVzIHByb3BzID0gVXNlck1hbmFnZXJQcm94eS5nZXRM
aXN0aW5nSW5mbyhkaXIpOwoJICAgIAlpZihwcm9wcyAhPSBudWxsKXsKCSAgICAJCWxpc3Rpbmcg
PSAoVmVjdG9yKXByb3BzLmdldCgibGlzdGluZyIpOwoJICAgIAkJaWYobGlzdGluZyAhPSBudWxs
KXsKCSAgICAJCQlJdGVyYXRvciBpdHIgPSBsaXN0aW5nLml0ZXJhdG9yKCk7CgkgICAgCQkJd2hp
bGUoaXRyLmhhc05leHQoKSl7CgkgICAgCQkJCVByb3BlcnRpZXMgcHJvcCA9IChQcm9wZXJ0aWVz
KWl0ci5uZXh0KCk7CgkgICAgCQkJCWlmKHByb3AgIT0gbnVsbCl7CgkgICAgCQkgICAgCQlJRGF0
YSBpZGF0YSA9IElEYXRhRmFjdG9yeS5jcmVhdGUoKTsKCSAgICAJCSAgICAJCVZhbHVlc0VtdWxh
dG9yLnB1dChpZGF0YSwgIm5hbWUiLCBwcm9wLmdldCgibmFtZSIpKTsKCSAgICAJCSAgICAJCVZh
bHVlc0VtdWxhdG9yLnB1dChpZGF0YSwgInBhdGgiLCBwcm9wLmdldCgiaHJlZl9wYXRoIikpOwoJ
ICAgIAkJICAgIAkJU3RyaW5nIHR5cGUgPSAoU3RyaW5nKXByb3AuZ2V0KCJ0eXBlIik7CgkgICAg
CQkgICAgCQlWYWx1ZXNFbXVsYXRvci5wdXQoaWRhdGEsICJ0eXBlIiwgdHlwZSk7CgkgICAgCQkg
ICAgCQlpZih0eXBlICE9IG51bGwgJiYgdHlwZS5lcXVhbHNJZ25vcmVDYXNlKCJESVIiKSkKCSAg
ICAJCSAgICAJCQlsaXN0RGlyLmFkZEVsZW1lbnQoaWRhdGEpOwoJICAgIAkJICAgIAkJZWxzZXsK
CSAgICAJCSAgICAJCQlpZihmaWxlc0luY2x1ZGVkICE9IG51bGwgJiYgZmlsZXNJbmNsdWRlZC5l
cXVhbHNJZ25vcmVDYXNlKCJ0cnVlIikpCgkgICAgCQkgICAgCQkJCWxpc3RGaWxlLmFkZEVsZW1l
bnQoaWRhdGEpOwoJICAgIAkJICAgIAkJfQoJICAgIAkJCQl9CgkgICAgCQkJfQoJICAgIAkJfQoJ
ICAgIAl9CgkgICAgCUlEYXRhW10gc29ydGVkRGlyTGlzdCA9IGxpc3REaXIuZ2V0U29ydGVkTGlz
dCgpOwoJICAgIAlJRGF0YVtdIHNvcnRlZEZpbGVMaXN0ID0gbGlzdEZpbGUuZ2V0U29ydGVkTGlz
dCgpOwoJICAgIAlJRGF0YVtdIGZpbmFsTGlzdCA9IG51bGw7CgkgICAgCWlmKHNvcnRlZERpckxp
c3QgIT0gbnVsbCAmJiBzb3J0ZWRGaWxlTGlzdCA9PSBudWxsKXsKCSAgICAJCWZpbmFsTGlzdCA9
IHNvcnRlZERpckxpc3Q7IAoJICAgIAl9ZWxzZSBpZihzb3J0ZWRGaWxlTGlzdCAhPSBudWxsICYm
ICBzb3J0ZWREaXJMaXN0ID09IG51bGwpewoJICAgIAkJZmluYWxMaXN0ID0gc29ydGVkRmlsZUxp
c3Q7CgkgICAgCX1lbHNlIGlmKHNvcnRlZEZpbGVMaXN0ICE9IG51bGwgJiYgIHNvcnRlZERpckxp
c3QgIT0gbnVsbCl7CgkgICAgCQlpbnQgbGVuZ3RoID0gc29ydGVkRmlsZUxpc3QubGVuZ3RoICsg
c29ydGVkRGlyTGlzdC5sZW5ndGg7CgkgICAgCQlmaW5hbExpc3QgPSBuZXcgSURhdGFbbGVuZ3Ro
XTsKCSAgICAJCWludCBrID0gMDsKCSAgICAJCWZvciAoaW50IGkgPSAwOyBpIDwgbGVuZ3RoOyBp
KyspewoJICAgIAkJCWlmKGkgPCBzb3J0ZWREaXJMaXN0Lmxlbmd0aCkKCSAgICAJCQkJZmluYWxM
aXN0W2ldID0gc29ydGVkRGlyTGlzdFtpXTsKCSAgICAJCQllbHNlewoJICAgIAkJCQlmaW5hbExp
c3RbaV0gPSBzb3J0ZWRGaWxlTGlzdFtrKytdOwoJICAgIAkJCX0KCSAgICAJCX0KCSAgICAJfQoJ
ICAgIAlWYWx1ZXNFbXVsYXRvci5wdXQob3V0cHV0LCAiZmlsZXMiLCBmaW5hbExpc3QpOwoJICAg
IH1jYXRjaCAoVGhyb3dhYmxlIHQpewoJICAgIAlzdmNSZXNwID0gUG9ydGFsVXRpbHMuY2F0Y2hF
cnJvcih0LCBzdmNOYW1lLCBTaGFyZWRDb25zdGFudHMuRVJST1Isc3ZjUmVzcCk7CgkgICAgfWZp
bmFsbHkgewoJICAgIAlpZiAoY3VyICE9IG51bGwpewoJICAgIAkJY3VyLmRlc3Ryb3koKTsKCSAg
ICAJfQoJICAgIAlWYWx1ZXNFbXVsYXRvci5wdXQob3V0cHV0LCAic3ZjUmVzcG9uc2UiLCBzdmNS
ZXNwKTsKCSAgICAJVmFsdWVzRW11bGF0b3IucHV0KHBpcGVsaW5lLCAib3V0cHV0Iiwgb3V0cHV0
KTsJICAgICAgICAJCgkgICAgfQoK</value>
</Values>
