<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">generateCertificatePairs</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:required keyType</value>
    <value>[i] field:0:required keyAlgorithm</value>
    <value>[i] field:0:required keyLength</value>
    <value>[i] field:0:required privateKeyAlias</value>
    <value>[i] field:0:required validityDays</value>
    <value>[i] field:0:required password</value>
    <value>[o] field:0:required success</value>
    <value>[o] field:0:required message</value>
  </array>
  <value name="subtype">unknown</value>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgY3VyID0gbnVsbDsKSURhdGEgb3V0cHV0ID0gSURhdGFGYWN0b3J5LmNyZWF0
ZSgpOwpJRGF0YSBzdmNSZXNwID0gbnVsbDsKU3RyaW5nIHN2Y05hbWUgPSAid20ubWZ0LnVpLmNl
cnRpZmljYXRlOmdlbmVyYXRlQ2VydGlmaWNhdGVQYWlycyI7CnRyeSB7CglTdHJpbmcga2V5VHlw
ZSA9IFZhbHVlc0VtdWxhdG9yLmdldFN0cmluZyhwaXBlbGluZSwgImtleVR5cGUiKTsKCWlmIChu
dWxsID09IGtleVR5cGUgfHwga2V5VHlwZS5pc0JsYW5rKCkpIHsKCQlrZXlUeXBlID0gIlBHUCI7
Cgl9CglpZiAoISJQR1AiLmVxdWFsc0lnbm9yZUNhc2Uoa2V5VHlwZSkKCQkJJiYgISJTU0giLmVx
dWFsc0lnbm9yZUNhc2Uoa2V5VHlwZSkpIHsKCQl0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbigi
S2V5IHR5cGUgbm90IHNwZWNpZmllZC4gQ2FuIGJlIGVpdGhlciBQR1Agb3IgU1NILiIpOwoJfQoK
CVN0cmluZyBhbGdvcml0aG0gPSBWYWx1ZXNFbXVsYXRvci5nZXRTdHJpbmcocGlwZWxpbmUsICJr
ZXlBbGdvcml0aG0iKTsKCWludCBrZXlTaXplID0gNDA5NjsKCVN0cmluZyBiaXRMZW5ndGhTdHJp
bmcgPSBWYWx1ZXNFbXVsYXRvci5nZXRTdHJpbmcocGlwZWxpbmUsICJrZXlMZW5ndGgiKTsKCXRy
eSB7CgkJa2V5U2l6ZSA9IEludGVnZXIudmFsdWVPZihiaXRMZW5ndGhTdHJpbmcpOwoJCWlmIChr
ZXlTaXplIDwgMCB8fCBrZXlTaXplICE9IDgxOTIpIHsKCQkJa2V5U2l6ZSA9IDQwOTY7CgkJfQoJ
fSBjYXRjaCAoRXhjZXB0aW9uIGUpIHsKCX0KCgoJU3RyaW5nIHByaXZhdGVLZXlBbGlhcyA9IFZh
bHVlc0VtdWxhdG9yLmdldFN0cmluZyhwaXBlbGluZSwgInByaXZhdGVLZXlBbGlhcyIpOwoJU3Ry
aW5nIGRheXMgPSBWYWx1ZXNFbXVsYXRvci5nZXRTdHJpbmcocGlwZWxpbmUsICJ2YWxpZGl0eURh
eXMiKTsKCWludCBkYXlzSW50ID0gMzY1OwoJdHJ5IHsKCQlkYXlzSW50ID0gSW50ZWdlci5wYXJz
ZUludChkYXlzKTsKCQlpZiAoZGF5c0ludCA8PSAwKSB7CgkJCWRheXNJbnQgPSAzNjU7CgkJfQoJ
fSBjYXRjaCAoRXhjZXB0aW9uIGUpIHsKCQkvLyAwIHZhbGlkaXR5IGluZGljYXRlcywgbm8gZXhw
aXJ5Cgl9CglTdHJpbmcgcGFzc3dvcmQgPSBWYWx1ZXNFbXVsYXRvci5nZXRTdHJpbmcocGlwZWxp
bmUsICJwYXNzd29yZCIpOwoJaWYgKHBhc3N3b3JkID09IG51bGwgfHwgcGFzc3dvcmQuZXF1YWxz
KCIiKSkgewoJCXRocm93IG5ldyBTZXJ2aWNlRXhjZXB0aW9uKCJQYXNzd29yZCBjYW5ub3QgYmUg
ZW1wdHkuIik7Cgl9CglpZiAoIlBHUCIuZXF1YWxzSWdub3JlQ2FzZShrZXlUeXBlKSkgewoJCVNl
cnZlckFkbWluUHJveHkuZ2VuZXJhdGVQR1BLZXlGaWxlc1N0cmVhbShwcml2YXRlS2V5QWxpYXMs
IGFsZ29yaXRobSwga2V5U2l6ZSwgZGF5c0ludCwgcGFzc3dvcmQsICJjb21tb25OYW1lIik7Cgl9
IGVsc2UgaWYgKCJTU0giLmVxdWFsc0lnbm9yZUNhc2Uoa2V5VHlwZSkpIHsKCQlTZXJ2ZXJBZG1p
blByb3h5LmdlbmVyYXRlU1NIS2V5RmlsZVN0cmVhbShwcml2YXRlS2V5QWxpYXMsIGFsZ29yaXRo
bSwga2V5U2l6ZSwgcGFzc3dvcmQpOwoJfQoJVmFsdWVzRW11bGF0b3IucHV0KHBpcGVsaW5lLCAi
c3VjY2VzcyIsICJ0cnVlIik7CglWYWx1ZXNFbXVsYXRvci5wdXQocGlwZWxpbmUsICJtZXNzYWdl
IiwgIktleXMgc3VjY2Vzc2Z1bGx5IGdlbmVyYXRlZC4iKTsKCVZhbHVlc0VtdWxhdG9yLnJlbW92
ZShwaXBlbGluZSwgInBhc3N3b3JkIik7CgkvLyBUT0RPLCBwYXNzIG9uIHByaXZhdGUga2V5IGFu
ZCBwdWJsaWMga2V5IGlkcyBhcyBwYXJ0IG9mIHRoZSByZXNwb25zZQp9IGNhdGNoIChTZXJ2aWNl
RXhjZXB0aW9uIHNlKSB7CglWYWx1ZXNFbXVsYXRvci5wdXQocGlwZWxpbmUsICJzdWNjZXNzIiwg
ImZhbHNlIik7CglWYWx1ZXNFbXVsYXRvci5wdXQocGlwZWxpbmUsICJtZXNzYWdlIiwgc2UuZ2V0
TG9jYWxpemVkTWVzc2FnZSgpKTsKfSBjYXRjaCAoVGhyb3dhYmxlIHQpIHsKCUNvbW1vblByb3h5
LmVycm9yUGFja2FnZUxvZyh0LCAiOTk5OSIsIHQuZ2V0TG9jYWxpemVkTWVzc2FnZSgpKTsKCVZh
bHVlc0VtdWxhdG9yLnB1dChwaXBlbGluZSwgInN1Y2Nlc3MiLCAiZmFsc2UiKTsKCVZhbHVlc0Vt
dWxhdG9yLnB1dChwaXBlbGluZSwgIm1lc3NhZ2UiLCAiS2V5IGdlbmVyYXRpb24gZmFpbGVkIik7
Cn0gZmluYWxseSB7CglWYWx1ZXNFbXVsYXRvci5yZW1vdmUocGlwZWxpbmUsICJwYXNzd29yZCIp
OwoJVmFsdWVzRW11bGF0b3IucmVtb3ZlKHBpcGVsaW5lLCAiY29uZmlybVBhc3N3b3JkIik7Cglp
ZiAoY3VyICE9IG51bGwpIHsKCQljdXIuZGVzdHJveSgpOwoJfQp9Cg==</value>
</Values>
