<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">add</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:required name</value>
    <value>[i] field:0:required type</value>
    <value>[i] field:0:required isParent</value>
    <value>[i] field:0:required parentId</value>
    <value>[i] field:0:required isTNPartner</value>
    <value>[i] field:0:required partnerID</value>
    <value>[i] field:0:required partnerName</value>
    <value>[o] field:0:required success</value>
    <value>[o] field:0:optional vfsId</value>
    <value>[o] field:0:required message</value>
    <value>[o] field:1:required validationErrors</value>
  </array>
  <value name="subtype">unknown</value>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">U3RyaW5nIG1lc3NhZ2UgPSBNRlRSZXNvdXJjZXMuZ2V0TWVzc2FnZSgiMTAxMyIpOwpWaXJ0dWFs
RmlsZU9iamVjdCB2ZnMgPSBuZXcgVmlydHVhbEZpbGVPYmplY3QoKTsKdmZzLnNldFZmc0lkKCJu
ZXciKTsKdmZzLnNldFBhcmVudCh0cnVlKTsKSURhdGFDdXJzb3IgaW5jdXIgPSBwaXBlbGluZS5n
ZXRDdXJzb3IoKTsKU3RyaW5nIFZGU05hbWUgPSBudWxsOwppZiAoaW5jdXIuZmlyc3QoIm5hbWUi
KSkgewoJVkZTTmFtZSA9IChTdHJpbmcpIGluY3VyLmdldFZhbHVlKCk7Cgl2ZnMuc2V0VkZTTmFt
ZShWRlNOYW1lKTsKfQpTdHJpbmcgVkZTVHlwZSA9IG51bGw7CmlmIChpbmN1ci5maXJzdCgidHlw
ZSIpKSB7CglWRlNUeXBlID0gKFN0cmluZykgaW5jdXIuZ2V0VmFsdWUoKTsKCWlmKCJWSVJUVUFM
Ii5lcXVhbHNJZ25vcmVDYXNlKFZGU1R5cGUpKXsKCQl2ZnMuc2V0VkZTVmlydHVhbCh0cnVlKTsK
CX0gZWxzZSBpZigiRklMRSIuZXF1YWxzSWdub3JlQ2FzZShWRlNUeXBlKSl7CgkJdmZzLnNldFZG
U1VSTCgiRklMRTovLyIpOwoJfSBlbHNlIGlmKCJSRU1PVEUiLmVxdWFsc0lnbm9yZUNhc2UoVkZT
VHlwZSkpewoJCXZmcy5zZXRWRlNVUkwoIkZUUDovLyIpOwoJfQoJdmZzLnNldFZGU1R5cGUoVkZT
VHlwZSk7Cn0KU3RyaW5nIHZpcnR1YWxQYXJlbnRJRCA9IG51bGw7CmlmIChpbmN1ci5maXJzdCgi
cGFyZW50SWQiKSkgewoJdmlydHVhbFBhcmVudElEID0gKFN0cmluZykgaW5jdXIuZ2V0VmFsdWUo
KTsKCXZmcy5zZXRWaXJ0dWFsUGFyZW50SUQodmlydHVhbFBhcmVudElEKTsKfQoKQm9vbGVhbiBp
c1BhcmVudCA9IGZhbHNlOwppZiAoaW5jdXIuZmlyc3QoImlzUGFyZW50IikpIHsKCWlzUGFyZW50
ID0gQm9vbGVhbi52YWx1ZU9mKChCb29sZWFuKSBpbmN1ci5nZXRWYWx1ZSgpKTsKCXZmcy5zZXRQ
YXJlbnQoaXNQYXJlbnQpOwp9CgpCb29sZWFuIGlzVE5QYXJ0bmVyID0gZmFsc2U7CmlmIChpbmN1
ci5maXJzdCgiaXNUTlBhcnRuZXIiKSkgewoJaXNUTlBhcnRuZXIgPSBCb29sZWFuLnZhbHVlT2Yo
KEJvb2xlYW4pIGluY3VyLmdldFZhbHVlKCkpOwoJdmZzLnNldFROUGFydG5lcihpc1ROUGFydG5l
cik7Cn0KClN0cmluZyBwYXJ0bmVySUQgPSBudWxsOwppZiAoaW5jdXIuZmlyc3QoInBhcnRuZXJJ
RCIpKSB7CglwYXJ0bmVySUQgPSAoU3RyaW5nKSBpbmN1ci5nZXRWYWx1ZSgpOwoJdmZzLnNldFBh
cnRuZXJJRChwYXJ0bmVySUQpOwp9CgpTdHJpbmcgcGFydG5lck5hbWUgPSBudWxsOwppZiAoaW5j
dXIuZmlyc3QoInBhcnRuZXJOYW1lIikpIHsKCXBhcnRuZXJOYW1lID0gKFN0cmluZykgaW5jdXIu
Z2V0VmFsdWUoKTsKCXZmcy5zZXRQYXJ0bmVyTmFtZShwYXJ0bmVyTmFtZSk7Cn0KCmlmIChpbmN1
ci5maXJzdCgiZmFzcEJyaWRnZSIpKSB7CglTdHJpbmcgZmFzcEJyaWRnZSA9IChTdHJpbmcpIGlu
Y3VyLmdldFZhbHVlKCk7CglpZiAobnVsbCE9ZmFzcEJyaWRnZSAmJiAhZmFzcEJyaWRnZS5pc0Js
YW5rKCkpewoJCXZmcy5zZXRGYXNwaW9CcmlkZ2VOYW1lKGZhc3BCcmlkZ2UpOwoJfQp9Cgpib29s
ZWFuIHN1Y2Nlc3MgPSBmYWxzZTsKClN0cmluZ1tdIG1lc3NhZ2VBcnJheSA9IG51bGw7ClN0cmlu
ZyB2ZnNJZCA9IG51bGw7CnRyeSB7CgkKCS8vIEZvciBVSSBjYWxscyBjaGVjayBmb3IgcGVybWlz
c2lvbiBmb3IgdGhlIGxvZ2dlZCBpbiB1c2VyCglSQkFQcm94eS52YWxpZGF0ZVNlc3Npb24oUkJB
VWlIYW5kbGUuVkZTX0FERCk7CgkKCS8vIEZvciBhZGRpbmcgVkZTLCBWRlMgaWQgaXMgbm90IHBl
cm1pdHRlZCBmcm9tIEFQSSBzZXJ2aWNlcwoJdmZzLnNldFZmc0lkKG51bGwpOwoJdmZzSWQgPSBV
c2VyTWFuYWdlclByb3h5LmFkZFZGUyh2ZnMsIHRydWUpOwoJc3VjY2VzcyA9ICh2ZnNJZCAhPSBu
dWxsKTsKCn0gY2F0Y2ggKFRocm93YWJsZSB0KSB7CgltZXNzYWdlID0gdC5nZXRMb2NhbGl6ZWRN
ZXNzYWdlKCk7CglpZiAodCBpbnN0YW5jZW9mIE1GVFNlcnZpY2VFeGNlcHRpb24pIHsKCQlMaXN0
PFN0cmluZz4gbWVzc2FnZUxpc3QgPSAoKE1GVFNlcnZpY2VFeGNlcHRpb24pIHQpLmdldEVycm9y
TWVzc2FnZUxpc3QoKTsKCQlpZiAobWVzc2FnZUxpc3QgIT0gbnVsbCkgewoJCQltZXNzYWdlQXJy
YXkgPSBuZXcgU3RyaW5nW21lc3NhZ2VMaXN0LnNpemUoKV07CgkJCW1lc3NhZ2VMaXN0LnRvQXJy
YXkobWVzc2FnZUFycmF5KTsKCQl9Cgl9Cn0gZmluYWxseSB7CglWYWx1ZXNFbXVsYXRvci5wdXQo
cGlwZWxpbmUsICJzdWNjZXNzIiwgU3RyaW5nLnZhbHVlT2Yoc3VjY2VzcykpOwoJVmFsdWVzRW11
bGF0b3IucHV0KHBpcGVsaW5lLCAidmZzSWQiLCB2ZnNJZCk7CglWYWx1ZXNFbXVsYXRvci5wdXQo
cGlwZWxpbmUsICJtZXNzYWdlIiwgbWVzc2FnZSk7CglpZiAobnVsbCAhPSBtZXNzYWdlQXJyYXkp
IHsKCQlWYWx1ZXNFbXVsYXRvci5wdXQocGlwZWxpbmUsICJ2YWxpZGF0aW9uRXJyb3JzIiwgbWVz
c2FnZUFycmF5KTsKCX0KfQoK</value>
</Values>
