<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">updateBatchAndRate</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:required batchSize</value>
    <value>[i] field:0:required rateLimit</value>
    <value>[o] record:0:required output</value>
    <value>[o] - field:0:required success</value>
    <value>[o] - field:0:required message</value>
    <value>[o] - field:0:optional batchSize</value>
    <value>[o] - field:0:optional rateLimit</value>
  </array>
  <value name="subtype">unknown</value>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">CklEYXRhQ3Vyc29yIGN1ciA9IG51bGw7CklEYXRhIG91dHB1dCA9IElEYXRhRmFjdG9yeS5jcmVh
dGUoKTsKU3RyaW5nIG1lc3NhZ2UgPSBNRlRSZXNvdXJjZXMuZ2V0TWVzc2FnZSgiMTAxMyIpOwpi
b29sZWFuIHN1Y2Nlc3MgPSB0cnVlOwoKdHJ5IHsKCS8vIFZhbGlkYXRlIHVzZXIgc2Vzc2lvbiBh
bmQgcGVybWlzc2lvbnMKCVJCQVByb3h5LnZhbGlkYXRlU2Vzc2lvbihSQkFVaUhhbmRsZS5BUElf
U0VUVElOR1NfVklFVyk7CgkKCWN1ciA9IHBpcGVsaW5lLmdldEN1cnNvcigpOwoJCgkvLyBHZXQg
aW5wdXQgcGFyYW1ldGVycwoJU3RyaW5nIGJhdGNoU2l6ZVN0ciA9IFZhbHVlc0VtdWxhdG9yLmdl
dFN0cmluZyhwaXBlbGluZSwgImJhdGNoU2l6ZSIpOwoJU3RyaW5nIHJhdGVMaW1pdFN0ciA9IFZh
bHVlc0VtdWxhdG9yLmdldFN0cmluZyhwaXBlbGluZSwgInJhdGVMaW1pdCIpOwoJCgkvLyBWYWxp
ZGF0ZSBpbnB1dHMKCWlmIChiYXRjaFNpemVTdHIgPT0gbnVsbCB8fCBiYXRjaFNpemVTdHIuaXNF
bXB0eSgpKSB7CgkJdGhyb3cgbmV3IFNlcnZpY2VFeGNlcHRpb24oImJhdGNoU2l6ZSBpcyByZXF1
aXJlZCIpOwoJfQoJaWYgKHJhdGVMaW1pdFN0ciA9PSBudWxsIHx8IHJhdGVMaW1pdFN0ci5pc0Vt
cHR5KCkpIHsKCQl0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbigicmF0ZUxpbWl0IGlzIHJlcXVp
cmVkIik7Cgl9CgkKCWludCBiYXRjaFNpemUgPSBJbnRlZ2VyLnBhcnNlSW50KGJhdGNoU2l6ZVN0
cik7CglpbnQgcmF0ZUxpbWl0ID0gSW50ZWdlci5wYXJzZUludChyYXRlTGltaXRTdHIpOwoJCgkv
LyBWYWxpZGF0ZSByYW5nZXMKCWlmIChiYXRjaFNpemUgPD0gMCkgewoJCXRocm93IG5ldyBTZXJ2
aWNlRXhjZXB0aW9uKCJiYXRjaFNpemUgbXVzdCBiZSBncmVhdGVyIHRoYW4gMCIpOwoJfQoJaWYg
KHJhdGVMaW1pdCA8PSAwKSB7CgkJdGhyb3cgbmV3IFNlcnZpY2VFeGNlcHRpb24oInJhdGVMaW1p
dCBtdXN0IGJlIGdyZWF0ZXIgdGhhbiAwIik7Cgl9CgkKCS8vIFVwZGF0ZSBiYXRjaCBzaXplIGFu
ZCByYXRlIGxpbWl0IGluIGEgc2luZ2xlIG9wZXJhdGlvbiAob25lIGF1ZGl0IGVudHJ5KQoJYm9v
bGVhbiB1cGRhdGVkID0gQXBpU2V0dGluZ3NQcm94eS51cGRhdGVTZXR0aW5ncyhiYXRjaFNpemUs
IHJhdGVMaW1pdCk7CgoJaWYgKCF1cGRhdGVkKSB7CgkJdGhyb3cgbmV3IFNlcnZpY2VFeGNlcHRp
b24oIkZhaWxlZCB0byB1cGRhdGUgc2V0dGluZ3MgZHVlIHRvIHZlcnNpb24gY29uZmxpY3QuIFBs
ZWFzZSB0cnkgYWdhaW4uIik7Cgl9CgkKCS8vIFNldCBzdWNjZXNzIHJlc3BvbnNlCgltZXNzYWdl
ID0gIkJhdGNoIHNpemUgYW5kIHJhdGUgbGltaXQgdXBkYXRlZCBzdWNjZXNzZnVsbHkiOwoJVmFs
dWVzRW11bGF0b3IucHV0KG91dHB1dCwgInN1Y2Nlc3MiLCB0cnVlKTsKCVZhbHVlc0VtdWxhdG9y
LnB1dChvdXRwdXQsICJtZXNzYWdlIiwgbWVzc2FnZSk7CglWYWx1ZXNFbXVsYXRvci5wdXQob3V0
cHV0LCAiYmF0Y2hTaXplIiwgYmF0Y2hTaXplKTsKCVZhbHVlc0VtdWxhdG9yLnB1dChvdXRwdXQs
ICJyYXRlTGltaXQiLCByYXRlTGltaXQpOwoJCn0gY2F0Y2ggKE51bWJlckZvcm1hdEV4Y2VwdGlv
biBlKSB7CglzdWNjZXNzID0gZmFsc2U7CgltZXNzYWdlID0gIkludmFsaWQgbnVtYmVyIGZvcm1h
dCBmb3IgYmF0Y2hTaXplIG9yIHJhdGVMaW1pdCI7CglWYWx1ZXNFbXVsYXRvci5wdXQob3V0cHV0
LCAic3VjY2VzcyIsIGZhbHNlKTsKCVZhbHVlc0VtdWxhdG9yLnB1dChvdXRwdXQsICJtZXNzYWdl
IiwgbWVzc2FnZSk7Cn0gY2F0Y2ggKEV4Y2VwdGlvbiBlKSB7CglzdWNjZXNzID0gZmFsc2U7Cglt
ZXNzYWdlID0gZS5nZXRMb2NhbGl6ZWRNZXNzYWdlKCk7CglWYWx1ZXNFbXVsYXRvci5wdXQob3V0
cHV0LCAic3VjY2VzcyIsIGZhbHNlKTsKCVZhbHVlc0VtdWxhdG9yLnB1dChvdXRwdXQsICJtZXNz
YWdlIiwgbWVzc2FnZSk7Cn0gZmluYWxseSB7CglpZiAoY3VyICE9IG51bGwpIHsKCQljdXIuZGVz
dHJveSgpOwoJfQoJVmFsdWVzRW11bGF0b3IucHV0KHBpcGVsaW5lLCAib3V0cHV0Iiwgb3V0cHV0
KTsKfQoK</value>
</Values>
