<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">initializeSSOCentralized</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:required ssodefaultCertificateId</value>
    <value>[i] field:1:required ssoencryptCertificateId</value>
    <value>[i] field:2:required ssosignCertificateId</value>
    <value>[i] field:3:required ssoIDPMetaUrl</value>
    <value>[i] field:4:required ssoSPEndpointUrl</value>
    <value>[i] field:5:required ssoClientId</value>
    <value>[i] field:6:required ssoIDPInitiatedRedirectUri</value>
    <value>[i] field:7:required instanceId</value>
    <value>[o] record:0:required output</value>
    <value>[o] - field:0:required success</value>
    <value>[o] - field:0:required message</value>
  </array>
  <value name="subtype">unknown</value>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">CklEYXRhIG91dHB1dCA9IElEYXRhRmFjdG9yeS5jcmVhdGUoKTsKSURhdGFDdXJzb3IgY3VyID0g
cGlwZWxpbmUuZ2V0Q3Vyc29yKCk7ClN0cmluZyBzc29EZWZhdWx0Q2VydGlmaWNhdGVBbGlhcyA9
IG51bGw7ClN0cmluZyBzc29TaWduQ2VydGlmaWNhdGVBbGlhcyA9IG51bGw7ClN0cmluZyBzc29F
bmNyeXB0Q2VydGlmaWNhdGVBbGlhcyA9IG51bGw7ClN0cmluZyBzc29DZXJ0aWZpY2F0ZSA9IG51
bGw7ClN0cmluZyBzc29JRFBNZXRhVXJsID0gbnVsbDsKU3RyaW5nIHNzb1NQRW5kcG9pbnRVcmwg
PSBudWxsOwpTdHJpbmcgc3NvQ2xpZW50SWQgPSBudWxsOwpTdHJpbmcgc3NvSURQSW5pdGlhdGVk
UmVkaXJlY3RVcmkgPSBudWxsOwpTdHJpbmcgc3NvTWF4QXV0aEFnZSA9IG51bGw7ClN0cmluZyBw
b3J0ID0gbnVsbDsKU3RyaW5nIGluc3RhbmNlSWQgPSBNRlREYXRhQ29uc3RhbnRzLlNFUlZFUl9J
TlNUQU5DRUlEX0RFRkFVTFQ7CmlmIChjdXIuZmlyc3QoInNzb1NpZ25DZXJ0aWZpY2F0ZUFsaWFz
IikpIHsKCXNzb1NpZ25DZXJ0aWZpY2F0ZUFsaWFzID0gKFN0cmluZykgY3VyLmdldFZhbHVlKCk7
Cn0KaWYgKGN1ci5maXJzdCgic3NvRGVmYXVsdENlcnRpZmljYXRlQWxpYXMiKSkgewoJc3NvRGVm
YXVsdENlcnRpZmljYXRlQWxpYXMgPSAoU3RyaW5nKSBjdXIuZ2V0VmFsdWUoKTsKfQppZiAoY3Vy
LmZpcnN0KCJzc29FbmNyeXB0Q2VydGlmaWNhdGVBbGlhcyIpKSB7Cglzc29FbmNyeXB0Q2VydGlm
aWNhdGVBbGlhcyA9IChTdHJpbmcpIGN1ci5nZXRWYWx1ZSgpOwp9CmlmIChjdXIuZmlyc3QoInNz
b0NlcnRpZmljYXRlSWQiKSkgewoJc3NvQ2VydGlmaWNhdGUgPSAoU3RyaW5nKSBjdXIuZ2V0VmFs
dWUoKTsKfQppZiAoY3VyLmZpcnN0KCJzc29JRFBNZXRhVXJsIikpIHsKCXNzb0lEUE1ldGFVcmwg
PSAoU3RyaW5nKSBjdXIuZ2V0VmFsdWUoKTsKfQppZiAoY3VyLmZpcnN0KCJzc29TUEVuZHBvaW50
VXJsIikpIHsKCXNzb1NQRW5kcG9pbnRVcmwgPSAoU3RyaW5nKSBjdXIuZ2V0VmFsdWUoKTsKfQpp
ZiAoY3VyLmZpcnN0KCJzc29DbGllbnRJZCIpKSB7Cglzc29DbGllbnRJZCA9IChTdHJpbmcpIGN1
ci5nZXRWYWx1ZSgpOwp9CmlmIChjdXIuZmlyc3QoInNzb0lEUEluaXRpYXRlZFJlZGlyZWN0VXJp
IikpIHsKCWlmICgoU3RyaW5nKSBjdXIuZ2V0VmFsdWUoKSAhPSAibnVsbCIpIHsKCQlzc29JRFBJ
bml0aWF0ZWRSZWRpcmVjdFVyaSA9IChTdHJpbmcpIGN1ci5nZXRWYWx1ZSgpOwoJfQp9CmlmIChj
dXIuZmlyc3QoInNzb01heEF1dGhBZ2UiKSkgewoJc3NvTWF4QXV0aEFnZSA9IChTdHJpbmcpIGN1
ci5nZXRWYWx1ZSgpOwp9CmlmIChjdXIuZmlyc3QoImluc3RhbmNlSWQiKSkgewoJaW5zdGFuY2VJ
ZCA9IChTdHJpbmcpIGN1ci5nZXRWYWx1ZSgpOwp9CmlmIChjdXIuZmlyc3QoInBvcnRObyIpKSB7
Cglwb3J0ID0gKFN0cmluZykgY3VyLmdldFZhbHVlKCk7CglpZighTUZURGF0YUNvbnN0YW50cy5T
RVJWRVJfSU5TVEFOQ0VJRF9ERUZBVUxULmVxdWFscyhpbnN0YW5jZUlkKSl7CgkJcG9ydCA9ICJE
TVpfUG9ydF8iICsgaW5zdGFuY2VJZCArICJfIiArIHBvcnQ7Cgl9Cn0KCnRyeSB7CglSQkFQcm94
eS52YWxpZGF0ZVNlc3Npb24oUkJBVWlIYW5kbGUuTElTVEVORVJfVklFVyk7CglNRlRDZXJ0aWZp
Y2F0ZURhdGEgY2VydGlmaWNhdGVEYXRhID0gQ29tbW9uUHJveHkudmlld01GVEtleURhdGEoc3Nv
Q2VydGlmaWNhdGUpOwoKCVN0cmluZyByZXN1bHQgPSBTU09NYW5hZ2VyLmluaXRpYWxpemVTU09D
ZW50cmFsaXplZCh0cnVlLCBjZXJ0aWZpY2F0ZURhdGEsIHNzb0RlZmF1bHRDZXJ0aWZpY2F0ZUFs
aWFzLAoJCQlzc29FbmNyeXB0Q2VydGlmaWNhdGVBbGlhcywgc3NvU2lnbkNlcnRpZmljYXRlQWxp
YXMsIHNzb1NQRW5kcG9pbnRVcmwsIHNzb0lEUE1ldGFVcmwsCgkJCXNzb0lEUEluaXRpYXRlZFJl
ZGlyZWN0VXJpLCBwb3J0LCBzc29DbGllbnRJZCwgc3NvTWF4QXV0aEFnZSk7CglWYWx1ZXNFbXVs
YXRvci5wdXQob3V0cHV0LCAibWVzc2FnZSIsIHJlc3VsdCk7CglWYWx1ZXNFbXVsYXRvci5wdXQo
b3V0cHV0LCAic3VjY2VzcyIsIHRydWUpOwoKfSBjYXRjaCAoVGhyb3dhYmxlIGUpIHsKCWlmKFNl
cnZlckFkbWluUHJveHkuaXNDbG91ZE1vZGUoKSkgewoJCVZhbHVlc0VtdWxhdG9yLnB1dChwaXBl
bGluZSwgIm1lc3NhZ2UiLCAiQ2hlY2sgeW91ciBjb25maWd1cmF0aW9ucy4iKTsKCX1lbHNlewoJ
CVZhbHVlc0VtdWxhdG9yLnB1dChwaXBlbGluZSwgIm1lc3NhZ2UiLCBlLmdldE1lc3NhZ2UoKSk7
Cgl9CgkKCVZhbHVlc0VtdWxhdG9yLnB1dChwaXBlbGluZSwgInN1Y2Nlc3MiLCBmYWxzZSk7Cn0K
CmZpbmFsbHkgewoJVmFsdWVzRW11bGF0b3IucHV0KHBpcGVsaW5lLCAib3V0cHV0Iiwgb3V0cHV0
KTsKfQo=</value>
</Values>
