<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">list</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:required pageNumber</value>
    <value>[i] field:0:required pageSize</value>
    <value>[o] record:1:required archiveData</value>
    <value>[o] - field:0:required startDate</value>
    <value>[o] - field:0:required endDate</value>
    <value>[o] - field:0:required referenceNumber</value>
    <value>[o] - field:0:required status</value>
    <value>[o] - field:0:required userId</value>
    <value>[o] field:0:required message</value>
    <value>[o] field:0:required success</value>
    <value>[o] field:0:required totalCount</value>
  </array>
  <value name="subtype">unknown</value>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">U3RyaW5nIG1lc3NhZ2UgPSBNRlRSZXNvdXJjZXMuZ2V0TWVzc2FnZSgiMTAxMyIpOwpib29sZWFu
IHN1Y2Nlc3MgPSB0cnVlOwpsb25nIHRvdGFsQ291bnQgPSAwOwp0cnkgewoJUkJBUHJveHkudmFs
aWRhdGVTZXNzaW9uKFJCQVVpSGFuZGxlLkRBVEFCQVNFX0FSQ0hJVkFMX1ZJRVcpOwoJaW50IHBh
Z2VOdW1iZXIgPSBWYWx1ZXNFbXVsYXRvci5nZXRJbnQocGlwZWxpbmUsICJwYWdlTnVtYmVyIiwg
MSk7CglpbnQgcGFnZVNpemUgPSBWYWx1ZXNFbXVsYXRvci5nZXRJbnQocGlwZWxpbmUsICJwYWdl
U2l6ZSIsIDUpOwoJaW50IHN0YXR1cyA9IC0xOwoJbG9uZyBzdGFydERhdGUgPSAwOwoJbG9uZyBl
bmREYXRlID0gMDsKCVN0cmluZyBzZWFyY2hVc2VySWQgPSBudWxsOwoJSURhdGEgaVNlYXJjaENy
aXRlcmlhID0gKElEYXRhKSBWYWx1ZXNFbXVsYXRvci5nZXQocGlwZWxpbmUsICJzZWFyY2hDcml0
ZXJpYSIpOwoJaWYgKGlTZWFyY2hDcml0ZXJpYSAhPSBudWxsKSB7CgkJU3RyaW5nIHN0YXR1c1N0
ciA9IFZhbHVlc0VtdWxhdG9yLmdldFN0cmluZyhpU2VhcmNoQ3JpdGVyaWEsICJzdGF0dXMiKTsK
CQlpZiAoc3RhdHVzU3RyICE9IG51bGwpIHsKCQkJdHJ5IHsKCQkJCXN0YXR1cyA9IEludGVnZXIu
dmFsdWVPZihzdGF0dXNTdHIpOwoJCQl9IGNhdGNoIChOdW1iZXJGb3JtYXRFeGNlcHRpb24gZXgp
IHsKCQkJfQoJCX0KCQlzZWFyY2hVc2VySWQgPSBWYWx1ZXNFbXVsYXRvci5nZXRTdHJpbmcoaVNl
YXJjaENyaXRlcmlhLCAidXNlcklkIik7CgkJSURhdGEgaURhdGVSYW5nZSA9IChJRGF0YSkgVmFs
dWVzRW11bGF0b3IuZ2V0KGlTZWFyY2hDcml0ZXJpYSwgImRhdGVSYW5nZSIpOwoJCXRyeSB7CgkJ
CVN0cmluZyBzRGF0ZSA9IFZhbHVlc0VtdWxhdG9yLmdldFN0cmluZyhpRGF0ZVJhbmdlLCAic3Rh
cnREYXRlIik7CgkJCXN0YXJ0RGF0ZSA9IExvbmcucGFyc2VMb25nKHNEYXRlKTsKCQl9IGNhdGNo
IChOdW1iZXJGb3JtYXRFeGNlcHRpb24gbmZlKSB7CgkJfQoJCXRyeSB7CgkJCVN0cmluZyBlRGF0
ZSA9IFZhbHVlc0VtdWxhdG9yLmdldFN0cmluZyhpRGF0ZVJhbmdlLCAiZW5kRGF0ZSIpOwoJCQll
bmREYXRlID0gTG9uZy5wYXJzZUxvbmcoZURhdGUpOwoJCX0gY2F0Y2ggKE51bWJlckZvcm1hdEV4
Y2VwdGlvbiBuZmUpIHsKCQl9Cgl9CglBY3RpdmVUcmFuc2ZlckFyY2hpdmVEYXRhUmVzcG9uc2Ug
YXJjaGl2ZURhdGFSZXNwb25zZSA9IENvbW1vblByb3h5Lmxpc3RNRlRBcmNoaXZhbExvZ3MocGFn
ZU51bWJlciwKCQkJcGFnZVNpemUsIHN0YXR1cywgc2VhcmNoVXNlcklkLCBzdGFydERhdGUsIGVu
ZERhdGUpOwoJTGlzdDxBY3RpdmVUcmFuc2ZlckFyY2hpdmVEYXRhPiBhcmNoaXZlRGF0YSA9IGFy
Y2hpdmVEYXRhUmVzcG9uc2UuZ2V0QWN0aXZlVHJhbnNmZXJBcmNoaXZlRGF0YSgpOwoJdG90YWxD
b3VudCA9IGFyY2hpdmVEYXRhUmVzcG9uc2UuZ2V0VG90YWxDb3VudCgpOwoJTGlzdDxJRGF0YT4g
YXJjaGl2ZURhdGFJRGF0YSA9IG5ldyBBcnJheUxpc3Q8PigpOwoJaWYgKGFyY2hpdmVEYXRhICE9
IG51bGwpIHsKCQlmb3IgKEFjdGl2ZVRyYW5zZmVyQXJjaGl2ZURhdGEgZGF0YSA6IGFyY2hpdmVE
YXRhKSB7CgkJCUlEYXRhIGFyY2hpdmVJZGF0YSA9IElEYXRhRmFjdG9yeS5jcmVhdGUoKTsKCQkJ
VmFsdWVzRW11bGF0b3IucHV0KGFyY2hpdmVJZGF0YSwgInN0YXJ0RGF0ZSIsIGRhdGEuZ2V0U3Rh
cnREYXRlKCkpOwoJCQlWYWx1ZXNFbXVsYXRvci5wdXQoYXJjaGl2ZUlkYXRhLCAiZW5kRGF0ZSIs
IGRhdGEuZ2V0RW5kRGF0ZSgpKTsKCQkJVmFsdWVzRW11bGF0b3IucHV0KGFyY2hpdmVJZGF0YSwg
InJlZmVyZW5jZU51bWJlciIsIGRhdGEuZ2V0UmVmZXJlbmNlTnVtYmVyKCkpOwoJCQlWYWx1ZXNF
bXVsYXRvci5wdXQoYXJjaGl2ZUlkYXRhLCAic3RhdHVzIiwgU3RyaW5nLnZhbHVlT2YoZGF0YS5n
ZXRTdGF0dXMoKSkpOwoJCQlWYWx1ZXNFbXVsYXRvci5wdXQoYXJjaGl2ZUlkYXRhLCAidXNlcklk
IiwgZGF0YS5nZXRVc2VySWQoKSk7CgkJCWFyY2hpdmVEYXRhSURhdGEuYWRkKGFyY2hpdmVJZGF0
YSk7CgkJfQoJfQoJVmFsdWVzRW11bGF0b3IucHV0KHBpcGVsaW5lLCAiYXJjaGl2ZURhdGEiLCBh
cmNoaXZlRGF0YUlEYXRhLnRvQXJyYXkobmV3IElEYXRhW2FyY2hpdmVEYXRhSURhdGEuc2l6ZSgp
XSkpOwp9IGNhdGNoIChUaHJvd2FibGUgdCkgewoJc3VjY2VzcyA9IGZhbHNlOwoJbWVzc2FnZSA9
IHQuZ2V0TG9jYWxpemVkTWVzc2FnZSgpOwp9IGZpbmFsbHkgewoJVmFsdWVzRW11bGF0b3IucHV0
KHBpcGVsaW5lLCAidG90YWxDb3VudCIsIHRvdGFsQ291bnQpOwoJVmFsdWVzRW11bGF0b3IucHV0
KHBpcGVsaW5lLCAic3VjY2VzcyIsIHN1Y2Nlc3MpOwoJVmFsdWVzRW11bGF0b3IucHV0KHBpcGVs
aW5lLCAibWVzc2FnZSIsIG1lc3NhZ2UpOwp9Cg==</value>
</Values>
