<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">updateAgentUser</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:required agentUser</value>
    <value>[o] field:0:required success</value>
    <value>[o] field:0:optional message</value>
  </array>
  <value name="subtype">unknown</value>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">CQlJRGF0YUN1cnNvciBjdXIgPSBudWxsOwoJCVN0cmluZyBtZXNzYWdlID0gTUZUUmVzb3VyY2Vz
LmdldE1lc3NhZ2UoIjEwMTMiKTsKCQlib29sZWFuIHN1Y2Nlc3MgPSB0cnVlOwoJCXRyeSB7CgkJ
CVJCQVByb3h5LnZhbGlkYXRlU2Vzc2lvbihSQkFVaUhhbmRsZS5BR0VOVF9WSUVXKTsKCQkJY3Vy
ID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7CgkJCVN0cmluZyBhZ2VudFVzZXIgPSAoU3RyaW5nKSBW
YWx1ZXNFbXVsYXRvci5nZXQocGlwZWxpbmUsICJhZ2VudFVzZXIiKTsKCgkJCWlmIChhZ2VudFVz
ZXIgPT0gbnVsbCkgewoJCQkJdGhyb3cgbmV3IFNlcnZpY2VFeGNlcHRpb24oImFnZW50VXNlciBw
YXJhbWV0ZXIgaXMgcmVxdWlyZWQiKTsKCQkJfQoKCQkJQWdlbnRzUHJveHkudXBkYXRlQWdlbnRV
c2VyKGFnZW50VXNlcik7CgoJCQl0cnkgewoJCQkJCUZpbGUgcHJvcGVydHlGaWxlID0gbmV3IEZp
bGUoU2VydmVyLmdldFJlc291cmNlcygpLmdldFBhY2thZ2VDb25maWdEaXIoIldtTUZUIiksICJw
cm9wZXJ0aWVzLmNuZiIpOwoJCQkJCWlmIChwcm9wZXJ0eUZpbGUuZXhpc3RzKCkpIHsKCQkJCQkJ
UHJvcGVydGllcyBtZnRQcm9wZXJ0aWVzID0gYWRtaW5pbXBsLmdldE1mdFByb3BlcnRpZXMocHJv
cGVydHlGaWxlKTsKCQkJCQkJbWZ0UHJvcGVydGllcy5zZXRQcm9wZXJ0eShNRlREYXRhQ29uc3Rh
bnRzLk1GVF9BR0VOVF9VU0VSX1BST1BFUlRZLCBhZ2VudFVzZXIpOwoJCQkJCQlhZG1pbmltcGwu
d3JpdGVUb01mdFByb3BlcnR5RmlsZShwcm9wZXJ0eUZpbGUsIG1mdFByb3BlcnRpZXMpOwoJCQkJ
CQlDb21tb25Qcm94eS5pbmZvUGFja2FnZUxvZygiMTExMTAiLCBhZ2VudFVzZXIpOwoJCQkJCX0K
CQoJCQkJCVN5c3RlbS5zZXRQcm9wZXJ0eShNRlREYXRhQ29uc3RhbnRzLk1GVF9BR0VOVF9VU0VS
X1BST1BFUlRZLCBhZ2VudFVzZXIpOwoJCQkJCUNvbW1vblByb3h5LmluZm9QYWNrYWdlTG9nKCIx
MTExMSIsIGFnZW50VXNlcik7CgkJCQkJQ29tbW9uUHJveHkudXBkYXRlUnVudGltZVByb3BlcnRp
ZXMoKTsKCQkJCX0gY2F0Y2ggKFRocm93YWJsZSBjbmZFeCkgewoJCQkJCUNvbW1vblByb3h5LmVy
cm9yUGFja2FnZUxvZyhjbmZFeCwgIjExMTEyIiwgY25mRXguZ2V0TG9jYWxpemVkTWVzc2FnZSgp
KTsKCQkJCX0KCgkJCW1lc3NhZ2UgPSAiQWdlbnQgdXNlciB1cGRhdGVkIHN1Y2Nlc3NmdWxseSI7
CgkJfSBjYXRjaCAoVGhyb3dhYmxlIHQpIHsKCQkJc3VjY2VzcyA9IGZhbHNlOwoJCQltZXNzYWdl
ID0gdC5nZXRMb2NhbGl6ZWRNZXNzYWdlKCk7CgkJfSBmaW5hbGx5IHsKCQkJaWYgKGN1ciAhPSBu
dWxsKSB7CgkJCQljdXIuZGVzdHJveSgpOwoJCQl9CgkJCVZhbHVlc0VtdWxhdG9yLnB1dChwaXBl
bGluZSwgInN1Y2Nlc3MiLCBTdHJpbmcudmFsdWVPZihzdWNjZXNzKSk7CgkJCVZhbHVlc0VtdWxh
dG9yLnB1dChwaXBlbGluZSwgIm1lc3NhZ2UiLCBtZXNzYWdlKTsKCQl9Cg==</value>
</Values>
