<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">initializeSSOCentralized</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:required ssodefaultCertificateId</value>
    <value>[i] field:1:required ssoencryptCertificateId</value>
    <value>[i] field:2:required ssosignCertificateId</value>
    <value>[i] field:3:required ssoIDPMetaUrl</value>
    <value>[i] field:4:required ssoSPEndpointUrl</value>
    <value>[i] field:5:required ssoIDPInitiatedRedirectUri</value>
    <value>[i] field:5:required instanceId</value>
    <value>[o] record:0:required output</value>
    <value>[o] - field:0:required success</value>
    <value>[o] - field:0:required message</value>
  </array>
  <value name="subtype">unknown</value>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">CgkJSURhdGEgb3V0cHV0ID0gSURhdGFGYWN0b3J5LmNyZWF0ZSgpOwoJCUlEYXRhQ3Vyc29yIGN1
ciA9IHBpcGVsaW5lLmdldEN1cnNvcigpOwoJCVN0cmluZyBzc29EZWZhdWx0Q2VydGlmaWNhdGVB
bGlhcyA9IG51bGw7CgkJU3RyaW5nIHNzb1NpZ25DZXJ0aWZpY2F0ZUFsaWFzID0gbnVsbDsKCQlT
dHJpbmcgc3NvRW5jcnlwdENlcnRpZmljYXRlQWxpYXMgPSBudWxsOwoJCVN0cmluZyBzc29DZXJ0
aWZpY2F0ZSA9IG51bGw7CgkJU3RyaW5nIHNzb0lEUE1ldGFVcmwgPSBudWxsOwoJCVN0cmluZyBz
c29TUEVuZHBvaW50VXJsID0gbnVsbDsKCQlTdHJpbmcgY2xpZW50SWQgPSBudWxsOwoJCVN0cmlu
ZyBzc29JRFBJbml0aWF0ZWRSZWRpcmVjdFVyaSA9IG51bGw7CgkJU3RyaW5nIHNzb01heEF1dGhB
Z2UgPSBudWxsOwoJCVN0cmluZyBwb3J0ID0gbnVsbDsKCQlTdHJpbmcgaW5zdGFuY2VJZCA9IE1G
VERhdGFDb25zdGFudHMuU0VSVkVSX0lOU1RBTkNFSURfREVGQVVMVDsKCQlpZiAoY3VyLmZpcnN0
KCJzc29TaWduQ2VydGlmaWNhdGVBbGlhcyIpKSB7CgkJCXNzb1NpZ25DZXJ0aWZpY2F0ZUFsaWFz
ID0gKFN0cmluZykgY3VyLmdldFZhbHVlKCk7CgkJfQoJCWlmIChjdXIuZmlyc3QoInNzb0RlZmF1
bHRDZXJ0aWZpY2F0ZUFsaWFzIikpIHsKCQkJc3NvRGVmYXVsdENlcnRpZmljYXRlQWxpYXMgPSAo
U3RyaW5nKSBjdXIuZ2V0VmFsdWUoKTsKCQl9CgkJaWYgKGN1ci5maXJzdCgic3NvRW5jcnlwdENl
cnRpZmljYXRlQWxpYXMiKSkgewoJCQlzc29FbmNyeXB0Q2VydGlmaWNhdGVBbGlhcyA9IChTdHJp
bmcpIGN1ci5nZXRWYWx1ZSgpOwoJCX0KCQlpZiAoY3VyLmZpcnN0KCJzc29DZXJ0aWZpY2F0ZSIp
KSB7CgkJCXNzb0NlcnRpZmljYXRlID0gKFN0cmluZykgY3VyLmdldFZhbHVlKCk7CgkJfQoJCWlm
IChjdXIuZmlyc3QoInNzb0lEUE1ldGFVcmwiKSkgewoJCQlzc29JRFBNZXRhVXJsID0gKFN0cmlu
ZykgY3VyLmdldFZhbHVlKCk7CgkJfQoJCWlmIChjdXIuZmlyc3QoInNzb1NQRW5kcG9pbnRVcmwi
KSkgewoJCQlzc29TUEVuZHBvaW50VXJsID0gKFN0cmluZykgY3VyLmdldFZhbHVlKCk7CgkJfQoJ
CWlmIChjdXIuZmlyc3QoInNzb0NsaWVudElkIikpIHsKCQkJY2xpZW50SWQgPSAoU3RyaW5nKSBj
dXIuZ2V0VmFsdWUoKTsKCQl9CgkJaWYgKGN1ci5maXJzdCgic3NvSURQSW5pdGlhdGVkUmVkaXJl
Y3RVcmkiKSkgewoJCQlpZiAoKFN0cmluZykgY3VyLmdldFZhbHVlKCkgIT0gIm51bGwiKSB7CgkJ
CQlzc29JRFBJbml0aWF0ZWRSZWRpcmVjdFVyaSA9IChTdHJpbmcpIGN1ci5nZXRWYWx1ZSgpOwoJ
CQl9CgkJfQoJCWlmIChjdXIuZmlyc3QoInNzb01heEF1dGhBZ2UiKSkgewoJCQlzc29NYXhBdXRo
QWdlID0gKFN0cmluZykgY3VyLmdldFZhbHVlKCk7CgkJfQoJCWlmIChjdXIuZmlyc3QoImluc3Rh
bmNlSWQiKSkgewoJCQlpbnN0YW5jZUlkID0gKFN0cmluZykgY3VyLmdldFZhbHVlKCk7CgkJfQoJ
CWlmIChjdXIuZmlyc3QoInBvcnRObyIpKSB7CgkJCXBvcnQgPSAoU3RyaW5nKSBjdXIuZ2V0VmFs
dWUoKTsKCQkJaWYoIU1GVERhdGFDb25zdGFudHMuU0VSVkVSX0lOU1RBTkNFSURfREVGQVVMVC5l
cXVhbHMoaW5zdGFuY2VJZCkpewoJCQkJcG9ydCA9ICJETVpfUG9ydF8iICsgaW5zdGFuY2VJZCAr
ICJfIiArIHBvcnQ7CgkJCX0KCQl9CgkJdHJ5IHsKCQkJTUZUQ2VydGlmaWNhdGVEYXRhIGNlcnRp
ZmljYXRlRGF0YSA9IENvbW1vblByb3h5LnZpZXdNRlRLZXlEYXRhKHNzb0NlcnRpZmljYXRlKTsK
CgkJCVNTT01hbmFnZXIuaW5pdGlhbGl6ZVNTT0NlbnRyYWxpemVkKHRydWUsIGNlcnRpZmljYXRl
RGF0YSwgc3NvRGVmYXVsdENlcnRpZmljYXRlQWxpYXMsCgkJCQkJc3NvRW5jcnlwdENlcnRpZmlj
YXRlQWxpYXMsIHNzb1NpZ25DZXJ0aWZpY2F0ZUFsaWFzLCBzc29TUEVuZHBvaW50VXJsLCBzc29J
RFBNZXRhVXJsLAoJCQkJCXNzb0lEUEluaXRpYXRlZFJlZGlyZWN0VXJpLCBwb3J0LCBjbGllbnRJ
ZCwgc3NvTWF4QXV0aEFnZSk7Ci8vCQkJCQkJVmFsdWVzRW11bGF0b3IucHV0KG91dHB1dCwgIm1l
c3NhZ2UiLCBTU09NYW5hZ2VyLmluaXRpYWxpemVTU09DKHRydWUpKTsKCQkJVmFsdWVzRW11bGF0
b3IucHV0KG91dHB1dCwgInN1Y2Nlc3MiLCB0cnVlKTsKCgkJfSBjYXRjaCAoVGhyb3dhYmxlIGUp
IHsKCQkJVmFsdWVzRW11bGF0b3IucHV0KG91dHB1dCwgIm1lc3NhZ2UiLCBlLmdldE1lc3NhZ2Uo
KSk7CgkJCVZhbHVlc0VtdWxhdG9yLnB1dChvdXRwdXQsICJzdWNjZXNzIiwgdHJ1ZSk7CgkJfQoK
CQlmaW5hbGx5IHsKCQkJVmFsdWVzRW11bGF0b3IucHV0KHBpcGVsaW5lLCAib3V0cHV0Iiwgb3V0
cHV0KTsKCQl9Cgo=</value>
</Values>
