<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">add</value>
  <array name="sig" type="value" depth="1">
    <value>[i] recref:0:required scheduleInfo wm.mft.assets.rec.event:ScheduledEvent</value>
    <value>[o] field:0:required success</value>
    <value>[o] field:0:optional scheduleId</value>
    <value>[o] field:0:required message</value>
    <value>[o] field:1:required validationErrors</value>
  </array>
  <value name="subtype">unknown</value>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">CgkJU3RyaW5nIG1lc3NhZ2UgPSBNRlRSZXNvdXJjZXMuZ2V0TWVzc2FnZSgiMTAxMyIpOwoJCUlE
YXRhQ3Vyc29yIGN1ciA9IHBpcGVsaW5lLmdldEN1cnNvcigpOwoJCVN0cmluZyBzY2hlZHVsZUlk
ID0gIiI7CgkJSURhdGEgc2NoZXVsZVBpcGUgPSAoSURhdGEpIFZhbHVlc0VtdWxhdG9yLmdldChw
aXBlbGluZSwgInNjaGVkdWxlSW5mbyIpOwoJCWJvb2xlYW4gdmFsaWRhdGVJbnB1dCA9IHRydWU7
CgkJaWYgKCAiZmFsc2UiLmVxdWFsc0lnbm9yZUNhc2UoVmFsdWVzRW11bGF0b3IuZ2V0U3RyaW5n
KHBpcGVsaW5lLCAidmFsaWRhdGVJbnB1dCIpKSApIHsKCQkJdmFsaWRhdGVJbnB1dCA9IGZhbHNl
OwoJCX0KCQkKCQlTY2hlZHVsZWRBY3Rpb24gc2NoZWR1bGUgPSBudWxsOwoJCQoJCWJvb2xlYW4g
c3VjY2VzcyA9IGZhbHNlOwoJCVN0cmluZ1tdIG1lc3NhZ2VBcnJheSA9IG51bGw7CgkJdHJ5ewoJ
CQlpZiAoIHNjaGV1bGVQaXBlID09IG51bGwgKQoJCQkJdGhyb3cgbmV3IFNlcnZpY2VFeGNlcHRp
b24oTUZUUmVzb3VyY2VzLmdldE1lc3NhZ2UoIjEwMDEiLCAic2NoZWR1bGVJbmZvIikpOwoJCQkK
CQkJc2NoZWR1bGUgPSBBc3NldFV0aWxzLmdldFNjaGVkdWxlRXZlbnRGcm9tSURhdGEoc2NoZXVs
ZVBpcGUpOwoJCQlpZiAoIHNjaGVkdWxlLmdldE5hbWUoKSAhPSBudWxsICYmIHNjaGVkdWxlLmdl
dE5hbWUoKS5sZW5ndGgoKSA+IDI1NSApIHsKCQkJCXRocm93IG5ldyBTZXJ2aWNlRXhjZXB0aW9u
KE1GVFJlc291cmNlcy5nZXRNZXNzYWdlKCI4MTA1IikpOwoJCQl9CgkJCWlmICggc2NoZWR1bGUu
Z2V0RGVzY3JpcHRpb24oKSAhPSBudWxsICYmIHNjaGVkdWxlLmdldERlc2NyaXB0aW9uKCkubGVu
Z3RoKCkgPiAyNTYgKSB7CgkJCQl0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbihNRlRSZXNvdXJj
ZXMuZ2V0TWVzc2FnZSgiODEwNCIpKTsKCQkJfQoJCQlzY2hlZHVsZUlkID0gRXZlbnRzUHJveHku
YWRkU2NoZWR1bGUoc2NoZWR1bGUsIHZhbGlkYXRlSW5wdXQpOwoJCQlzdWNjZXNzID0gdHJ1ZTsK
CQl9Y2F0Y2ggKFRocm93YWJsZSB0KXsKCSAgICAJbWVzc2FnZSA9IHQuZ2V0TG9jYWxpemVkTWVz
c2FnZSgpOwoJICAgIAlpZiAoIHQgaW5zdGFuY2VvZiBNRlRTZXJ2aWNlRXhjZXB0aW9uICkgewoJ
ICAgIAkJTGlzdDxTdHJpbmc+IG1lc3NhZ2VMaXN0ID0gKChNRlRTZXJ2aWNlRXhjZXB0aW9uKSB0
KS5nZXRFcnJvck1lc3NhZ2VMaXN0KCk7CgkgICAgCQlpZiAoIG1lc3NhZ2VMaXN0ICE9IG51bGwg
KSB7CgkgICAgCQkJbWVzc2FnZUFycmF5ID0gbmV3IFN0cmluZ1ttZXNzYWdlTGlzdC5zaXplKCld
OyAKCSAgICAJCQltZXNzYWdlTGlzdC50b0FycmF5KG1lc3NhZ2VBcnJheSk7CgkgICAgCQl9CgkJ
CX0KCSAgICB9ZmluYWxseSB7CgkgICAgCVZhbHVlc0VtdWxhdG9yLnB1dChwaXBlbGluZSwgInN1
Y2Nlc3MiLCBTdHJpbmcudmFsdWVPZihzdWNjZXNzKSk7CgkgICAgCVZhbHVlc0VtdWxhdG9yLnB1
dChwaXBlbGluZSwgInNjaGVkdWxlSWQiLCBzY2hlZHVsZUlkKTsKCSAgICAJVmFsdWVzRW11bGF0
b3IucHV0KHBpcGVsaW5lLCAibWVzc2FnZSIsbWVzc2FnZSk7CgkJCWlmICggbWVzc2FnZUFycmF5
ICE9IG51bGwgKQoJCQkJVmFsdWVzRW11bGF0b3IucHV0KHBpcGVsaW5lLCAidmFsaWRhdGlvbkVy
cm9ycyIsbWVzc2FnZUFycmF5KTsKCQkJaWYgKGN1ciAhPSBudWxsKXsKCSAgICAJCWN1ci5kZXN0
cm95KCk7CgkgICAgCX0KCSAgICB9Cg==</value>
</Values>
